### ISSUE TITLE
Unable to re-invite someone who rejected a previous invite

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#1001]
**App**: Element X iOS 1.1.1 (228) on iPhone 12 mini running iOS 16.3.1

#### Steps
1. Tap on _Start  chat_
2. Search for a user by their display name
3. Tap on the search result
4. Have the other user reject the invite
5. Search for that user again by their display name
6. Tap on the search result again
7. Have the other user accept the invite

#### Expected Result
When the invite is initially rejected I am presented with an empty room with a message saying the user rejected my invite.
When the invite is initiated a second time and is accepted I am presented with a room with that user in it.

#### Actual Result
On the subsequent invite the user on the other end does not receive an invite notification, and I am taken to an empty room.

**Comment by Johennes** [comment]
@alfogrillo could you give this a look and check if it might be related to the SDK issue listed above? If so, we can close it as a duplicate.

**Comment by alfogrillo** [comment]
> @alfogrillo could you give this a look and check if it might be related to the SDK issue listed above? If so, we can close it as a duplicate.

Investigating it today.

**Comment by alfogrillo** [comment]
@ashughes1
We have this expectations:

After `4.` in your test case there are two cases:

1. The user proceeds with `5.` **without leaving the room first**. In this case the expected final result is seeing the room where the other person left. Unfortunately right now the title says "Empty Room", but the flow overall looks ok.

2. The user **leaves the room first**, and then proceed with `5.`. In this case a new room will be created and the other user will receive a new invite like you were expecting. Unfortunately this case isn't working. Just opened a detail tech issue [here](https://github.com/matrix-org/matrix-rust-sdk/issues/2017). It is worth checking at least that the correct behavior is restored after signing off and logging in again.

**Comment by Johennes** [comment]
Closing this as a duplicate now because 1 seems to work as expected and 2 is tracked in https://github.com/matrix-org/matrix-rust-sdk/issues/2017.

We also have https://github.com/vector-im/element-x-ios/issues/1077 and https://github.com/vector-im/element-x-android/issues/590 to improve the leaving DM experience in general.
