### ISSUE TITLE
Remove Beta wording

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#1012]
Or any similar wording to be able pass Apple review.

For example, we need to update the onboarding screen:
![image](https://github.com/vector-im/element-x-ios/assets/8418515/94190a4e-db09-480c-a92f-bfd23ae06e3f)

**Comment by stefanceriu** [comment]
"Beta" removed from localazy (from all languages), strings updated as part of [1041](https://github.com/vector-im/element-x-ios/pull/1041/files#diff-820dd031991c61213a1d080e54adb928764207a7e040523ead2060db18e08558R247)
