### ISSUE TITLE
Replies still contain the original redacted message

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#1021]
### Steps to reproduce

1. Have a reply on a message "A"
2. Remove message "A"

#### What did you expect?
The reply should not contain the original message which got redacted.

#### What happened instead?
Message "A" is still displayed in the reply.

### Application version

Nightly 1.1.2 (232)

### Will you send logs?

No

**Comment by manuroe** [comment]
Tested it again on 1.1.8.272. The reply contains the original message until you reopen the room.

**Comment by jplatte** [comment]
Should be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2307.

**Comment by bnjbvr** [comment]
As per previous message, closing. Please reopen if this is still a problem.
