### ISSUE TITLE
Add in Notification settings the option to enable/disable notifications on this device

### ISSUE THREAD

**Issue by giomfo** [vector-im/element-x-ios#1023]
## Description ##
Add a toggle at the top of the Notifications settings to handle in the application the push service registration.

<img width="446" alt="image" src="https://github.com/vector-im/element-x-ios/assets/8969772/c09b0af1-ee67-4a33-aa6c-994f45569267">

We should check the permission at the system level. The notifications must be allowed at the system level if the user decides to turn them on in the application. We prompt the user to get the permission like this is the case on first launch.
If the permission has been removed/cancelled at the system level, an item is displayed at the top of the Notification settings screen:
- the users are taken to the system settings when they click on this item).
- the toggle defined at the application level is still ON even if the permission is lost:

<img width="260" alt="image" src="https://github.com/vector-im/element-x-ios/assets/8969772/2c5ec8f0-661c-4441-af24-674cfd2af592">

- if the toggle is switched off, the warning is hidden

## Bonus ##

When this flag will be added at the application level, we will be able to detect on application resume when the user turned ON the notification for Element whereas the permission has been disabled at the system/device level. In that case a banner should be displayed to notify the user:
<img width="260" alt="image" src="https://github.com/vector-im/element-x-ios/assets/8969772/9f94b651-29c1-4612-b36a-94b77d7a0d70">

**Comment by giomfo** [comment]
When I discussed again with the dev team about this flag (global notification setting toggle) defined at the application level, we realized that we are going to the wrong direction. Indeed adding this flag introduces some complexity that we don't need for the moment in EX. We want to keep notification setting handling simple in EX -> we should only use the existing system toggle to control globally the notifications on a device.

The points that we were trying to handle here are:
- provide a complete view of the current notification configuration inside the EX application (Notification Settings screen)
- let the user be able to turn off/on globally the notifications from the application settings (to mute all rooms temporarily)

To satisfy these 2 points, we only need to display in the application the current configuration observed from the device settings, and let the user be able to navigate to this device settings to change it.

We suggest here to add this kind of item at the top of the Notification Settings screen:
<img width="401" alt="tmp" src="https://github.com/vector-im/element-x-ios/assets/8969772/c30a31a2-16ea-4bf8-a612-0e6a2c29e8be">

The users are taken to the system settings when they click on it.

@VolkerJunginger are you ok with this suggestion? The purpose is to keep it simple (waiting for any user feedbacks before adding more complexity).

FYI the complexity that I mentioned above arose when we discussed about the following points :
- what should be the default value of this new application flag? we were considering it true by default, but then we realized that we will have to turn it off if the user rejects the permission demand from the system after the first login, in order to not prompt the user again.  
- the current wording itself risks to put the users in difficulties :
<img width="441" alt="image" src="https://github.com/vector-im/element-x-ios/assets/8969772/8e2ecc37-b966-4021-82de-9f7bda2ba25b">

we ease the wording if we don't introduce the toggle at the application level

**Comment by VolkerJunginger** [comment]
I would be ok to send the user to the system settings IF we would have the possibility to mute single rooms.

But as long as we don't have this it feels wrong to me to have a messenger where the only option to mute the noise is in system settings. Especially on iOS the system setting are often a one-way route for unexperienced users.

**Comment by giomfo** [comment]
> the system setting are often a one-way route for unexperienced users.

I see what you mean, but I'm not sure this is still the case. We miss recent and actual user feedbacks on this point. The user usage have changed. 
The dev team and I think that it would be better to wait for some actual user feedbacks (or place some user testings) before adding this complexity. My suggestion is a temporary solution in order to wait before adding 2 settings inside EX that the user will probably misunderstand. I double checked with @manuroe, he agrees with us to not introduce this toggle at the app level.

If you confirm your wish to add this toggle/flag at the application level. I would suggest the following behavior for its implementation:
- Notifications are enabled by default in EX (the flag is true by default)
- This flag is **unchanged** if the user rejects the system permission demand in the application after the login (the banner is displayed and the toggle is ON in the settings screen)
- If the flag is ON whereas the permission has been disabled at the system/device level, we **don't prompt** the user when the application is resumed (we don't implement what I labelled "Bonus" in my first description). This is to prevent us from prompting too much the user. One option would be to reset the flag when the user discards the dialog, but we agreed to not automatically change the flag value. Another option would be to add an internal flag to remember if we already prompt the user, but this is a part of the complexity that we want to avoid (except if this is actually need).

**Comment by VolkerJunginger** [comment]
"If you confirm your wish to add this toggle/flag at the application level. I would suggest the following behavior for its implementation:

- Notifications are enabled by default in EX **(the flag is true by default)**

- This flag is unchanged if the user rejects the system permission demand in the application after the login **(the banner is displayed and the toggle is ON in the settings screen)**

- If the flag is ON whereas the permission has been disabled at the system/device level, we don't prompt the user when the application is resumed **(we don't implement what I labelled "Bonus" in my first description)**. (...)."

Yes, I lets go for this.
