### ISSUE TITLE
User’s permission through the AppTrackingTransparency framework

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#1060]
Element X 1.1.2 has been rejected for the following reason:

Guideline 5.1.2 - Legal - Privacy - Data Use and Sharing

The app privacy information you provided in App Store Connect indicates you collect data in order to track the user, including Other Diagnostic Data. However, you do not use App Tracking Transparency to request the user's permission before tracking their activity.

Starting with iOS 14.5, apps on the App Store need to receive the user’s permission through the AppTrackingTransparency framework before collecting data used to track them. This requirement protects the privacy of App Store users.

Next Steps

Here are two ways to resolve this issue:

- If you do not currently track, or decide to stop tracking, update your [app privacy information in App Store Connect](https://developer.apple.com/help/app-store-connect/manage-app-information/manage-app-privacy). You must have the [Account Holder or Admin role](https://developer.apple.com/support/roles/) to update app privacy information.

- If you track users, you must [implement App Tracking Transparency](https://developer.apple.com/documentation/apptrackingtransparency) and request permission before collecting data used to track. When you resubmit, indicate in the Review Notes where the permission request is located.

Resources

- Tracking is linking data collected from your app with third-party data for advertising purposes, or sharing the collected data with a data broker. Learn more about [tracking](https://developer.apple.com/app-store/app-privacy-details/#user-tracking).
- See Frequently Asked Questions about the [requirements for apps that track users](https://developer.apple.com/app-store/user-privacy-and-data-use/#permission-to-track).
- Learn more about designing [appropriate permission requests](https://developer.apple.com/design/human-interface-guidelines/patterns/accessing-private-data/).

**Comment by stefanceriu** [comment]
This is a bit confusing, we're definitely not `linking data collected from your app with third-party data for advertising purposes, or sharing the collected data with a data broker`

I believe we don't want this sort of alert to pop up in the app

![image](https://github.com/vector-im/element-x-ios/assets/637564/e8be0c57-fa61-4f32-8ec8-2800e84ecd04)

I believe we can tweak what we chose in the `App Privacy` section and try again
