### ISSUE TITLE
You can get a big ugly gap in the top of the roomlist when jumping to top of list & focusing the search bar.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1066]
### Steps to reproduce

1. Open the room list
2. Scroll down a few pages
3. Tap on the titlebar to jump to top
4. Tap on the Search bar to start filtering

Observe an ugly-ass gap (above the new 'Invites' row)

![IMG_0477](https://github.com/vector-im/element-x-ios/assets/1294269/bf89114f-9410-4ca9-b92c-f11789a5866f)

5. This then disappears if you start to type and filter.

It looks suspiciously like we're failing to recalculate vertical offsets correctly after displaying the keyboard.

#### What did you expect?

No ugly ass gaps.

#### What happened instead?

Ugly ass gaps.

### Application version

235

### Will you send logs?

No

**Comment by manuroe** [comment]
Note that the gap can hides itself quickly but it is not guaranteed. We should not have this gap in first place anyway.

**Comment by manuroe** [comment]
Fixed during UI polish work.
