### ISSUE TITLE
Syncing prompt should only appear after ~1s of trying to sync

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1103]
### Steps to reproduce

1. bg app
2. fg app
3. see syncing spinner flicker up for about 100ms
4. wonder why it bothered showing the spinner at all; it’s just distracting and makes the app feel slow by highlighting that it needed to sync

#### What did you expect?

only see the syncing spinner if the app is stuck syncing for a significant length of time - long enough for the user to wonder whether it’s stuck or not. probably 500-1000ms

#### What happened instead?

showing it all the time is just visual noise

### Application version

242

### Will you send logs?

No

**Comment by ara4n** [comment]
also, sometimes it doesn't appear at all - especially if you're looking at a timeline when you fg, it shows you stale fg with no sync spinner until it eventually updates

**Comment by Hywan** [comment]
Delay before showing the sync indicator is normal and expected.

There is a delay before showing the sync indicator. That was requested by @manuroe. EAX was doing this before. This is defined [here](https://github.com/matrix-org/matrix-rust-sdk/blob/6131e41183d969c6684006830eed8a7fa4b89aaf/crates/matrix-sdk-ui/src/room_list_service/mod.rs#L99-L109). The code that implements the `SyncIndicator` logic is [here](https://github.com/matrix-org/matrix-rust-sdk/blob/6131e41183d969c6684006830eed8a7fa4b89aaf/crates/matrix-sdk-ui/src/room_list_service/mod.rs#L344-L392).
