### ISSUE TITLE
Room list isn’t updating at all

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1106]
### Steps to reproduce

1. Run the app for a while - say 3h (in both fg and bg)
2. Check the room list
3. Observe that the room list ordering and preview contents and timestamps are all 3h old, despite having gone into those rooms and loading their history.

#### What did you expect?

accurate roomlist

#### What happened instead?

roomlist frozen in amber

### Application version

242

### Will you send logs?

Yes

**Comment by manuroe** [comment]
@Hywan, this issue existed before the new room list API. I wanted to test it after the new API landing before we spend time to investigate it.

**Comment by Hywan** [comment]
Maybe https://github.com/matrix-org/matrix-rust-sdk/pull/2103/ will fix it if it's a problem with session expiration.

**Comment by ara4n** [comment]
it's still here on build 249. will rs

**Comment by ara4n** [comment]
this seems to be working now on 254, but i am bitten by https://github.com/vector-im/element-x-ios/issues/1173 which is almost as bad

**Comment by manuroe** [comment]
Let's close it and track #1173 with fresher rageshakes.
