### ISSUE TITLE
Notification broken when matrix.org is blocked

### ISSUE THREAD

**Issue by nisbet-hubbard** [vector-im/element-x-ios#1133]
### Steps to reproduce

Push notification on iOS is broken in geography where matrix.org is blocked.

#### What did you expect?

FluffyChat’ push notification is working fine, whilst Element iOS’s is similarly broken. This is related to matrix.org getting blocked in the area.

#### What happened instead?
No push notification is received. And the following error message appears in homeserver log:
```
WARN conduit::service::pusher: Could not send request to pusher https://matrix.org: Could not send request to pusher https://matrix.org: error sending request for url (https://matrix.org/_matrix/push/v1/notify): error trying to connect: operation timed out
```

### Your phone model

SE2

### Operating system version

16.3.1

### Application version

111(48)

### Homeserver

Conduit next

### Will you send logs?

No

**Comment by pixlwave** [comment]
Unfortunately the notifications backend (Sygnal) is a hard-coded end-point per client in the matrix world. If this is blocked you will need to find another client that has its own instance of Sygnal on a different URL.
