### ISSUE TITLE
Timeline - Report Content

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#115]
As an user I should be able to report malicious messages so that we can all have nice conversations

- [x] Message contextual report action
- [x] A way to specify the reason
- [x] Explain to the user what's happening when they report content
- [x] Give a visual feedback when the content has been sent successfully
- [x] Do not propose to report content for current user's own messages

**Comment by Velin92** [comment]
- Explain to the user what's happening when they report content
- Give a visual feedback when the content has been sent successfully

We need design and copies for these two

**Comment by jplatte** [comment]
In terms of the Rust code required for this, it should be as easy adding a method to [this impl block](https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/room.rs#L177) (and importing `matrix_sdk::ruma::api::client::room::report_content` at the top of the file) that calls

```rust
RUNTIME.spawn(async move {
    self.room.client().send(report_content::v3::Request::new(/* ... */), None).await?;
    Ok(())
});
```

The function will have to return `Result<()>` like others in that impl block so a failure to send the request can be detected. Also the method needs to be added to [`api.udl`](https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/api.udl).

**Comment by Velin92** [comment]
Will split this in two PRs:

In the first one we will only add the repot content functionality as it is also currently available on El-iOS, here it is:
https://github.com/vector-im/element-x-ios/pull/587

In the next one, once the designs are available we will add these two extra features:
- Explain to the user what's happening when they report content
- Give a visual feedback when the content has been sent successfully

**Comment by amshakal** [comment]
Link to figma: 
https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=546%3A75404&t=pMDua121dCFpWKLL-1
