### ISSUE TITLE
Expanding the keyboard doesn’t always scroll up the timeline and gets stuck in a loop

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1150]
### Steps to reproduce

1. Open room
2. Tap on composer
3. Composer expands to cover the timeline
4. You have to manually scroll the timeline back down...
5. ...which hides the composer
6. goto 2

You can break out of the loop by hitting the "jump to bottom"
button, i think.

Happens as of the last few builds, aboue 30% of the time

### Application version

249

### Will you send logs?

No

**Comment by ara4n** [comment]
https://github.com/vector-im/element-x-ios/assets/1294269/3d09800d-6b8a-41f1-a43e-676f365e086d

**Comment by ara4n** [comment]
i haven't seen this in weeks. @stefanceriu i assume something fixed it?

**Comment by stefanceriu** [comment]
> i assume something fixed it?

Most likely the refactoring around flipping the timeline
