### ISSUE TITLE
Message actions menu should be disabled on failed or local echo

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#1151]
At least some of the actions should be disabled. Actions like reply or reaction makes no sense on a failed message. 

UX question are we happy with the two user interactions we have in this case?:
- simple tap to retry or cancel the message
- long press for actions menu

**Comment by Velin92** [comment]
the simple tap could create some issues with images and medias, for now the tap is localised only on the red alert icon/timestamp

However yeah we should definitely remove reaction, reply and maybe even edit?

**Comment by Velin92** [comment]
What are the actions we want to explicitly filter for failed messages?
These are all the possible types:
 ```
   case copy
    case edit
    case copyPermalink
    case redact
    case reply
    case forward(itemID: String)
    case viewSource
    case retryDecryption(sessionID: String)
    case report
    // reactions are not included in this enum but we can filter them out too
```

**Comment by Velin92** [comment]
For now I identified these cases that I feel should be the ones that we should filter out:
```
var shouldAppearInFailedEcho: Bool {
        switch self {
        case .edit, .copyPermalink, .redact, .reply, .retryDecryption, .report:
            return false
        default:
            return true
        }
    }
```

**Comment by manuroe** [comment]
For redacted, it could be just for debug purpose :
   - case viewSource

**Comment by Velin92** [comment]
@manuroe  sadly with the current API is not possible to edit a failed local echo, so probably we need to filter that out too... for now

**Comment by callumu** [comment]
@Velin92 what's the issue with the tap on failed media messages? 

I'd rather keep retry and remove in an action sheet and not add these options to the long press bottom sheet.
