### ISSUE TITLE
failed msgs won’t resend

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1153]
### Steps to reproduce

1. message failed for some reason (bad wifi?)
2. tried to resend when on good data
3. silently failed

### Application version

251

### Will you send logs?

Yes

**Comment by ara4n** [comment]
it also then deleted my unsent msgs (including those which claimed to send after the unsent ones?)

**Comment by manuroe** [comment]
The 2nd rageshake has a video.

**Comment by Velin92** [comment]
Can't reproduce the issue, we are looking at the logs but didn't find anything particularly weird so far, so @jplatte  improving the logging for the resend behaviour.

**Comment by jplatte** [comment]
If / when this happens again, the 'View Source' debug info for the item (the one that was retried after the connection came back) would be helpful.

**Comment by manuroe** [comment]
The case we got today appeared to be a lock issue between the app and NSE:

<img width="353" alt="image" src="https://github.com/vector-im/element-x-ios/assets/8418515/75b0c756-a35f-41fd-b851-6820a62a94bd">


The encryption loop is only under a feature flag and not in production a better implementation of the lock is coming.

**Comment by ara4n** [comment]
i can’t repro this when on single ss loop. i had it with two ss loops enabled in settings tho

**Comment by manuroe** [comment]
The 2 SS loops has a new lock mechanism that will fix this problem.
