### ISSUE TITLE
Push notifications are unreliable

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1172]
### Steps to reproduce

1. Run EI and EIX side by side
2. Notice that often EI shows a notif which EIX doesn’t.

Apparently this is because EIX executes push rules clientside and if SS has never seen a given room, it fails to execute the rule.

However, SS should know all rooms via allrooms, so i’m confused how this breaks

#### What did you expect?

reliable push

#### What happened instead?

push msgs getting dropped

### Application version

254

### Will you send logs?

No

**Comment by Velin92** [comment]
We just disabled the client side filtering given the push rules context of a room for now, until we find a way to have push rules work reliably with SS.
https://github.com/vector-im/element-x-ios/issues/1155

**Comment by manuroe** [comment]
We need to revisit is when https://github.com/matrix-org/matrix-rust-sdk/pull/2252 and all have landed.

**Comment by Velin92** [comment]
We are inserting an FF in nightly which should fix the issue in this PR:
https://github.com/vector-im/element-x-ios/pull/1412

Of course the solution is experimental that's way it's hidden behind an FF.
