### ISSUE TITLE
Replying to "Unable to decrypt" message does nothing

### ISSUE THREAD

**Issue by Velin92** [vector-im/element-x-ios#1185]
### Steps to reproduce

1. Open context menu on an "Unable to decrypt" message
2. Select Reply
3. Send a message

#### What did you expect?
That it should still quote the unencrypted message (even if I am not able to see the content) and then send the message with a reply, or at least not have the option to reply to an unencrypted message at all.
#### What happened instead?
Nothing, the reply does not get sent, here is a video:

https://github.com/vector-im/element-x-ios/assets/34335419/651c0464-6bae-4df3-92ab-0c48f4092cd0

### Will you send logs?

No

**Comment by Velin92** [comment]
Maybe for now we should just avoid replying to unencrypted messages entirely

**Comment by VolkerJunginger** [comment]
We should not let users interact w. unencrypted messages except for "retry to decrypt" at all.

**Comment by Velin92** [comment]
fair! then I'll work on filtering out all the actions aside view source and retry decrypt
