### ISSUE TITLE
Set up Nightly builds

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#12]
We want to automate the release of develop builds so that we can have feedbacks sooner a la develop.element.io.

**Comment by moodler** [comment]
Am not able to help directly until nightly builds are ready but just wanted to say that users out here are very much looking forward to Element X and we're  sending you good vibrations!   Keep up the good work!

**Comment by ismailgulek** [comment]
Ops issue: https://github.com/matrix-org/internal-config/issues/1276

**Comment by stefanceriu** [comment]
Duplicate
