### ISSUE TITLE
Room previews in the room list are often missing the sender details

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1204]
### Steps to reproduce

1. Look at the room previews in the room list
2. Many of them either have a blank line where you might see the message sender's name should be, or are just missing the sender.
4. Enter the room, wait for the users' profiles to load in the timeline, go back to room list, and now the sender is shown.

#### What did you expect?

1. sender names should not be missing
2. sender names should be inlined rather than get a line of their own.

#### What happened instead?

Stuff like this:

![image](https://github.com/vector-im/element-x-ios/assets/1294269/888b8850-7a4b-4094-af2c-c473b4ca149f)

(pimpleeater only turns up because i viewed the room first to load their profile)

### Application version

257

### Will you send logs?

No

**Comment by ara4n** [comment]
The blank lines are caused by replies having mangled previews, apparently

**Comment by kegsay** [comment]
You can use `required_state: [["m.room.member", "$LAZY"]]` for the `VisibleRooms` list to pull in the member events of the senders.
