### ISSUE TITLE
Sliding sync slow to send back new data

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#1218]
Use case:
* logged into the `bigtestaccount`
* backgrounded the application and wait for the sync to stop
* sent a new message to `bigtestaccount` and waited for the push notification to come in
* tap on the notification, go into the room and wait for the message to appear

Looking at the network logs it took a total of 19! requests and around 4.5 seconds. Har archive available [here](https://matrix.to/#/!kCCQTCfnABLKGGvQjo:matrix.org/$ivcgoI94OoNiueJyRFb7a0NIFBIzDookUhhj4Sy8BCc?via=matrix.org&via=element.io&via=one.ems.host)

**Comment by ara4n** [comment]
hm, i wonder if that's the same problem as 1105. i reliably see 10-20s delay (but that might be because my acct is proportionately bigger than bigtestaccount)

**Comment by manuroe** [comment]
There is a SDK [patch](https://github.com/matrix-org/matrix-rust-sdk/pull/2192) as a workaround for the server behavior. We need to revisit it. We do not know the consequence.

At least, it allows to see that SS can run at light speed even for large account.

**Comment by manuroe** [comment]
Subscription implementation has been improved on the proxy side from July, 4th
