### ISSUE TITLE
Invites button needs a larger tap area

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#1221]
### Steps to reproduce

1. Make sure you're on the home screen with a list of rooms showing
2. Swipe down to show the search bar
3. Have someone send you an invite
4. Try tapping the top region of the Invites button 

#### What did you expect?
Tapping anywhere within the Invites button should trigger the Invites list. Better still, there should be a certain padding around the button that triggers it.

#### What happened instead?
Tapping the top area of the Invites button triggers focus of the Search box instead. In the end I have to be careful to tap the bottom region of the Invites button to trigger the Invites list.

#### UI referred to in this issue
![IMG_3825](https://github.com/vector-im/element-x-ios/assets/766595/08d24c19-9c6c-494a-a644-8aa63a756400)

### Your phone model

iPhone 12 mini

### Operating system version

iOS 16.5

### Application version

1.1.6 (267)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by stefanceriu** [comment]
I already increased the overall size of the invites button together with other changes but I can't find the exact commit at the moment. Please reopen if it's still an issue.
