### ISSUE TITLE
Couldn't reach the homeserver

### ISSUE THREAD

**Issue by Ciechom** [vector-im/element-x-ios#1231]
### Steps to reproduce

1. I try to enter my own server
2. I write the address: matrix.ciechom.eu
3. I get the error
![IMG_0659](https://github.com/vector-im/element-x-ios/assets/6024778/44af9bce-788c-4b6d-a308-8748a2e0f76f)

### Outcome

I expect to be able to login

I get the error

On another server which doesn't support ssync I get the info message that it doesn't support it. On my server it doesn't matter what is in my .well-known/matrix/client i get the same error

My server points to my ssync server from matrix.ciechom.eu/.well-known/matrix/client

### Your phone model

Iphone 13 pro max

### Operating system version

Ios 17 beta

### Application version

1.1.7 (53)

### Homeserver

Synapse 1.85.1

### Will you send logs?

Yes

**Comment by Velin92** [comment]
Does the server support Sliding Sync?

**Comment by Ciechom** [comment]
Yes, the sliding sync server lives at: https://sliding.matrix.ciechom.eu which should be supplied from https://matrix.ciechom.eu/.well-known/matrix/client

**Comment by Ciechom** [comment]
Someone on #element-x-ios:matrix.org told me to check if I have TLS versions other than TLSv1.3 enabled, and I didn't. After allowing older versions, I was able to log in.

**Comment by fuomag9** [comment]
I have the exact same issue with my server fuo.fi and I'm using caddy as my reverse proxy. @Ciechom how did you fix it?

**Comment by pixlwave** [comment]
Adding a link to https://github.com/vector-im/element-x-ios/issues/786 for anyone encountering this in the future, which was the actual issue here.
