### ISSUE TITLE
Rageshake doesn't send after app crash

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-ios#1238]
### Steps to reproduce

1. Trigger https://github.com/vector-im/element-x-ios/issues/1237
2. After the app crashes, you see the OS desktop and a pop-up asking you to submit a rageshake
3. Submit the rageshake

#### What did you expect?
Rageshake is sent

#### What happened instead?
Rageshake does not send

When I next start up the app, I get asked to send a rageshake again, and that rageshake is sent (attaching)

### Your phone model

iPhone 11

### Operating system version

16.5

### Application version

1.1.8 (272)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
The issue here is that the prompt shown was Apple's, not ours. It only affected internal users.
