### ISSUE TITLE
App didn’t subscribe to room (and so timeline was dead entirely)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1242]
### Steps to reproduce

1. using app
2. switched room (can’t remember how; maybe via room list, but more likely by tapping a push notif)
3. new room wasn’t subscribed in ss, so the timeline never updated.

#### What did you expect?

timelines which aren’t stuck.

### Application version

271

### Will you send logs?

Yes

**Comment by manuroe** [comment]
SS proxy problems:
- https://github.com/matrix-org/sliding-sync/issues/192
- https://github.com/matrix-org/sliding-sync/issues/193
