### ISSUE TITLE
Navigating from roomlist to timeline is weirdly slow (200ms or so) 

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1246]
### Steps to reproduce

1. Be in room list
2. Tap on a room
3. Watch 100-200ms of lag before the app responds
4. Hit back button to go back to the roomlist
5. App responds instantly

#### What did you expect?

Instant navigation

#### What happened instead?

Weirdly delayed navigation that feels laggy

### Homeserver

271

### Will you send logs?

No

**Comment by manuroe** [comment]
Was it on low battery mode?
We cannot reproduce the issue?

**Comment by ara4n** [comment]
> Was it on low battery mode?
> 
> We cannot reproduce the issue? 

no, normal battery, and i can repro reliably.

sm also added in the public EIX room:

> I will say that once you have scrolled back a long way, that room is noticeably slower to re-enter than the rooms with small scrollback

**Comment by manuroe** [comment]
@ara4n can we close this one?

**Comment by ara4n** [comment]
nope, folks are still reporting it, and I still see it - Valere spotted it a few hours ago, and Jan in the public room.  N.B. i do *NOT* think it's related to account size.

**Comment by stefanceriu** [comment]
I might have an idea on this: I spotted some code that loads members and maps them on the main thread while doing performance tuning yesterday. Doing calls through FII for various member properties can easily slow down the app and it might be the reason the push animation hangs

**Comment by Jaffex** [comment]
If this behaviour is considered normal in low battery mode, maybe, but I feel like the issue has gotten worse between 1.2.8 and 1.2.9.

I'm only experiencing it in low battery mode but never experienced it before updating to 1.2.9

(On iPhone 12 mini, freshly updated to iOS17)

Here's a replay of opening a room:
[Replay1.webm](https://github.com/vector-im/element-x-ios/assets/31133207/fe527af3-23ac-4f19-a7ed-8beeaaa8d02e)

This also affects opening the message composer:
[Replay2.webm](https://github.com/vector-im/element-x-ios/assets/31133207/d0eb3677-34b0-4904-b9a5-c88dd50b405a)

Please note the light grey circle that moves is the indicator for my taps (not the one with the white center).
Tap occurs when the dot begins to move, not when it arrives at it's destination.

While I understand that battery saving mode will have some impact on performance, I usually don't "feel" it as much in other messenger apps (not even the old element) as much as in element x currently.

**Comment by ara4n** [comment]
@Jaffex thanks for the recordings.  I'm a bit worried that AssistiveTouch actually adds latency, so makes it a bit hard to see what's going on.

I made three slowmo recordings with another iPhone (opening big room on EX, small room on EX, and opening conversation on iMessage).  EX took 33 frames (at whatever slowmo framerate is on an iPhone 14 Pro) for the transition to start regardless of the size of room.  iMessage took 20 frames: therefore EX is about 40% slower for the roomlist to react to being tapped than on iMessage.

It'd also be nice if EX actually highlighted the room when you tap on it, to make things feel more responsive.  But irrespective of that feedback, we're still more sluggish for some reason.

**Comment by stefanceriu** [comment]
> I might have an idea on this:

Handled here https://github.com/vector-im/element-x-ios/pull/1757

**Comment by stefanceriu** [comment]
Found something else too: https://github.com/vector-im/element-x-ios/pull/1760

Between the 2 of them I think we'll be able to close this ticket but leaving it open for now to see how it goes out in the wild

**Comment by ara4n** [comment]
confirmed fixed by https://github.com/vector-im/element-x-ios/issues/1246 - it's now 21 frames for the app to load a room.

There's a separate problem that if you backpaginate a room loads, then it takes a while for the room to re-open later, which i can file separately.

**Comment by ara4n** [comment]
(filed as  https://github.com/vector-im/element-x-ios/issues/1771)
