### ISSUE TITLE
Swiping up hides the Start Chat button

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#1255]
### Steps to reproduce

1. Start from the room list view with the list scrolled to the top
2. Swipe up
3. Swipe down

#### What did you expect?
Start Chat button should remain on the screen

#### What happened instead?
Start Chat button disappears until I swipe back down

https://github.com/vector-im/element-x-ios/assets/766595/9b610126-8808-4fb4-ae90-6bcb723d6fab

### Your phone model

iPhone 12 mini

### Operating system version

iOS 16.5.1

### Application version

1.1.8 (271)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ara4n** [comment]
this is a deliberate (albeit opinionated) design to maximise vertical screen realestate. if you want to see the bottom UI, scroll up.

**Comment by ashughes1** [comment]
> this is a deliberate (albeit opinionated) design to maximise vertical screen realestate. if you want to see the bottom UI, scroll up.

I can see the benefit when the room list is populated with multiple pages of rooms, but not when there are only a couple rooms listed and the rest of the UI is blank (ie. you have ample vertical screen to spare). To me the user experience feels weird in this particular case.

**Comment by kittykat** [comment]
@amshakal What is the design perspective on this?

**Comment by amshakal** [comment]
Yes, this is deliberate. We *could* treat it differently for when we have less than x chats on the screen, but again, don't know if we should act on it right now.

**Comment by pixlwave** [comment]
Closing this as a defect then. We can create an enhancement after reviewing the behaviour if it isn't desirable.
