### ISSUE TITLE
Turning on airplane mode then opening a room displays undismissable "Failed loading messages" error

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#1256]
### Steps to reproduce

1. Be on the room list view with some rooms populating the list
2. Switch on airplane mode
3. Tap on a room
4. Wait

#### What did you expect?
Either display cached messages or display a dismissible "Cannot load messages while offline" message or something like that.

#### What happened instead?
When tapping a room the OFFLINE pill turns into a Syncing pill that spins for several minutes. Once it times out it displays an error, "Failed loading messages" that I cannot seem to dismiss. Turning off airplane mode restores the connection and loads the messages as expected.

![IMG_3826](https://github.com/vector-im/element-x-android/assets/766595/a97d2f5f-d12c-495b-8a79-a3a5b27a079f)

### Your phone model

iPhone 12 mini

### Operating system version

iOS 16.5.1

### Application version

1.1.8 (271)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by Hywan** [comment]
Should be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2386.

I assign @stefanceriu as a little more work is required on iOS side to make it work. Up to you my friend!

**Comment by stefanceriu** [comment]
Fixed in https://github.com/vector-im/element-x-ios/pull/1469
