### ISSUE TITLE
Opening app in airplane mode displays empty but loading room list

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#1257]
### Steps to reproduce

1. Have the app open with a list of rooms
2. Turn on airplane mode
3. Swipe up from the bottom of the screen to dismiss the app
4. Open the app again

#### What did you expect?
Any cached data should be shown, or a relevant user message about being in airplane mode.

#### What happened instead?
The app sits there trying to sync, seemingly forever, with an empty room list trying to load rooms.
![IMG_3829](https://github.com/vector-im/element-x-ios/assets/766595/885e097a-d9a2-4981-b8a8-1dde55b98bb7)

### Your phone model

iPhone 12 mini

### Operating system version

iOS 16.5.1

### Application version

1.1.8 (271)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Will be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2386 in the next SDK release

**Comment by Hywan** [comment]
Should be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2386.

I assign @stefanceriu as a little more work is required on iOS side to make it work. Up to you my friend!

**Comment by stefanceriu** [comment]
> Should be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2386.

with the addition of https://github.com/vector-im/element-x-ios/pull/1469
