### ISSUE TITLE
Context menu for unsent msgs is missing resend item

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1258]
### Steps to reproduce

1. fail to send a msg
2. long tap on the msg
3. feel surprised that the context menu doesn’t let you resend it. worse, the red item in the menu deletes the msg (whereas you might expect the red item to match the red unsent warning to let you resend)
4. realise you have to short tap on the unsent warning instead to resend

#### What did you expect?

context menu should let you resend, not a hidden menu on the unsent warning.

### Application version

271

### Will you send logs?

No

**Comment by manuroe** [comment]
Dup of https://github.com/vector-im/element-x-ios/issues/1186. Check this [comment](https://github.com/vector-im/element-x-ios/issues/1186#issuecomment-1611662300).
