### ISSUE TITLE
Room previews don't update when megolm keys arrive

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1267]
### Steps to reproduce

1. Open room list after being offline for a bit
2. See room previews saying "Decryption error" or similar
3. Click into room; message shows up fine.
4. Conclude that the room preview in the room list isn't updating itself when keys arrive, and so lies about messages being undecryptable.

#### What did you expect?

Accurate room previews, and no UISIs

#### What happened instead?

Room previews which lie about things being UISI when they're not.

### Application version

276

### Will you send logs?

No

**Comment by pixlwave** [comment]
Fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2142
