### ISSUE TITLE
Attach screenshots to bug reports

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#127]
We're currently automatically detecting if the user took a screenshots and prompting them to submit a bug report which is far from ideal. We need to disable automatic detection and implement file attachment functionality in the bug reporting screen.

**Comment by pixlwave** [comment]
Probably makes sense to wait until we upgrade to Xcode 14 for this one and use the new `PhotosPicker` or `.photosPicker()` view/modifier.

**Comment by Velin92** [comment]
Do we want to allow the user to upload screenshots of any size? Or should be a limit on how big the images are?

**Comment by stefanceriu** [comment]
Let's start with one single image and no videos for now. Also no resizing but let's do make sure we show a decent error if we go over the allowed attachment limit (100mb I think)
