### ISSUE TITLE
Reading a room doesn't clear its notifications from the Notification Center

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1277]
### Steps to reproduce

1. See a push. Don't tap on it.
2. Open the room manually in EX and read the msg
3. Observe the push hasn't disappeared from the Notification Center

#### What did you expect?

Notification Center should declutter as you read notifs.

#### What happened instead?

Much clutter.

### Application version

276

### Will you send logs?

No

**Comment by Velin92** [comment]
@VolkerJunginger I imagine we want to remove all message notifications that belong to a specific room if such room has been opened manually right?

**Comment by VolkerJunginger** [comment]
yes, sounds right.
