### ISSUE TITLE
DM Details is no longer working properly

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#1281]
### Steps to reproduce

- Open a DM with someone (or create a new one)
- Make sure the other person accepts the DM. There must be 2 people in the room.
- Tap the room header at the top of the screen

#### What did you expect?
To see the DM details screen

#### What happened instead?
The general room details screen is shown instead

Likely related to: https://github.com/matrix-org/matrix-rust-sdk/issues/2213

### Your phone model

Simulator

### Operating system version

16.5.1

### Application version

1.1.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by kittykat** [comment]
I think this has been fixed so will close it now. Please open a new issue if you experience it again!
