### ISSUE TITLE
Room list -> Room animation stutters badly whenever the keyboard is open

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1282]
### Steps to reproduce

1. Go to room
2. Open keyboard
3. Go back to roomlist
4. Observe the animation judder nastily back and forth as the keyboard gets hidden

Compare the two transitions below:

https://github.com/vector-im/element-x-ios/assets/1294269/a869e900-5ec4-45b1-805d-dad9ac3a3d9b

#### What did you expect?

smooth transitions

#### What happened instead?

juddering janky transition when keyboard is open in a room

can we change the timing of the keyboard hide anim?

Turns out this may have been like this forever, although i only noticed on release day.

### Application version

276

### Will you send logs?

No

**Comment by Velin92** [comment]
I think dismissing the room should just dismiss the keyboard entirely, until the user needs it again.
