### ISSUE TITLE
Do not block UI on file upload

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-ios#1283]
### Steps to reproduce

1. Room -> + -> Photo & video Library
2. Select photo
3. Preview and send photo

#### What did you expect?
Photo uploads in the background, I see local echo

#### What happened instead?
UI is locked up until photo upload is done, which can be a long time on slow connections or with large files

### Your phone model

iPhone 11

### Operating system version

16.5.1

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Duplicates https://github.com/vector-im/element-x-ios/issues/1288
