### ISSUE TITLE
Ability to know when people sent a given emoji reaction

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1289]
* If you long-tap on a emoji reaction, you get told who sent which emoji.  (This is very undiscoverable, but that's a separate issue)
* Weirdly, it doesn't tell you when the emoji got sent though.  If you care enough about who specifically reacted to a message, though, you'd expect to also be told *when* they did so - just as EW/ED does, given the app obviously knows that info, and it's useful to know if you're trying to track when someone handshook on a message (thinking in terms of the all-to-often-forgotten 'people coordinator' persona)

**Comment by pixlwave** [comment]
Adding a note that this is already in progress.
