### ISSUE TITLE
Offline support.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1290]
### Steps to reproduce

When we disabled the cold cache, we lost offline support - the app won't even launch if you don't have internet connectivity, let alone let you browse locally cached conversations.

Opening this issue to track its reintroduction at the EX layer (for my benefit as much as anyone's).

#### What did you expect?

The app should cache messages and let me read them even when it can't connect to the internet.

#### What happened instead?

No internet == no worky

### Application version

279

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Fixed in https://github.com/matrix-org/matrix-rust-sdk/pull/2386
