### ISSUE TITLE
Animated send/receive receipts

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1292]
SRs currently cause the timeline to pop as they appear/disappear, as do RRs.

Instead, short of a redesign where they don't change the shape of the timeline, they should surely tween in and out to avoid a nasty pop.

**Comment by ara4n** [comment]
(n.b. i'm not proposing we copy the tetris animation from EW/ED here; just ease them in & out sizewise or similar)

**Comment by pixlwave** [comment]
Closing in favour of #1297
