### ISSUE TITLE
Keyboard goes over text input field

### ISSUE THREAD

**Issue by fuomag9** [vector-im/element-x-ios#1303]
### Steps to reproduce

1. Open any chat
2. Click on text input for message

#### What did you expect?

Keyboard should not go over text input field

#### What happened instead?

Keyboard went over text input field

https://github.com/vector-im/element-x-ios/assets/1580624/880314ac-2d6d-44be-a1d5-7cc2e90ad414

### Your phone model

iPhone 12

### Operating system version

iOS 17.0 beta 3

### Application version

1.1.8 (54)

### Homeserver

fuo.fi

### Will you send logs?

No

**Comment by pixlwave** [comment]
Thanks for reporting, unfortunatly we can't provide support for iOS 17 yet as these are in beta and often change a lot before release. Please let us know if this is still the issue on the GM/RCs :)

**Comment by fuomag9** [comment]
iOS 17 beta 3 (21A5277j) fixed the issue
