### ISSUE TITLE
DevX - Automatic/Cloud signing

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#131]
As a developer I want to be able to use automatic/cloud signing when making the release.

This is a requirement for Xcode Cloud, and makes our signing process more secure by removing the need to distribute a certificate and allowing signing privileges to be revoked via App Store Connect. [WWDC21-10204](https://developer.apple.com/videos/play/wwdc2021-10204/?time=453) has more information about how Cloud signing works. Ideally we should adopt this for Element iOS too.

**App Store Connect user options**
![Image](https://user-images.githubusercontent.com/6060466/177296762-dd33dfbb-abf2-4cd3-9aa7-9bf7f69caf82.png)

Signing for ElementX PR on GitHub can be achieved with additional [build flags](https://developer.apple.com/videos/play/wwdc2021-10204/?time=1141), however as it is AdHoc this wouldn't necessarily be a requirement to implement.

**Comment by stefanceriu** [comment]
Automatic signing is already enabled by default and for alpha builds we manually update the settings through a fastlane action here https://github.com/vector-im/element-x-ios/blob/develop/fastlane/Fastfile#L15

**Comment by stefanceriu** [comment]
Done as part of vector-im/element-x-ios/issues/81
