### ISSUE TITLE
Inability to distinguish between replies & threads (which could be a very easy fix)

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1333]
### Steps to reproduce

1. Chat in a room
2. See a reply from someone - which happens to be inside a thread, but you have no way of knowing that.
3. Answer it without sending a reply
4. Your answer gets sent to the main timeline, fragmenting the thread, and making no sense to users on thread-aware clients.
5. Feel frustrated that you broke the thread without realising it.

In other words: EX currently acts as a non-thread-aware client currently, showing threads as replies. Proper thread support is a while off.

However, if app showed you which replies were actually threads (and which were instead boring old replies), then the user would be able to much more effectively participate in threads - by knowing when they'd need to hit reply to participate in the thread, rather than talking normally in the room and fragmenting the thread for folks on thread-aware clients.

#### What did you expect?

EX should tell me somehow which replies are actually threads, versus plain replies in the main timeline.

#### What happened instead?

EX doesn't, so as a user you don't know if you need to send an explicit reply in order to keep your message in the right place in the thread, or whether you can just send a normal non-reply message.

### Application version

292

### Will you send logs?

No

**Comment by ara4n** [comment]
UI proposal: prefix the sender of the reply-preview message with 🧵 if the reply is part of a thread, until we have proper thread UI

**Comment by nadonomy** [comment]
> Your answer gets sent to the main timeline, fragmenting the thread, and making no sense to users on thread-aware clients.

Is this true? I've been using replies as a 'hack' on EX to reply in threads and at least a few weeks ago that was working great.

**Comment by ara4n** [comment]
If you hit reply to the message, it's fine. The problem is that you don't know whether to hit reply or not, because you don't know if it's a thread, hence this bug.

**Comment by nadonomy** [comment]
Aha gotcha (I'd misread point 3!).

**Comment by ara4n** [comment]
Another thought: i wonder if we easily do very simple poor man's threading like iMessage does - i.e. hide messages from the timeline which aren't part of the thread if the user views a message.  We could do this locally without having to use any server-side threading APIs as a first cut? (i.e. literally iterate over the timeline and hide the messages which aren't in the thread?)

**Comment by amshakal** [comment]
@stefanceriu @bmarty would this be easy to do? To 1) distinguish between threads and replies 2) to visually differentiate between the two without building the whole threads feature on EX.

**Comment by stefanceriu** [comment]
1) Sure, if the Rust SDK can provide us that piece of info on the timeline items
2) Easy to tweak the timeline views, yes
3) Not unless you want them to

**Comment by stefanceriu** [comment]
> This was fixed by #1686 in 1.2.9, wasn't it?

Yes, you're right. Fixed in https://github.com/vector-im/element-x-ios/pull/1686 which went out in `1.2.9`
