### ISSUE TITLE
Lots of echo problems on bad connectivity

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1335]
### Steps to reproduce

1. Be on slightly patchy GSM
2. Send messages
3. Observe edits getting lost in local echo
4. Unsent msgs which have to be retried one by one
5. No way to retry the lost edit
6. Broken date markers

See rageshake for video

#### What did you expect?

reliable time and echo, and ability to “resend all” (which is surely the common case), especially if there is no other way to resend edits!

### Application version

291

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Fixed in https://github.com/vector-im/element-x-ios/pull/1503
