### ISSUE TITLE
Can't permalink UISIs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1338]
### Steps to reproduce

1. Receive a UISI
2. Try to copy a permalink to it so I can reference it in a rageshake
3. Discover there's no "copy link to this msg" option on the UISI :(

#### What did you expect?

Ability to permalink undecryptable msgs.

### Application version

291

### Will you send logs?

No

**Comment by pixlwave** [comment]
@VolkerJunginger Are you happy to make this change? It is the opposite of what you said [here](https://github.com/vector-im/element-x-ios/issues/1185#issuecomment-1609879584).

**Comment by VolkerJunginger** [comment]
I am not a fan of exposing the regular message interaction to errors. I think the right way to do this is to introduce a "Report bug" action for UTDs that creates a bug with the link to that message.

**Comment by ara4n** [comment]
The main way of debugging UISIs is for a developer to copy-paste the URLs of the affected messages and collate with the logs. If there is no way to copy the URL short of "reporting a bug", that will be incredibly frustrating.

Given these errors exist primarily for developers to debug these bugs, I think we should prioritise what developers would need to fix UISIs (the last thing we need is to make them even harder to debug!) - and that means being able to copy their links.

Otherwise it's like saying "huh, this webpage is 500ing. therefore i'm not going to let you see its URL."
