### ISSUE TITLE
Placeholder avatars are 'wrong' colour.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1345]
### Steps to reproduce

Placeholder avatars (i.e. those for rooms without explicit avatars) don't match the colours used by Element Web (presumably we're hashing the wrong thing, or using the wrong hashing function).  Plus the actual shades of colours don't match Element Web.

#### What did you expect?

No cognitive dissonance due to inconsistent colours between platforms.

#### What happened instead?

Extreme cognitive dissonance, similar to seeing the word RED but painted green.

### Application version

292

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Implementation [here](https://github.com/vector-im/element-x-ios/blob/develop/DesignKit/Sources/Colors/ElementColors.swift#L57)

**Comment by ara4n** [comment]
also the colour of placeholder avatars in RRs doesn't always match that of the user in the room icon in a 1:1...
