### ISSUE TITLE
Hitting resend on failed msg doesn’t reset its send status

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1352]
### Steps to reproduce

1. Tried to send two msgs
2. For whatever reason (bad connectivity? server problems?) they failed.
3. Conversation moved on
4. I hit retry on the first one
5. It moved to the bottom of the timeline, but was still marked as failed-send (i guess it might have immediately failed?). i expected it to move back to sending/unsent state, not failed
6. I then did the second one; same result. Plus very annoying to have to individually resend them.

#### What did you expect?

resending should be shown as resending, not failed.

### Application version

292

### Will you send logs?

Yes

**Comment by Hywan** [comment]
Hi,

In [the `remote_echo_full_trip` unit test](https://github.com/matrix-org/matrix-rust-sdk/blob/4643bae28445e058080896a280083b32fd403146/crates/matrix-sdk-ui/src/timeline/tests/echo.rs#L32-L110), we ensure that the `EventSendState` evolves as expecting when an event is sent, has failed to be sent etc.

In [the `echo` integration test](https://github.com/matrix-org/matrix-rust-sdk/blob/4643bae28445e058080896a280083b32fd403146/crates/matrix-sdk-ui/tests/integration/timeline/echo.rs#L40-L134), we test a successful send of an event against a server.

In [the `retry_failed` integration test](https://github.com/matrix-org/matrix-rust-sdk/blob/4643bae28445e058080896a280083b32fd403146/crates/matrix-sdk-ui/tests/integration/timeline/echo.rs#L137-L189), we test a send that fails, then is retried, against a server.

I strongly believe that what you see is a very fast retry that ends up failing, like the first send.

To avoid this “nothing has happened??” feeling, the UI may run an animation when retrying, or displaying something to the user that deliberately “takes time”. Thoughts?
