### ISSUE TITLE
Room list missing Matrix HQ

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-ios#1359]
### Steps to reproduce

I re-joined Matrix HQ yesterday from web after being kicked out due to inactivity

1. Search for Matrix HQ or look for Matrix HQ in the room list
2. See no room in the results
3. Verify on web that I am in the room
4. Clear cache
5. Matrix HQ is there

#### What did you expect?
Search works and I can see all my rooms in the results. All my rooms are in the room list.

#### What happened instead?

https://github.com/vector-im/element-x-ios/assets/51663/06b5e87a-ee95-44bf-a162-ef37dc826947

All the other rooms are in the same order on web and EX, but Matrix HQ is missing from the room list on EX

### Your phone model

iPhone 11

### Operating system version

16.5.1

### Application version

1.2.1 (294)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
@kittykat Do you have any empty gaps in the room list when this is happening? It's probably related to https://github.com/vector-im/element-x-ios/issues/1157

**Comment by kittykat** [comment]
@stefanceriu No gaps in the room list - I've only ever seen gaps a couple of times

**Comment by stefanceriu** [comment]
Most likely fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2526
