### ISSUE TITLE
Unable to receive videos with odd width

### ISSUE THREAD

**Issue by dasJ** [vector-im/element-x-ios#1365]
### Steps to reproduce

1. Received a message with a video with a weird width, sent from regular iOS Element
2. I cannot view it

Video: https://github.com/vector-im/element-x-ios/assets/4971975/6228105f-0a94-4cd9-9c07-3de37a164f0a

Looks like `.content.info.w` is a float rather than an integer

#### What did you expect?

I would have expected to be able to see the video.

#### What happened instead?

![image](https://github.com/vector-im/element-x-ios/assets/4971975/cc27e432-d45a-449e-87b2-447dd799f075)

### Your phone model

iPad Pro 2019

### Operating system version

iPadOS 16.5.1 (c)

### Application version

1.1.8 (54)

### Homeserver

Synapse 1.87.0

### Will you send logs?

No

**Comment by dasJ** [comment]
Decrypted source:
```json
{
  "content": {
    "body": "Video",
    "file": {
      "hashes": {
        "sha256": "wd/yZ5yjmc/vw3Zpe9mtbaBz1MVsGqFHA7QJgx0z7cQ"
      },
      "iv": "XXX",
      "key": {
        "alg": "A256CTR",
        "ext": true,
        "k": "XXX",
        "key_ops": [
          "encrypt",
          "decrypt"
        ],
        "kty": "oct"
      },
      "url": "mxc://XXX",
      "v": "v2"
    },
    "info": {
      "duration": 68585,
      "h": 720,
      "mimetype": "video/mp4",
      "thumbnail_file": {
        "hashes": {
          "sha256": "nzRdjjE+NbWji/QqPv7zBRrQgGm7syPQA8sB+kHSbhM"
        },
        "iv": "XXX",
        "key": {
          "alg": "A256CTR",
          "ext": true,
          "k": "XXX",
          "key_ops": [
            "encrypt",
            "decrypt"
          ],
          "kty": "oct"
        },
        "url": "mxc://XXX",
        "v": "v2"
      },
      "thumbnail_info": {
        "h": 720,
        "mimetype": "image/jpeg",
        "size": 43592,
        "w": 405
      },
      "w": 405.8823547363282
    },
    "msgtype": "m.video"
  },
  "room_id": "!XXX",
  "type": "m.room.message"
}
```

**Comment by jplatte** [comment]
Yeah, this is a bug in whichever client sent this event. Widths and heights in image / video metadata are integers per spec.

**Comment by Velin92** [comment]
This is an El-iOS issue actually, El-X is going to be more restrictive in terms respecting Matrix Specs, the message should not be allowed to be sent like this.
