### ISSUE TITLE
Read receipts lack profile data

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1381]
### Steps to reproduce

1.  enable RRs
2. Send messages in a DM
3. observe that the RR is a placeholder, and doesn’t use the user’s displayname or avatar, but is the initial of their username.
4. This is *very* disconcerting if their username starts with a different letter to their displayname

#### What did you expect?

reliable profiles for RRs

#### What happened instead?

no reliable profiles

### Application version

300

### Will you send logs?

No

**Comment by Velin92** [comment]
Also this one has been fixed long time ago, now they correctly use the display name provided by the SDK
