### ISSUE TITLE
read receipt placeholder avatars are too big

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1382]
### Steps to reproduce

![image](https://github.com/vector-im/element-x-ios/assets/1294269/ca663e56-3645-42dc-bd31-c684e6fe00af)

#### What did you expect?

I would have expected there to be more margin around the edges of the letter, rather than cramming the letter to be as big as possible.

#### What happened instead?

Letter is crowded in the RR and looks ugly

### Application version

300

### Will you send logs?

No

**Comment by ara4n** [comment]
critically, it doesn’t match the larger placeholder avatar used for push and room names etc, which is weirdly disconcerting, as to the eye it looks like a different thing given it has a different shape

**Comment by Velin92** [comment]
The size for placeholder has been changed in its calculation some time ago so this issue has been solved.
