### ISSUE TITLE
Markdown and links are not friends

### ISSUE THREAD

**Issue by Hywan** [vector-im/element-x-ios#1390]
### Steps to reproduce

1. Write the following message:

    ```
    https://some.link1/_/lol and https://some.link2/_/bar
    ```

2. And send the message.

#### What did you expect?

I expect to see 2 links, and zero emphasize.

#### What happened instead?

I have 2 broken links, and emphasize between `/lol` up to `link2/`.

The Markdown parser considers `_` as an emphasize marker, instead of being part of the URL.

It happens also in Element Web. Not tested on Android.

### Operating system version

iOS

### Application version

nightly 1.2.1 (300)

### Will you send logs?

No

**Comment by stefanceriu** [comment]
It seems that the formatted body is `"formatted_body": "https://some.link1/<em>/lol and https://some.link2/</em>/bar"` which would point to this being a Rust side bug coming from here https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/timeline.rs#L50C8-L50C43

**Comment by Hywan** [comment]
Indeed, I ended up in Ruma, which uses `pulldown_cmark`. I'll raise the bug there.

**Comment by Hywan** [comment]
Issue raised here, https://github.com/raphlinus/pulldown-cmark/issues/695.

**Comment by Hywan** [comment]
Closing this issue, as it's not a bug, it's just how CommonMarkdown is defined.
