### ISSUE TITLE
State events should only be shown in the timeline if you have history visibility to see the timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1415]
### Steps to reproduce

1. Accept an invite to a room with non-shared (ie invited/joined) history visibility.
2. Scroll through pages of timeline showing historical membership events
3. Get confused that it looks like the room has no actual messages
4. Realise that they are hidden by histviz.
5. Wince that we are technically leaking metadata by exposing the historical membership

#### What did you expect?

Hide historical state events from users in the timeline which hist viz means they shouldn’t be able to see.

#### What happened instead?

the Mary Celeste

### Application version

303

### Will you send logs?

No

**Comment by ara4n** [comment]
this may be a bogus bug in the end; i think the room genuinely had no non-stateevents in it. but would be good to check.

**Comment by stefanceriu** [comment]
This is indeed the case but ElementX behaves in line with our other clients:

| iOS | Web | Element X |
|-----|-----|-----------|
|  ![IMG_79FD8C38FFBB-1](https://github.com/vector-im/element-x-ios/assets/637564/ac5ef459-9122-4781-9604-5f2ee903fe29)   |  ![Screenshot 2023-09-11 at 14 18 44](https://github.com/vector-im/element-x-ios/assets/637564/5eed47be-74b0-4c61-9da9-f3135fd5b775)   | ![Screenshot 2023-09-11 at 14 23 11](https://github.com/vector-im/element-x-ios/assets/637564/869a2771-4d5c-485c-8d91-9f92dcc18d9e) |


As such this is a bigger discussions that should be taken through the proper channels
