### ISSUE TITLE
Accepting invites is unreliable

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1420]
### Steps to reproduce

1. Viewed invites
2. Hit accept on the newest one
3. Failed to go to the room (it showed me a timeline-loading spinner on the new room, which never resolved after 10s or so)
4. Hit back button
5. Room is still in invite list
6. Hit accept again
7. “An error occurred”

#### What did you expect?

hitting accept should immediately join the room, and tgen disappear from the invite list.

#### What happened instead?

no local echo for accepting invite, plus accepted room didn’t show up

### Will you send logs?

Yes

**Comment by kittykat** [comment]
@ara4n I'm going to close this for now as we think we've fixed this issue. Please reopen if you're still experiencing it!
