### ISSUE TITLE
Pasting text from Apple Notes pastes as a webarchive file

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-x-ios#1436]
### Steps to reproduce

1. Write something in Apple Notes
2. Copy to clipboard
3. Paste into the composer. Hit send.
4. Observe that iOS presents a full screen modal to preview a webarchive file. Screenshot below.
6. Dismiss it. Observe that your text was placed in the composer all along.

![IMG_5514](https://github.com/vector-im/element-x-ios/assets/4626865/2180066c-ea6b-4730-8d61-9d063e9c12f0)

### Outcome

Plain text composer: To just strip formatting and paste as plaintext.
Rich text composer: Ideally to preserve formatting.

### Will you send logs?

No

**Comment by stefanceriu** [comment]
I believe this duplicates [1247](https://github.com/vector-im/element-x-ios/issues/1247). What app version are you on?

**Comment by nadonomy** [comment]
@stefanceriu Aha I'd launched an old build. D'oh. Confirmed as fixed in Nightly.

**Comment by stefanceriu** [comment]
Beautiful, thanks for checking 👍
