### ISSUE TITLE
Room previews show redacted messages

### ISSUE THREAD

**Issue by marwing** [vector-im/element-x-ios#1441]
### Steps to reproduce

1. Write message in room
2. Redact that message
3. Go back to the room list
4. Read content of redacted message in room preview (if it shows as `Message`, open a different room and go back to the room list again)

#### What did you expect?
Show an indicator a message was removed like in Element (“Message deleted”) or the previous message or something other than the thing that was supposed to be removed.

#### What happened instead?
Content of the redacted message is shown.

The message also reappears after a logout/login for unencrypted rooms and shows as “Message” for encrypted ones (probably only because of missing keys)

### Your phone model

iPhone 13 mini / iPad Pro

### Operating system version

iOS 17 Beta / iPadOS 16.5.1

### Application version

1.2.1 (62)

### Homeserver

Synapse 1.89.0

### Will you send logs?

No

**Comment by Hywan** [comment]
Yes please!

**Comment by kegsay** [comment]
Server-side fixes are in place, not yet deployed on matrix.org. Still requires client-side fixes to retroactively remove the redacted event from the room list preview.

**Comment by jplatte** [comment]
I'm pretty confident that this is mostly fixed with the server bugfix. The only remaining bug should be that when the server sends a non-redacted event *and its redaction* in the same response, we fail to honor the redaction. I don't think that remaining bug should have high priority (even though it's clearly a bug).

**Comment by ara4n** [comment]
an edge case where we leak redacted data just because the sync response included both redacted and unredacted data feels like it should still be high priority, imo. we should *always* honour redactions.

**Comment by manuroe** [comment]
I am considering the issue fixed and closing it. A fresh installation of EX using a server with the bug fix will not have the issue. 

The issue will not automatically fix itself after the server updates but this is not something we want to target. The last message will be redacted if the user opens the room or makes a clear cache. This is enough.
