### ISSUE TITLE
Invites show the avatar of the inviter, not the room avatar.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1451]
### Steps to reproduce

1. Receive an invite to a room
2. The invite is shown with the avatar of the person who’s invited you, but the name of the room you are invited to.
3. This is very confusing and dissonant

#### What did you expect?

Show the avatar of the room you’re invited to

#### What happened instead?

Shows the avatar of the user who invited you

### Application version

313

### Will you send logs?

No

**Comment by stefanceriu** [comment]
I believe this has been fixed in https://github.com/vector-im/element-x-ios/pull/1435/files#diff-960f82522d528c36824e409c4faaabc0614f1e812071588588f875e91ec9552fL123
