### ISSUE TITLE
Room previews leak redacted msgs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1452]
### Steps to reproduce

1. Have someone send a msg in a room and redact it
2. Look at the room preview and see the unredacted msg
3. Open room and see a redaction
4. Go back to room list and see unredacted msg still there

#### What did you expect?
redactions to be upheld

### Application version

323

### Will you send logs?

No

**Comment by pixlwave** [comment]
Duplicate of https://github.com/vector-im/element-x-ios/issues/1441
