### ISSUE TITLE
Tapping on room aliases doesn’t take you to that room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1465]
### Steps to reproduce

1. Send a message including a room alias - eg #matrix:matrix.org
2. Admire how the alias is shown as a nice blue link
3. Tap on it
4. Nothing happens.

I thought this used to work as a poorman’s way to join rooms or switch rooms?

#### What did you expect?

clicking on a link should not silently fail

### Application version

327

### Will you send logs?

No

**Comment by stefanceriu** [comment]
I don't think this ever worked. Permalink detection has been implemented a long time ago but we never got around to implementing their handling or deeplinking

**Comment by grahamperrin** [comment]
Duplicate?

* #966

**Comment by pixlwave** [comment]
Thanks for pointing that out 👍
