### ISSUE TITLE
The user button in HomeScreen can become wider than the window

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#147]
**To Reproduce**
Login to an account with a long username.

**Expected behavior**
The view clips the name when it is too long.

**Screenshots**
![Screenshot 2022-07-27 at 11 20 21 am](https://user-images.githubusercontent.com/6060466/181232802-ea563eef-a562-4133-8e62-b67a4566f1b7.png)

**Comment by stefanceriu** [comment]
Fixed by new designs no longer showing the user display name
