### ISSUE TITLE
12 Hour Time Format

### ISSUE THREAD

**Issue by ZachJTMurphy** [vector-im/element-x-ios#1476]
**Is your feature request related to a problem? Please describe.**
No my feature request is not related to a problem. Currently on Element (iOS) timestamps are only available in 24 hour time format. I would love to be able to use a 12 hour time format rather than a 24 hour time format. I live in Ontario, Canada and we rarely use a 24 hour clock unless you either work in the military or the government.

**Describe the solution you'd like**
If possible, I would like the ability to change timestamps from using the 24 hour clock format to the 12 hour clock format and vice-versa. It could either be made a toggleable feature in the app settings or configured a different way.

**Describe alternatives you've considered**
I have tried adding my Canadian phone number thinking that it does it by regional however, the home server I currently am using doesn't support adding a phone number to the account. I also thought maybe the timestamps are done in regards to the language set in the app, however when I check to see if there are any other English variants there is only 1 English Option which makes me think it is by default using the [UK] English setup because the [US] English in most apps doesn't use a 24 hour clock.

**Additional context**
I have attached a screenshot as a example of a 12 Hour Clock timestamp: 
![image](https://github.com/vector-im/element-x-ios/assets/141941897/a21f5351-7e6b-4120-a841-a4b5ffa20e25)

And here is a screenshot of a example of a 12 hour clock timestamp settings option. (Screenshot taken from Element Desktop) 
![image](https://github.com/vector-im/element-x-ios/assets/141941897/8ca58791-245f-4105-95d5-b28362385245)

**Comment by stefanceriu** [comment]
Throughout Element X we use locale aware date and time formatters based on your system's settings. You can either `General -> Date & Time -> 24-Hour time` or `General -> Language & Region -> Region`. The latter will show you formatting examples at the bottom and will take into account the former.

**Comment by stefanceriu** [comment]
Ah okay, that explains it. That is indeed **not** Element X, this is https://apps.apple.com/gb/app/element-x-secure-messenger/id1631335820.

The old client is currently in maintenance mode and we are only fixing security issues and high priority bugs.

Will close this ticket for now. Please feel free to reopen it if you do actually find any problems in Element X
