### ISSUE TITLE
Invite didn’t show room name

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1492]
### Steps to reproduce

1. Got invited to a private room
2. Invite came in as from “user 1, 2 and 3” with avatar of the inviter
3. Hit accept
4. Discovered the room had a specific name and an icon.

#### What did you expect?

Invite should reflect the name of the room and show it’s icon. (Even if that name and icon change post invite, ideally)

#### What happened instead?

I thought i was answeing a group DM rather than entering a specific named chat room.

It may be that the room was named after i received the invite, but it’s still weird.

### Application version

341

### Will you send logs?

No

**Comment by kittykat** [comment]
I can't reproduce this issue right now, it's likely to have been fixed. Please reopen if you're still seeing it
