### ISSUE TITLE
Element X sometime presenting as 'matrix-rust-sdk'

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/element-x-ios#1504]
### Steps to reproduce

From the perspective of Synapse, Element X sometimes presents itself correctly as 'Element X/...' and other times as the rust-sdk default 'matrix-rust-sdk'.

I'm not sure which contexts lead to which outcome but it is common enough that for a given user like me there will be examples of 'matrix-rust-sdk' daily.

#### What did you expect?
I expect Element X to correctly set the user agent so that we can determine the client type server side.

#### What happened instead?
The user agent is sometimes 'matrix-rust-sdk'

@jplatte suggests that this could be due to EX not overriding the user_agent properly when constructing an SDK client object.

### Your phone model

n/a

### Operating system version

n/a

### Application version

n/a

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by Velin92** [comment]
This is likely caused by the Notification Service Extension that now is capable of performing a sync but lacks a user agent name, luckily this is easily fixable.
