### ISSUE TITLE
Launch time has regressed substantially.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1509]
### Steps to reproduce

A clean launch (after having just killed the app, so no data to catch up on) used to take about 200ms around FOSDEM.

As of a few builds ago (possibly build 344?) it's now about 4s (see rageshake) - so a 20x regression.

#### What did you expect?

No perf regressions, otherwise we'll end up backsliding to the old app's performance.

#### What happened instead?

Perf regression.

### Application version

345

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
Launch time is now fast, as in to get to the room list. But sync time is still 7s or so on @ara4n's account

**Comment by ara4n** [comment]
Reasons for slow sync are:
 * [x] perf bug in SS proxy which meant having lots of members in an invited room slowed sync to 2s (fixed but not deployed?)
 * [ ] the push extension crypto loop doesn’t sync its pos with the main process’s crypto loop, meaning the loop can expire when the main process loads, which in turn expires the main loop too, slowing everything down as it resets.
 * [x] there was a bug where after reset the SS window would not reset its offsets and so pull in too much data
 * [x] there was a bug where the app would ask for large list windows, after unfiltering the room list.

**Comment by Hywan** [comment]
> the sdk looks to be blocking sync on pulling in invites on every launch. instead it should so it in the bg once the roomlist is rendered

First sync is for `all_rooms` only, next syncs have `visible_rooms` and `invites`.

**Comment by ara4n** [comment]
On build 360 this is a pretty constant 5-7s to sync on launch (on a recently used session). Have rageshaked.

**Comment by Hywan** [comment]
> …not sure that’s true when the sync loop expires; looks like we immediately try to pull them back in. plus i think we shouldn’t block visible_rooms on invites - we want visible_rooms to be visible as rapidly as possible!

Indeed!

**Comment by ara4n** [comment]
unfortunately sync time is still easily 5-10s.

**Comment by ara4n** [comment]
(n.b. this is very similar if not a dup of https://github.com/vector-im/element-x-ios-rageshakes/issues/790, not closing as dup though as this has more data on it)

**Comment by ara4n** [comment]
i think the main thing blocking this now is https://github.com/vector-im/element-x-ios/issues/1618

the approach being taken to get things snappy again is (something like) this:

* first sync:
 * all_rooms: 0..=19, limit=1
 * visible_rooms: none
 * invites: 0..=0
* second sync:
  * all_rooms: 0..=99, limit=1
  * visible_rooms: 0..=19, limit=20
  * invites: 0..=99 (?)
* ...then session expires...
* first sync after expiration:
  * all_rooms: 0..=19, limit=1
  * visible_rooms: ???
  * invites: 0..=0
* second sync - same as on launch.

**Comment by Hywan** [comment]
I believe we can close this issue now :-)? Closing it. If you disagree or if I've missed something, please feel free to re-open!

**Comment by ara4n** [comment]
reopening because without the 500-room cap, the roomlist still takes 2-3s to update after the initial sync completes - so while we're now driving SS efficiently (hurray!), EIX isn't updating the roomlist efficiently, so the end result is the app still feeling like it takes seconds to launch if you have lots of rooms.

@stefanceriu can we populate the roomlist gradually in the bg?

**Comment by stefanceriu** [comment]
> @stefanceriu can we populate the roomlist gradually in the bg?

We cannot, no. All diffs (e.g 4k cached rooms) need to processed before any other diffs can be applied on top. The only solution is for the SDK to paginate the room list and associated diffs.

**Comment by ara4n** [comment]
with the fancy SDK-powered incremental loading, i think we're back at snappy enough launch time again. I suspect there may still be room for improvement, but the original "5-7 seconds to sync" bug has gone :)
