### ISSUE TITLE
App blocked for ~30s on sending a message, during which hitting the send button sent duplicates.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#151]
**Describe the bug**

**To Reproduce**

1. login
2. send messages while e2ee is still warming up?
3. keep hitting send to try to make them send
4. eventually see many duplicates have sent

**Expected behavior**
msgs send UI should always local-echo send a message instantly, and not block.

https://github.com/matrix-org/element-ios-rageshakes/issues/19627

**Comment by stefanceriu** [comment]
Fixed with the introduction of local echoes.
