### ISSUE TITLE
After being offline for a month or so, EX shows and sends UTDs everywhere

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1524]
### Steps to reproduce

1. Use Nightly for a month or so rather than appstore EIX
2. Nightly breaks
3. Switch back to the appstore EIX
4. All messages appear UISI
5. Slowly, some but not all gradually decrypted over the next 30m or so
6. Meanwhile, other people (but not all) couldn’t decrypt my messages.

### Outcome

It looks like we should have queued sending msgs until we had cleared the todevice/devicelist backlog, so we knew we would be able to send to people successfully.

It also looks like we (or senders?) might not be handling fallback keys correctly, such that even after having caught up on megolm traffic, not all olm sessions could be decrypted?

### Application version

1.2.4

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
This feels like key gossipping gone wrong but that has been disabled in the meantime entirely so it's probably not an issue we should worry about. We're actively working on proper key backup so closing this.
