### ISSUE TITLE
theming broken on reaction summary on dark theme

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1526]
### Steps to reproduce

1. open reaction summary by long tapping on a reaction in dark theme
2. note emoji is light themed
3. also, the profiles should already be resolved, but aren’t (takes ages to take kick in)

![image](https://github.com/vector-im/element-x-ios/assets/1294269/f97736c7-cad4-425a-a3ee-99cbdb22001c)

#### What did you expect?
pretty reaction summary
#### What happened instead?
ugly reaction summary

### Application version

345

### Will you send logs?

No

**Comment by pixlwave** [comment]
This isn't a theming issue, its implemented as designed:
https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X?type=design&node-id=2128-105675&mode=design&t=0TjyEuB2Pml7SHJ4-4
