### ISSUE TITLE
All msgs sent from EX 1.2.3 are UTD in all other sessions & encrypted DMs

### ISSUE THREAD

**Issue by valynor** [vector-im/element-x-ios#1528]
### Steps to reproduce

I installed EX 1.2.3 on an iPad which also has regular Element on it. 
Verified the session with an iPhone 11 (also regular Element, iOS 16.6), all shields are green, cross-signing is ready2use. 
I can read all msgs in EX but everything I send from EX is UTD in the other sessions and in a DM with another [matrix.org] account, too. 

Logged out and created a new session from EX and verified it several times now - same issue persists.

### Outcome

All msgs sent from EX should be decrypted in the other sessions. 

### Your phone model

iPad Pro 2020 12.9"

### Operating system version

16.6

### Application version

1.2.3

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by valynor** [comment]
Updated to 1.2.5, created a new session. Msgs sent by Element X are now decryptable on other sessions.

**Comment by pixlwave** [comment]
Sounds like this is solved for you, I'm closing this as I'm unaware of any similar reports.
