### ISSUE TITLE
OIDC registration is missing logo and ToS link is 404

### ISSUE THREAD

**Issue by hughns** [vector-im/element-x-ios#1547]
Two issues:

1. No logo is being sent with the OIDC dynamic client registration
2. The terms of service URL given (`https://element.io/user-terms-of-service`) returns a 404 

This is how the logo looks on the consent screen:
<img width="578" alt="image" src="https://github.com/vector-im/element-x-ios/assets/6955675/8f7ef43e-9a30-47e9-acf1-47f5f6d21b78">

**Comment by pixlwave** [comment]
https://github.com/vector-im/sre-internal/issues/2755 for hosting the logo.
