### ISSUE TITLE
In-app notifs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1563]
### Steps to reproduce

1. When the app is running, you don’t get shown notifs
2. Therefore you miss notifs in rooms you are not currently reading

This is subtle, but really impacts perceived flakiness of the app. We fixed it quite late in the day in EI; would be good to ensure it doesn’t become a chronic issue here too. (It was a chronic bug on EI)

#### What did you expect?

Even if the app is running, show notifications (local notifs?) for push messages received - either derived from APNS or reconstituted from /sync

#### What happened instead?

No way at all to tell when people are talking to you in other rooms when you’re chatting in a given room.

### Application version

361

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Strange, this works just fine on my side 🤔 

![IMG_10E974C91FE6-1](https://github.com/vector-im/element-x-ios/assets/637564/2c2c4e78-b606-4788-9cef-0e5245898aff)

**Comment by ara4n** [comment]
working fine for me too. i am a crank.
