### ISSUE TITLE
When aborting back navigation from timeline to all chats the navigation state is not correct.

### ISSUE THREAD

**Issue by AlexanderBabel** [vector-im/element-x-ios#1568]
### Steps to reproduce
When going back by swiping and aborting that action the navigation stack is no longer representing the correct state. See video.

#### What did you expect?
Just staying in the screen while the back button is still visible.

#### What happened instead?
You cannot go back anymore.

https://github.com/vector-im/element-x-ios/assets/13570439/69b46806-9e80-4023-9919-daa3f5e74d59

### Your phone model

iPhone 14 Pro

### Operating system version

iOS 17

### Application version

1.2.6 (67)

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Thanks for reporting, unfortunatly we can't provide support for iOS 17 yet as these are in beta and often change a lot before release. Please let us know if this is still the issue on the GM/RCs
