### ISSUE TITLE
Let user register a new account in the Element X app

### ISSUE THREAD

**Issue by cloudaxes** [vector-im/element-x-ios#1599]
**Is your feature request related to a problem? Please describe.**
This feature request is related to the problem of what new users experience upon first interacting with Element X.  There is no way to register a new user account.  There is no way for a fresh user to continue using the app without using some third party to create an account (another app/website). 

**Describe the solution you'd like**
On opening the app without being logged on, either before or after choosing a server, the app should present a choice to either log onto an existing account or register and create a new account.  Alternatively, add a link on the login modal to register a new account.

**Describe alternatives you've considered**
I have considered creating accounts on other apps or through the web interface.  That would work, but doing all essential account-related activity though the app is table stakes for a serious client.

**Comment by ara4n** [comment]
this will be coming very shortly via the native OIDC auth support (but will require a server that supports native OIDC, also coming very shortly).

**Comment by cloudaxes** [comment]
Thank you!
