### ISSUE TITLE
Push notifs shouldn’t include reply fallbacks

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1620]
### Steps to reproduce

1. I just received a push from someone replying to my last msg
2. The push contents was mainly my own msg (with no > up front)
3. It also i correctly showed a ? with a backslash escape

#### What did you expect?

To see what the person’s msg

#### What happened instead?

I got shown a mangled version of my msg instead (their response didn’t fit in the notif bubble)

### Application version

372

### Will you send logs?

Yes

**Comment by Velin92** [comment]
We probably need a way for the SDK's NotificationItem to know if the Notification is a reply or not, right? @bnjbvr

**Comment by bnjbvr** [comment]
> We probably need a way for the SDK's NotificationItem to know if the Notification is a reply or not, right?

You have access to the full underlying event and event type, so you could look at the event type, and apply this kind of filtering in the app, right?

With respect to the original issue, I'm not too familiar with the event for a response, but I would suppose there's a field containing only the response, and not the original message including the fallback, and you could use that in the app when displaying this kind of notification?

**Comment by Velin92** [comment]
The reply appears as simple `MessageLike `type messages of type` .text(content: TextMessageContent)` but I can't find an easy way to understand where the message content contains a reply and when the message starts.

**Comment by pixlwave** [comment]
> The reply appears as simple MessageLike type messages of type .text(content: TextMessageContent) but I can't find an easy way to understand where the message content contains a reply and when the real reply message starts. (I don't see a dedicated body property for it)

This is done for us on the Rust side in the RoomList and Timeline fwiw.
