### ISSUE TITLE
Accepting invites from push notifications doesn't work

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1626]
### Steps to reproduce

1. Get an invite via push: "You have been invited to the X room"
2. Tap on the invite and get taken to the invites list in the app \o/
3. The new invite room is not shown in the list /o\
4. Wait 5 minutes
5. Nothing happens

#### What did you expect?

Accurate invite list

#### What happened instead?

Stale invite list

### Application version

373

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
We weren't able to reproduce it. The invites list updates with the new invite as soon as sync catches up no matter if the app is backgrounded or fully closed.
