### ISSUE TITLE
When the RTE is enabled, the plain `body` contains escaped characters.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#1629]
### Steps to reproduce

1. Enable the RTE in developer options
2. Send the message `Really?`
3. Inspect the event.

#### What did you expect?
`"body": "Really?"`

The plain body should be untouched and sent exactly as the user input (maybe other than trimming leading/trailing whitespaces).

#### What happened instead?
`"body": "Really\?"`

### Operating system version

16.6

### Application version

1.2.9 Nightly

### Will you send logs?

No

**Comment by jplatte** [comment]
So why would we put markdown in the plain-text `body`?

**Comment by langleyd** [comment]
This should be fixed now

**Comment by jonnyandrew** [comment]
Fixed by vector-im/element-x-ios#1703
