### ISSUE TITLE
Escaping characters appear on context menu for a given msg

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1632]
### Steps to reproduce

1. Send a message that begins with a /
2. Long-tap on the message
3. Observe that the preview on the context menu begins `\/`

![image](https://github.com/vector-im/element-x-ios/assets/1294269/499ca1c4-e159-4dfd-8c9c-bc1ef55ed2f3)

#### What did you expect?

No UNIX backslash escaping

#### What happened instead?

Unexpected UNIX backslash escaping creeping in

### Application version

373

### Will you send logs?

No

**Comment by pixlwave** [comment]
Also the same as #1629
