### ISSUE TITLE
Push Notifications Requirements

### ISSUE THREAD

**Issue by Hagbear** [vector-im/element-x-ios#1644]
### Steps to reproduce

Hi, i test Element X on my iphone and setup sliding-sync on my homeserver.
But i get no Push Notifications. Do I need to set up anything extra for this?
I find out that i can host my own notification service with sygnal but on the guide i found stands that i have to compile the client for my own to use it. But i use the Element X from the Store, should they not use the element.io push server like the "normal" app? I read also in the update notes something over push rules, but not find them in my app.
sorry for the stupid question, if i have missed anything.

#### What did you expect?
get push notifications
#### What happened instead?
no push notifications

### Your phone model

iPhone 11 Pro Max

### Operating system version

16.6

### Application version

1.2.5

### Homeserver

Synapse 1.91.1

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Hi, the documentation is right, you cannot use a custom push gateway with the stock Element X app. The push gateway needs the APNS keys that are private to Element and our Apple Developer Portal. You can still use the stock app with the stock push gateway (even if you have a custom sliding sync proxy) and the notifications should work just fine. We are not aware of any serious problems with push notification at the moment

P.S. next time please direct support questions to our public room #element-x-ios:matrix.org, you'll get a faster answer.
