### ISSUE TITLE
Room list is decorated with @ symbols on almost every room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1648]
### Steps to reproduce

1. set your notifs to “mentions and keywords” by default (a very sensible default)
2. almost every room in your roomlist gets decorated with an @ on the right hand side
3. cringe at drowning in a visual sea of @ symbols

#### What did you expect?

Rooms in the roomlist should only be decorated with notification configuration if they are *not* using the default setting and have explicitly overridden it for that room

#### What happened instead?

* All rooms apart from DMs were shown with an @, which also is deeply visually confusable with showing a “red notif” (ie mention notif) for a room.
* Death by drowning in useless visual noise.

I would assume is a blocker for recording glossy demo vids of EX, as it just looks awful.

### Application version

374

### Will you send logs?

No

**Comment by ara4n** [comment]
![image](https://github.com/vector-im/element-x-ios/assets/1294269/b2ab3819-1f6f-42a7-a38c-d32fc3367dfc)

for instance, the @'s here mean "rooms have default notification settings". they do *not* mean i have missed a mention in the room, so the second room is doubly confusing.

**Comment by nadonomy** [comment]
+1 to this being confusing.

@amshakal I remember in design review we debated on if it's a priority to be explaining the set notification state or not. I can see the value for muted rooms, but not sure about mentions/keywords.

**Comment by amshakal** [comment]
Yeah, I can see why that is confusing. Maybe a decoration for mentions and keywords is not necessary or primary enough information that it warrents a place in the room list. 

I am happy to circle back on this. We don't have mentions working properly in EX right now, so that being the bigger concern.

**Comment by langleyd** [comment]
@ara4n We now only show the decoration on the room list for rooms that you explicitly set. It was fixed on the rust side in https://github.com/matrix-org/matrix-rust-sdk/pull/2545 and you should see it reflected in the latest builds of each app.
