### ISSUE TITLE
ogg audio support

### ISSUE THREAD

**Issue by yspreen** [vector-im/element-x-ios#165]
there is no mention of ogg anywhere in this project yet.

I just want to start a conversation on deciding how those files will be handled. downloaded as ogg, converted, and cached locally?

**Comment by stefanceriu** [comment]
We're not quite there yet feature wise but chances are it's going to be implemented the same as in normal Element: conversion through https://github.com/vector-im/swift-ogg

**Comment by yspreen** [comment]
completed?
