### ISSUE TITLE
Rich text bubbles have massive paragraph breaks when authored with RTE.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1673]
### Steps to reproduce

1. Send a single-spaced multiline message in the RTE by hitting 'enter' at the end of every line
2. Observe that the rendered bubble is shown with double-spacing.

It's as if the `<p/>` tags created by the RTE are rendered with CSS with `margin-bottom: 1em` or something, whereas either they should be emitted as `<br/>` tags, or there should be no bottom margin or other padding on rendering `<p/>` tags.

https://github.com/vector-im/element-x-ios/assets/1294269/80fd81d1-47d7-427d-9399-d51fb11f3a7a

#### What did you expect?

Sent bubble should visually match the authored preview in the RTE precisely.

#### What happened instead?

All the linefeeds got doublespaced.

### Application version

380

### Will you send logs?

No

**Comment by ara4n** [comment]
https://github.com/matrix-org/matrix-rich-text-editor/issues/832 is the root cause here:

> the problem is that the default and correct handling of paragraph tags is to put a linebreak of padding after them, like in a book
> i don’t think we’ve ever specced or suggested that matrix clients should override that padding to 0px
> so i would argue that we are doing the wrong semantic thing in RTE if every return is seen as a paragraph break rather than a `<br/>` line break
> given the intention of the author will be a linebreak. (and they’ll prolly write two linebreaks if they intend a paragraph break).

**Comment by ara4n** [comment]
https://github.com/matrix-org/matrix-rich-text-editor/issues/832

**Comment by jonnyandrew** [comment]
Fixed in RTE v2.15.0 (https://github.com/matrix-org/matrix-rich-text-editor/pull/834).
