### ISSUE TITLE
Low hanging improvements to the message send, edit & reaction animations

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-x-ios#1707]
I understand we're waiting on iOS17/some SwiftUI updates to properly update the timeline animations. However, from recording and slow-mo debugging, I think we can materially improve what we have today just by tweaking tween values, easing and overall choreography with todays implementation.

I'd like us to timebox a working session to see how much we can improve this, ahead of recording launch materials.

**Comment by pixlwave** [comment]
Closed by https://github.com/vector-im/element-x-ios/pull/1751
