### ISSUE TITLE
Low hanging improvements to make the rich text editor actions more visually balanced

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-x-ios#1708]
The active states on formatting options are quite bold. We should find some low hanging tweaks (e.g. reducing icon button sizing, the colour contrast) to see if we can improve it a bit ahead of recording launch materials.

**Comment by alfogrillo** [comment]
The RTE toolbar and the composer in general have been updated [here](https://github.com/vector-im/element-x-ios/pull/1719) as discussed with @callumu

**Comment by nadonomy** [comment]
@alfogrillo @callumu  Great! Looks awesome.
