### ISSUE TITLE
Sending a message after accepting an invite sends a UTD.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1738]
### Steps to reproduce

1. Get invited into an E2EE room
2. Send a message
3. Chances are that others in the room won't be able to decrypt you.

#### What did you expect?

Reliable encryption

#### What happened instead?

UISI hell

### Application version

386

### Will you send logs?

Yes

**Comment by bnjbvr** [comment]
I think that should be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2570, so that'll require a SDK upgrade from the clients to benefit from this fix.

**Comment by ara4n** [comment]
I got bitten by this on Saturday's build (i.e. post-ignition)

**Comment by bnjbvr** [comment]
Fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/2615/ (until the next issue!). Thanks for the rageshakes, they're quite useful.
