### ISSUE TITLE
Animated transition from Room List to Room View doesn't always fire

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1750]
### Steps to reproduce

The first time you view a room in a session, the slide animation may not fire.

@stefanceriu says this is an iOS16 bug likely fixed in iOS17, but just tracking it here.

Video available on request

#### What did you expect?

pretty animation

#### What happened instead?

no animation

### Application version

389

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Dupes https://github.com/vector-im/element-x-ios/issues/913
