### ISSUE TITLE
Flash of incorrect room items when filtering

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-x-ios#1772]
### Steps to reproduce

1. Focus the "search" input to filter the room list
2. Type the letter "Z"

#### What did you expect?

For the items that match `Z` to appear

#### What happened instead?

The unfiltered room list appears for a split seconds, then gets replaced by the filtered down version
Can reproduce both on iOS and on Desktop

### Will you send logs?

No

**Comment by stefanceriu** [comment]
We hide the room list when the search field is focused and the seach query is empty. Problem is that search results come back async and we show the full room until they come back. Will be fixed with help from https://github.com/matrix-org/matrix-rust-sdk/pull/2594
