### ISSUE TITLE
User details page doesn't update room info

### ISSUE THREAD

**Issue by callumu** [vector-im/element-x-ios#1778]
### Steps to reproduce

Change room avatar photo, room name and topic

### Outcome

I'd expect everything to be updated in the room details page. On iOS this isn't the case:

![IMG_8405](https://github.com/vector-im/element-x-ios/assets/110109933/a1ebef94-44e0-4162-97b1-c3f880e15d29)
![IMG_8404](https://github.com/vector-im/element-x-ios/assets/110109933/144afe0a-d32b-4e6d-8f78-737247737557)

I assume this should update like on Android?

### Your phone model

iPhone 13 mini

### Will you send logs?

Yes

**Comment by VolkerJunginger** [comment]
We need to fix this later with an update to sync.
