### ISSUE TITLE
Timeline missing large number of messages

### ISSUE THREAD

**Issue by marwing** [vector-im/element-x-ios#1787]
### Steps to reproduce

I can't reliably reproduce this (yet). I did the following when I last noticed the issue:
1. Open EX after some inactivity on my part
2. Open a public room (Element X iOS)
3. Scroll up to the new messages separator (The messages were already read so this should not have been there, but that's another issue)
4. Notice a chunk of messages missing

This stuck around after leaving and reentering the room.
It disappeared after force closing the app.

I think I noticed this twice before since 1.2.3 (which re-enabled the cache) but couldn't reproduce so thought nothing of it. This is the first time I noticed it in a fully read room, with known instead of new messages missing, and also the first time with a time span this large missing. Considering I had to scroll up a bit every time, this is probably older and is just easy to miss or super rare (or both).

#### What did you expect?
The timeline to be shown correctly without gaps (i.e., all messages in chronological or topological order)

#### What happened instead?
The timeline had a major chunk missing without indication (not event the date separator). The messages below the new message separator are from today (Sep. 23), the message above from Sep. 18.

| This issue | After force close (with intact timeline) |
|-|-|
|![IMG_3454](https://github.com/vector-im/element-x-ios/assets/29716248/d8276c02-b0bc-46f5-876e-d078e42606cd)|![IMG_3455](https://github.com/vector-im/element-x-ios/assets/29716248/97fb326c-e0b2-441e-ad52-0f6ac5f5731f)|

### Your phone model

iPhone 13 mini

### Operating system version

iOS 17.0.1

### Application version

TF 1.3.0 (72)

### Homeserver

Synapse 1.92.3 / Proxy 0.99.10

### Will you send logs?

No

**Comment by ara4n** [comment]
@marwing did you submit debug logs for these? (if so, what's your matrix ID, so we can correlate them? if not, please can you submit debug logs referencing this bug asap before the logs rotate)

**Comment by manuroe** [comment]
It might be related to https://github.com/vector-im/element-x-android/issues/1076

**Comment by ara4n** [comment]
received - thanks.

**Comment by simonmichael** [comment]
But today I see it in Element Desktop Mac, so possibly it's not EX specific ?

ED:

<img width="902" alt="image" src="https://github.com/vector-im/element-x-ios/assets/10144/94a424df-d3b5-4f3a-8a8e-41f628affce4">

EX:

<img width="1283" alt="image" src="https://github.com/vector-im/element-x-ios/assets/10144/6acf9f91-254f-47b3-a600-98c2fcb1df9b">

**Comment by simonmichael** [comment]
Restarting or clearing cache in settings does not fix the issue in ED. E IOS on phone is showing an even larger hole in this chat log, even after restart.

**Comment by simonmichael** [comment]
Apologies, today's problem in Element was a red herring (I forgot that threads UI is mandatory in Element).
