### ISSUE TITLE
RTE: Selecting and deleting words before quotes causes corruption

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1803]
### Steps to reproduce

1. Type `foo "bar"`
2. Double-tap on `foo` to select it
3. Hit delete. Note that it also deletes the following space, despite it not having been selected.
4. Tap off the end of string to hit the equivalent of the end key
5. Type something
6. Observe the string corrupts to be `"ba "...`

https://github.com/vector-im/element-x-ios/assets/1294269/a10b6c00-d204-4d21-94cc-fbf28e46cf94

#### What did you expect?

RTE doesn't corrupt

#### What happened instead?

RTE starts eating characters, turning smart quotes into non-smart quotes, and all sorts.

### Application version

394

### Will you send logs?

No

**Comment by ara4n** [comment]
Here's another one (harder to see what's happening given that it's a screencap rather than an analogue gap vid):


https://github.com/vector-im/element-x-ios/assets/1294269/79a5b120-2b53-45c8-8939-aa3618e38e45

**Comment by kenrachynski** [comment]
Related: 

https://github.com/vector-im/element-x-ios/assets/867597/a21e5874-a91d-406b-aead-e5b83d388206
