### ISSUE TITLE
No motion between room list & room on first tap after launching app

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-x-ios#1809]
### Steps to reproduce

![Element X - bug - room loading glitch](https://github.com/vector-im/element-x-ios/assets/4626865/1918fa6f-08ba-487f-ab2f-ded91a65378d)

1. Launch the app cold.
2. Tap on a room. Observe it immediately switches to the room without motion between the room list / room states.
3. Hit back.
4. Tap on the same room again. Observe it now has a nice transition.

### Outcome

...

### Application version

1.3.1 (73)

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Duplicates https://github.com/vector-im/element-x-ios/issues/913
