### ISSUE TITLE
Text wrapping in filename bubbles wraps too eagerly 

### ISSUE THREAD

**Issue by nadonomy** [vector-im/element-x-ios#1810]
### Steps to reproduce

![Element X - filenames text wrapping](https://github.com/vector-im/element-x-ios/assets/4626865/e7a891e2-653b-45ce-86d1-f0a7c4cb7717)

Text wrapping in general seems really unoptimised. Here's a screenshot of a filename wrapping unexpectedly. The 'Voice Messages' bubble also has a break between the 2 words. Seems like there's fundamental root/layout issues to address.  

### Outcome

...

### Application version

1.3.1 (73)

### Will you send logs?

No

**Comment by nadonomy** [comment]
@Velin92 just to align on priority - this is visible to _all_ users in a variety of messages. Shouldn't the occurance be `O-Frequent`?

**Comment by Velin92** [comment]
I would say this happens also depending on the device size (which can determine the size of the bubble), and the length of the text name/filename so I would say is less than frequent, and for mostly files which are not sent as frequently as messages...  but of course this is just an estimate, I can check with someone else from the platform team if they agree on the estimate or if we should bring to `O-Frequent`

**Comment by nadonomy** [comment]
> I would say this happens also depending on the device size (which can determine the size of the bubble), and the length of the text name/filename

@Velin92 interesting. Admittedly I'm less familiar with how SwiftUI handles layout (compared to, e.g. flexbox), but it feels like in these kind of situations, the 'Voice message' bubble should expand rather than wrap, up to the width of the bubbles below it:

<img width="204" alt="Screenshot 2023-09-28 at 10 11 22" src="https://github.com/vector-im/element-x-ios/assets/4626865/cdd5db56-235c-4889-a929-8d7aae28d8b2">

Which seems like a layout rather than device width issue? But not sure. Perhaps when we get to this we should just review all of the logic (design & engineering) with some test cases and come up with some guidelines in the spirit of responsive design, with the realities of how SwiftUI works.

**Comment by Velin92** [comment]
> > I would say this happens also depending on the device size (which can determine the size of the bubble), and the length of the text name/filename
> 
> @Velin92 interesting. Admittedly I'm less familiar with how SwiftUI handles layout (compared to, e.g. flexbox), but it feels like in these kind of situations, the 'Voice message' bubble should expand rather than wrap, up to the width of the bubbles below it:
> 
> <img alt="Screenshot 2023-09-28 at 10 11 22" width="204" src="https://user-images.githubusercontent.com/4626865/271233448-cdd5db56-235c-4889-a929-8d7aae28d8b2.png">
> Which seems like a layout rather than device width issue? But not sure. Perhaps when we get to this we should just review all of the logic (design & engineering) with some test cases and come up with some guidelines in the spirit of responsive design, with the realities of how SwiftUI works.

Yeah we probably should double check file based messages, because they were initially made to be of a defined max size that is different from the message one.
So it's more like an issue the way they are made, than SwiftUI itself, the real issue is that these should behave and have the same behaviour as the text based ones, but with the additional image on the left side.
