### ISSUE TITLE
Leaving room keeps it in room list, can't forget

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-x-ios#1812]
1. long press in room list
2. select leave
3. nothing obvious happens
4. open the room to see own leave event
5. long press room in room list again
6. can "leave" again

**Comment by gunnarbeutner** [comment]
Also, it seems like rooms in this particular state count towards the “unread” counter. I have two rooms that are broken in this way and my unread app badge is “2”.

**Comment by ara4n** [comment]
dup #1817
