### ISSUE TITLE
Notifications of rooms with avatar placeholders mirror the letter

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-x-ios#1814]
- be in room without room avatar and 3+ members
- receive system notification 
![image](https://github.com/vector-im/element-x-ios/assets/2803622/ad854160-8b2a-4b3e-a2b9-b3b700273cfd)

Related? https://github.com/vector-im/element-x-ios/issues/1639

**Comment by pixlwave** [comment]
Thanks for the report, this one has already been fixed by https://github.com/vector-im/element-x-ios/pull/1785 and will be available in the next release (Soon™️)

**Comment by HarHarLinks** [comment]
perfect, thanks, my search didn't yield the existing issue :)
