### ISSUE TITLE
Leaving room doesn’t remove it from roomlist

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1817]
### Steps to reproduce

1. Long tap on room in roomlist
2. Hit “leave”
3. Get a nice pretty “room left!” modal
4. Room is still shown in room list

#### What did you expect?

leave room

#### What happened instead?

hotel california

### Application version

394

### Will you send logs?

Yes

**Comment by manuroe** [comment]
Fixed with https://github.com/matrix-org/matrix-rust-sdk/pull/2866
