### ISSUE TITLE
Invite green-dot is stuck on

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1820]
### Steps to reproduce

1. Someone invites you
2. You observe a green dot on the invites section of the room list
3. View the invite list to see who it is
4. Decide not to answer their invite
5. Time passes
6. Launch the app (or another instance of the app)
7. Observe a green dot on the invites section of the room list
8. Discover that it's the same invite as before
9. Feel frustrated that it's re-notifying you about the same invite you've chosen to ignore
10. GOTO 4

#### What did you expect?

Only see a green dot on invites when the invite list changes.

#### What happened instead?

Green dot appears on every launch.

### Application version

397

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
I had a look at this and cannot reproduce it. Viewed invites are correctly stored app side and used between launches as per https://github.com/vector-im/element-meta/issues/1158. 

The only way they would show up again as new is on a new login or a different device.
