### ISSUE TITLE
EXI still intercepts EC links on macOS, and DoSes the OS

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1824]
### Steps to reproduce

1. Install EX Nightly and EX TF on macOS
2. Click on an Element Call link in Apple Calendar or similar
3. Watch as both apps go berserk fighting over the URL, flickering back and forth between them at 120fps, chewing 10 cores of CPU, and locking you out of using the machine as mouse & keyboard focus is constantly stolen by the window manager.
4. The only way to get out is to stab frantically at Cmd-Q and hope to break the loop by quitting both apps adjacently.

This is 100% reproducable.

#### What did you expect?

Not to get DoSed out of my laptop

#### What happened instead?

Two EXes went mad and colluded to steal my CPU and input devices

### Your phone model

macOS 13.6 (22G120)

### Will you send logs?

No

**Comment by ara4n** [comment]
looks like the fix to https://github.com/vector-im/element-x-ios/issues/1794 didn't work

**Comment by stefanceriu** [comment]
I tried getting the system to stop tightlooping between multiple apps that support the same universal links but I didn't get anyhwere. The new plan is this:

1) Deploy [this](https://github.com/vector-im/element-call/pull/1658) to call.element.io
2) Have the universal link open one app as normal
3) If the app can't handle the url (i.e. it's running on the mac) then add that extra `no_universal_links` query param and send it back to the system
4) The system should now ignore the universal link and just open the browswer
