### ISSUE TITLE
Unsupported event error when giphy image is posted to room

### ISSUE THREAD

**Issue by ajkessel** [vector-im/element-x-ios#1828]
### Steps to reproduce

Using the [giphy maubot plugin](https://github.com/TomCasavant/GiphyMaubot), when it uploads an animated GIF  to the room, Element-X reports:
```
Unsupported event: m.room.message
invalid type: string "288",
expected u64 at line 1 column 36
```
Works fine on Element.

Example decrypted event source:
```
{
  "room_id": "(redacted)",
  "type": "m.room.message",
  "content": {
    "msgtype": "m.image",
    "body": "file.gif",
    "url": "mxc://(path here)",
    "info": {
      "mimetype": "image/gif",
      "h": "288",
      "w": "480"
    }
  }
}
```

#### What did you expect?

Image to be visible

#### What happened instead?

Error code

### Your phone model

iPhone 13 Pro

### Operating system version

iOS 17.0.2

### Application version

1.3.1 (74)

### Homeserver

Synapse

### Will you send logs?

No

**Comment by pixlwave** [comment]
The bot is creating a non-compliant event. The spec defines the `w` and `h` should be integers and not strings.

@jplatte I assume we stick to the spec here?

**Comment by ajkessel** [comment]
I've added this as an issue to the bot at https://github.com/TomCasavant/GiphyMaubot/issues/11

**Comment by jplatte** [comment]
Yeah, Ruma doesn't seem to have any workarounds for stringified integers in this particular place 😄

**Comment by ajkessel** [comment]
The GiphyMaubot plugin has been fixed so this error no longer occurs, but I wonder if Element-X could/should be move forgiving about slight non-compliance like this. Fine with me if you want to close, though.

**Comment by jplatte** [comment]
I like that we're helping other software find these bugs, so I'd be inclined to keep things as-is.

**Comment by stefanceriu** [comment]
> so I'd be inclined to keep things as-is.

I agree, we're intentionally being very strict on what we're accepting and sending.
