### ISSUE TITLE
Long replies overlay the replied message.

### ISSUE THREAD

**Issue by neilisfragile** [vector-im/element-x-ios#1832]
### Steps to reproduce

1. Where are you starting? What can you see?

I'm on the timeline for a room, I click reply, I write a long reply. While still composing, if I scroll up and down the text of my reply is overlaid on the text of the original message

#### What did you expect?
I would have expected the original message to not be overlaid with text on text rendering both my reply and the original message illegible. 

#### What happened instead?
I could not read my reply or the original message (this is especially problematic since I am still composing my reply).

I could send a screen shot, but thus far all examples have been in private rooms so I don't want to attach to the issue. 

### Your phone model

iPhone 11

### Operating system version

16.6.1

### Application version

1.3.2(398)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by pixlwave** [comment]
Oh yeah! recording:

https://github.com/vector-im/element-x-ios/assets/6060466/f08a2a8c-2d91-4751-ac02-a5e802eb2f77
