### ISSUE TITLE
Timeline suddenly reset on sending a reply, and the sent message was lost

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1840]
### Steps to reproduce

1. was just writing msgs normally
2. the first sent fine
3. the next was a reply, which seemed to trigger a timeline reset
4. the reply then vanished entirely; showed the previous msg for a bit by itself, and then after going out and in the timeline reformed with the sent msg gone.

![IMG_3131](https://github.com/vector-im/element-x-ios/assets/1294269/228e2ba9-9eb1-4dea-bcd6-3a374287cc57)

#### What did you expect?

no lost sent msgs; no spurious timeline resets

### Application version

396

### Will you send logs?

Yes

**Comment by ara4n** [comment]
had it again (although msg got sent this time); rageshaking

**Comment by jplatte** [comment]
This should be fixed. Though it seems like people on EXA are still experiencing [gaps](https://github.com/vector-im/element-x-android/issues/1076#issuecomment-1759933176), those no longer seem to be for entire chunks of paginated messages.

**Comment by manuroe** [comment]
Closing it right now on iOS following what @jplatte said 1 month ago. I tried to reproduce with no success. Please reopen with a new rageshake if the issue appeared again.
