### ISSUE TITLE
Indefinite spinning if sliding sync server is not available but configured

### ISSUE THREAD

**Issue by kewisch** [vector-im/element-x-ios#1866]
### Steps to reproduce

1. Set up synapse and a sliding sync server. Both available on :8448, synapse on :443 as well.
2. Forget to expose the sliding sync server on :443
3. Configure the .well-known to point to both servers (in my case: two subdomains, same apache) 
4. Log in to server in Element X

#### What did you expect?
* Element X figures out the host is not reachable and errors out

#### What happened instead?
* I am able to get all the way to "Setting up your account, this may take a while"
* Element X keeps on spinning, the phone gets fairly warm (though that might not be related)
* Sliding sync server obviously never gets contacted
* Even if I fully quit the app and restart it, it goes back to the spinning immediately

### Your phone model

iPhone X

### Application version

1.3.1 (74)

### Homeserver

Synapse 1.93.0 / Sliding Sync 0.99.10

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Related to https://github.com/vector-im/element-x-ios/issues/1701
