### ISSUE TITLE
DM is showing an old avatar after the other user removed their avatar.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#1879]
### Steps to reproduce

Not sure how to reproduce this, but my DM with @kittykat is showing an avatar in the room list and the room header that isn't shown in the DM details or on Element Web. Kat says she removed the avatar a few weeks ago.

Linking a rageshake to this issue.

#### What did you expect?
The room list to show the placeholder avatar.

#### What happened instead?

![image](https://github.com/vector-im/element-x-ios/assets/6060466/b3b084f4-1620-4d08-811c-e50c6b2e42be)

### Your phone model

iPhone 12

### Operating system version

17.0.3

### Application version

Nightly 1.3.2 (405)

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by bnjbvr** [comment]
This might be fixed by the patch [I made for the Rust SDK](https://github.com/matrix-org/matrix-rust-sdk/pull/2867) about correctly unsetting the avatar; can someone double-check that please?
