### ISSUE TITLE
Replies sent by you to threads aren't shown as threaded

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1883]
### Steps to reproduce

1. Reply to a message in a thread.
2. Get a warm fuzzy feeling that the app told you that the message you're replying to was in a thread, and that you haven't broken the thread. It even showed "Reply in thread" in the context menu!
3. Notice that *your* message isn't shown as being part of a thread, so if you then later forget and try to respond to it without a reply, you break the thread.

#### What did you expect?

Messages in threads should be shown as threaded whether they were sent by you or someone else.

#### What happened instead?

If you reply in a thread, your reply is not shown as being a threaded msg, just a normal reply.

### Application version

407

### Will you send logs?

No

**Comment by jplatte** [comment]
Rust-side bugfix is available (in a PR), just needs another SDK bump after the fix is merged.

**Comment by manuroe** [comment]
> Rust-side bugfix is available (edit: now merged), just needs another SDK bump.

@stefanceriu can we close this issue?

**Comment by stefanceriu** [comment]
Yes, it's working properly now 👏
