### ISSUE TITLE
Chat History

### ISSUE THREAD

**Issue by KnechtNoobrecht** [vector-im/element-x-ios#1888]
**Is your feature request related to a problem? Please describe.**
In every webapp-session you can view the message history in your chats.
This is a pretty essential feature.

**Describe the solution you'd like**
I'd like to see the message history of my chats in the Element X iOS App.

**Comment by pixlwave** [comment]
Thanks for the issue @KnechtNoobrecht. Work on key backup is already underway and tracked across multiple repos, so I'm going to close this, but don't worry, it *is* coming :)
