### ISSUE TITLE
Cannot post to non-E2EE rooms

### ISSUE THREAD

**Issue by vmstan** [vector-im/element-x-ios#1897]
### Steps to reproduce

1. Try to post to non-E2EE rooms
2. Fails to post

### Outcome

Fails for non-E2EE
https://github.com/vector-im/element-x-ios/assets/3002053/07b5b459-5c4a-47ca-9770-7d1039269720

Posts fine in any E2EE room
https://github.com/vector-im/element-x-ios/assets/3002053/e372d3d8-8bcf-436d-bf5a-93a0e2bef115

### Your phone model

iPhone 15 Pro Max

### Operating system version

iOS 17.0.3

### Application version

Version 1.3.3 from TestFlight and 1.3.1 from App Store

### Homeserver

Synapse 1.94.0, Sliding Sync 0.99.11 (matrix.vmst.io)

### Will you send logs?

Yes

**Comment by vmstan** [comment]
I have submitted logs via the app and marked them as tied to this case.

Other troubleshooting:
- Element Desktop tied to sliding sync does not have issues
- Nginx Ingress Controller logs do not indicate any traffic requests during posting attempts when failing
- Tried public and test versions
- Tried rolling back Sliding Sync server to 0.99.10
- Upgraded Synapse from rc to final of 1.94.0
- Restarted iPhone
- Logged out of Element X, deleted and reinstalled multiple times
- Used Element from same device, no posting issues
- Used wifi and cellular to reproduce

**Comment by vmstan** [comment]
I've also previously submitted logs in the app and mentioned in the Matrix room, but not filed tickets, for a similar issue where opening the app after sitting idle would error out on the first post or reaction emoji attempt, but then work fine after that. This feels like an escalated version of that, but I never connected if the E2EE piece was related at the time.

**Comment by kittykat** [comment]
Lets see if we can figure out the cause, and then check in again about the fix

**Comment by jplatte** [comment]
@vmstan Can you still reproduce this? If yes, could you go to advanced settings, enable the "View Source" feature there and then fetch the source / debug info for one of these failed local messages?

**Comment by vmstan** [comment]
I shut down my homeserver and am not having the issue in matrix.org so this can be closed.
