### ISSUE TITLE
Markdown lists at the beginning of messages are rendered incorrectly

### ISSUE THREAD

**Issue by marwing** [vector-im/element-x-ios#1915]
### Steps to reproduce

1. Send a message containing only a markdown list

#### What did you expect?

All list items to be formatted the same (as is happening in Element iOS and Web). Similar to this (but without the A):
![IMG_3507](https://github.com/vector-im/element-x-ios/assets/29716248/c8a0814d-03e4-4329-a7de-3d4f7a45f772)

#### What happened instead?

The first list item was rendered looking like an indented paragraph instead of a list item.
![IMG_3504](https://github.com/vector-im/element-x-ios/assets/29716248/70bee7f3-f48d-4d58-9c2f-7b7539d4effd)
This also happens with short lists with very short list items:
![IMG_3506](https://github.com/vector-im/element-x-ios/assets/29716248/f2b12c2f-d05d-4309-a55f-9713b50bc6ed)

### Your phone model

iPhone 13 mini / iPad Pro

### Operating system version

iOS/iPadOS 17.0.3

### Application version

1.3.3 (76)

### Homeserver

Synapse 1.94.0

### Will you send logs?

No

**Comment by langleyd** [comment]
Fixes with https://github.com/vector-im/element-x-ios/pull/2152
