### ISSUE TITLE
Chat message timed destruction function

### ISSUE THREAD

**Issue by cz9** [vector-im/element-x-ios#194]
**I suggest adding the chat message timed destruction feature as soon as possible. This feature is great for protecting the privacy of users and keeping the space occupied by chat messages small.**

**Comment by pixlwave** [comment]
Thanks for opening this @cz9. For more general requests like this I would suggest starting a discussion on the [element-meta](https://github.com/vector-im/element-meta/discussions) repo which will help us measure people's interest :)

I'm going to close this issue on ElementX.
