### ISSUE TITLE
Enabling chat backup fails badly on large accounts and corrupts your online backup.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#1976]
### Steps to reproduce

1. Enable chat backup in labs
2. Enter your recovery passphrase in settings and enable the backup.

Subsequent failure modes include:
 * Repeated prompts to 'confirm your recovery key' in room list; re-entering the key doesn't seem to help.
 * Stuck red badge on the settings icon (which doesn't map through to a badge within)
 * Repeated prompts to 'confirm recovery key' in settings (despite having already provided it)
 * Past history is shown as UTD (although the blue 'past history undecryptable' prompt has gone away)

I ended up entering the recovery key (passphrase) about 4 times, and left the app foregrounded for roughly an hour to see if it needed time to download the backup (which didn't help).

My megolm backup is currently 328MB.

#### What did you expect?

Chat backup should:
 * Work for powerusers, otherwise we undo all the good work from Ignition in terms of providing a great experience for powerusers to help them advocate for the app.
 * Explain in the UI that backup is for accessing history, not just storing keys
 * Give feedback on whether the backup restoration succeeded or not
 * Show some kind of progress on backup restoration so you know if you need to keep the app running in the fg to let it complete
 * Retry restoration if it fails?
 * Not talk about "confirming recovery key" if it's asking you to enter it for the first time - surely it's not a confirmation (which implies that you're confirming a user action which the user just performed) but a plain old "enter your recovery key"?
 * Enabling backup should be O(1) with size of backup (e.g. by incrementally restoring it in the background, resuming as needed, starting with the most recent keys), to avoid penalising powerusers.

#### What happened instead?

Very cryptic and suboptimal experience trying to use E2EE backup as a poweruser.

Meanwhile my Element Desktop coughed up...

![image](https://github.com/vector-im/element-x-ios/assets/1294269/6261112f-e5d6-4966-be40-4f4652371e42)

...and no longer seems to recognise my recovery passphrase :|

### Your phone model

iPhone 12 Pro Max

### Operating system version

ios 16.7

### Application version

421

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ara4n** [comment]
apparently EX went and created a new backup version, using a passphrase which doesn't match the previous one, thus breaking backup everywhere.

**Comment by ara4n** [comment]
This is *really bad*, in that it corrupts your backups for all clients (with the private key to the new backup stuck in the guts of EXI), and if you then lose keys on other devices then you could lose your history.

**Comment by manuroe** [comment]
This nasty bug happened during the development of the backup feature. The SDK no more recreates a new backup after entering the recovery key.

**Comment by manuroe** [comment]
FTR, it happened on any account, whatever the size.

**Comment by richvdh** [comment]
> This nasty bug happened during the development of the backup feature. The SDK no more recreates a new backup after entering the recovery key.

@manuroe was there an issue for this? Or can you link the PR that fixed it?
