### ISSUE TITLE
Post-demo cleanup™

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#198]
With the demo now behind us it's time to go back and cleanup some things. Here's a list in no particular order

- [ ] Get Rust bits merged into main and make proper release
- [x] thumbnail fetching. How do we deal with different image view sizes. Currently using hardcoded default for avatars
- [ ] sliding sync diffing optimisations (moved a bunch of stuff to background threads)
- [x] restarting the sync after the app becomes active. Also making sure it's closed properly on logout
- [x] retain cycles in the room view model (additionally stop timeline listeners and release `RoomProxy`s)
- [ ] re-review new timeline api changes
- [x] re-review bubbles
- [x] re-review the settings screen
- [x] split up the app coordinator state machine?
- [x] fix codecov!
- [x] re-review display name and user avatar caching? - lets leave Client/RoomProxy on the MainActor
- [x] switch blocking Rust calls to dispatch queues
- [x] add more UI tests.. home screen for example
- [x] fix room list loading rooms modal on new accounts (no rooms)
- [x] iOS 16 support
- [x] voiceover and dynamic type review
- [ ] automatic logout when offline. Return proper errors from the Rust auth service
- [x] Rust: replace `expect` with `context` everywhere

**Comment by niquewoodhouse** [comment]
@stefanceriu thanks for the list!

>  re-review bubbles
>  re-review the settings screen

Are these the only two UI specific reviews (eg wireframe bubbles look odd)?  Just looking to plan out the next design milestones

**Comment by stefanceriu** [comment]
@niquewoodhouse It would probably good idea for you to review the whole app. We've redesigned the following:
* room list
* user avatar contextual menu
* settings screen
* timeline + bubbles
* new message composer w/ reply state
* timeline item contextual menus

p.s. we haven't changed the splash screen or the onboarding but we have changed the accent color on it

You can use the build here https://i.diawi.com/Pr3Kwc, totally safe to use your normal account.

**Comment by niquewoodhouse** [comment]
> timeline + bubbles

Just testing the bubbles and wondering if we can do dynamic widths for messages?  If yes, do we need a min and max-width for each content type, or just generally a min and a max for any bubble, and let the content work out the width?

thanks

**Comment by ismailgulek** [comment]
> Just testing the bubbles and wondering if we can do dynamic widths for messages? If yes, do we need a min and max-width for each content type, or just generally a min and a max for any bubble, and let the content work out the width?

We can definitely do it, and tbh it's a lot easier to do it (for the max bubble width: we can have some margins for all bubbles or use a screen width percentage like we do right now for bubble width). 

However we need to think about message grouping here. In your screenshot there is no grouping at all so it seems fine but if we want message grouping, we need to think consider how it's gonna look when consequent messages have different bubble widths etc. Also the rounded corners might be another issue around it, maybe we can inspire from Web designs there.

**Comment by stefanceriu** [comment]
Closing in favor of https://github.com/vector-im/element-x-ios/issues/239 and https://github.com/vector-im/element-x-ios/issues/240
