### ISSUE TITLE
App crashes on block/unblocking user

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-x-ios#1998]
- go to user details
- click block

And then the app crashes. Upon reopening the user is actually blocked. If you unblock them the same thing happens again.

**Comment by pixlwave** [comment]
I'm unable to reproduce the crash following these steps on an iPhone:
- From the timeline tap a user's avatar.
- Tap Block User in the user details screen.

Or 
- From the timeline tap the room header.
- Tap the People button to get to the members list.
- Tap a member.
- Tap Block User in the user details screen.

If there's any more information you have on this, let me know and I'll try dig into it further.

**Comment by stefanceriu** [comment]
I am unable to reproduce it either, closing for now.
