### ISSUE TITLE
Same user shows twice in RR

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-ios#2000]
### Steps to reproduce

1. Open a group chat

#### What did you expect?
Can only see one RR per user

#### What happened instead?
Can see RR twice for the same user at different points in the timeline

Internal reference: iOSX-2

### Will you send logs?

No

**Comment by pixlwave** [comment]
Changing to uncommon as Read Receipts are behind a development flag and not enabled on the app.

**Comment by Velin92** [comment]
This is issue is already described in detail here, and seems to be a mix of a BE and a Rust SDK issue:
	https://github.com/vector-im/element-x-ios/issues/1784
