### ISSUE TITLE
Update avatar preview screen

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-ios#2001]
### Steps to reproduce

1. Go to a user detail page for another user
2. Click on their avatar

#### What did you expect?
I do not have the options for forwarding, editing and doing an "iOS search" for another user's avatar.

#### What happened instead?
The UI shows me options that I shouldn't be able to take

Internal reference: iOSX-5

### Will you send logs?

No

**Comment by pixlwave** [comment]
@kittykat Assuming you have the same comments for the room avatar too?

Adding a few thoughts:
- The share option is useful to save an avatar to your device rather than making users screenshot the image *cringe*
- What is an "iOS search", I can't see how to trigger any search in that screen?

**Comment by pixlwave** [comment]
@VolkerJunginger I think you might have more context 👆

**Comment by VolkerJunginger** [comment]
I can understand that our users would like to have this more as an magnifier feature.

Is it maybe easier to implement a quick-look functionality like for example instagram is having?


https://github.com/vector-im/element-x-ios/assets/118339066/f0c2e0ea-c316-495e-9add-bf43fdda83bc

**Comment by VolkerJunginger** [comment]
Please, remove all actions form the image screen, so this is just an option to magnify the image.
