### ISSUE TITLE
DM is still in room list after leaving it

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-ios#2005]
### Steps to reproduce

1. Leave a DM

#### What did you expect?
DM is no longer in the room list

#### What happened instead?
DM is still in the room list

There are three scenarios:

1. User leaves room
If a user leaves a room the room should disappear from the room-list. 

2. User gets kicked from a room
If a user gets kicked from a room the room should stay in the room list.
- The user should still have access to the history that they have been a part of (UX - is that right?)
- The room should not be updated.
- The user cannot write in the room anymore
- The user can join the room again. To join a room the user needs to go through the same invitation flow as a user that has never been a member.

3. User is banned from a room
The room should disappear from the roomlist.
The user can only re-join when they are un-banned by a moderator.

**Comment by pixlwave** [comment]
A quick test of this and I was able to reproduce it by leaving the DM on the home screen from the room's context menu. The DM was down towards the bottom of my room list if that matters.

**Comment by pixlwave** [comment]
More info I just noticed: The same steps above also reproduce the issue for a room too. Force quitting and reloading the app appears to fix the problem, but now I see the last room in my list duplicated.

**Comment by bnjbvr** [comment]
For what it's worth, I've been asked to investigate this, so stealing assignment @stefanceriu; please keep me updated if you found anything useful. I think at this point the SDK doesn't process left rooms at all, in the context of sliding sync.

**Comment by bnjbvr** [comment]
> I think at this point the SDK doesn't process left rooms at all, in the context of sliding sync.

This was wrong. In fact, when a user leaves a room, the sliding sync proxy doesn't update the `lists` part of the sync response, so that change is never propagated back to the SDK nor the apps. It's unclear from reading the MSC if the proxy server is supposed to remove the room from the list or not, but I would suppose so.

If that's not the case, then we could filter out left rooms from the sliding sync lists. To be continued on Monday.
