### ISSUE TITLE
Lock screen grace period is *very* confusing and insecure

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#2011]
### Steps to reproduce

1. Enable lock screen
2. Launch the app
3. Enter your PIN code
4. Feel nice and secure
5. A few minutes later, hand someone your phone so they can enter their phone number / order takeaway / futz with venmo / etc
6. Discover that they were able to a) view the contents of Element in the task switcher, b) switch to the app and read your messages.

#### What did you expect?

I'd expect the PIN to be prompted for every single time you foreground the app, at least by default, otherwise its security is very questionable indeed.  I'd also expect the UI of the app to be hidden as soon as it gets backgrounded, to avoid people shouldersurfing the task switcher (or iOS from caching sensitive content for the task switcher sprites)

Critically, the app should behave like WhatsApp or banking apps which default to having no grace period.

#### What happened instead?

A confusing setup where some of the time you get prompted for PINs by the app, and sometimes you don't, and the user doesn't know when they're protected or not.

### Application version

424

### Will you send logs?

No

**Comment by pixlwave** [comment]
We're going to set the grace period to 0 and let forks set a custom value if they want that behaviour.
