### ISSUE TITLE
Keyboard hides EX popup when following an EC link

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#2025]
### Steps to reproduce

1. Click on an EC link
2. It opens in EX
3. If EX had a timeline open, you end up with a keyboard over the overlay that you can’t get rid of.

![IMG_3903](https://github.com/vector-im/element-x-ios/assets/1294269/d039dfc3-137b-431c-92cd-1b7cecd8d2e4)

#### What did you expect?

no rogue keyboard

#### What happened instead?

rogue keyboard

### Application version

427

### Will you send logs?

No

**Comment by stefanceriu** [comment]
@ara4n unfortunately neither me nor doug can reproduce this. Anything more you can give us to go on?

**Comment by ara4n** [comment]
trivially reproable for me:

https://github.com/vector-im/element-x-ios/assets/1294269/f35d6ada-544d-4f20-9666-adee63e5ad84

**Comment by stefanceriu** [comment]
Heh, it's the lock screen, 100% reproducible with that enabled.
