### ISSUE TITLE
Expose log files in iOS Files app

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#2028]
It'd be helpful to expose EX's log files in the iOS Files app to help advanced users see what's going on when debugging, and to give confidence over what we log.

**Comment by stefanceriu** [comment]
Hi, we had a look at this but Element X is using an AppGroup to share log locations between different processes. The UISupportsDocumentBrowser Info.plist key only allows files that are present in the App's **local** Documents folder to be exposed to the Files.app. There are of course workarounds but none that are worth it in our oppinion. We would much rather just do https://github.com/vector-im/element-x-ios/issues/734
