### ISSUE TITLE
Unlock screen has inconsistent bg on dark theme

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#2029]
### Steps to reproduce

![IMG_3906](https://github.com/vector-im/element-x-ios/assets/1294269/f65f2ab2-5336-40bd-9307-4f2120471677)

is this meant to be black at the bottom yet grey on the top?

#### What did you expect?

consistent bg, like the light theme has:

![IMG_3907](https://github.com/vector-im/element-x-ios/assets/1294269/10092823-8f0f-4031-bd00-f5b1a8d637bf)

#### What happened instead?

50 (well 2) shades of grey

### Application version

428

### Will you send logs?

No

**Comment by pixlwave** [comment]
Ooooops!
