### ISSUE TITLE
Sent an undecryptable message

### ISSUE THREAD

**Issue by Hywan** [vector-im/element-x-ios#2043]
### Steps to reproduce

I've received a UTC for event `$S_TCPxFFQpQDpzdLG-j0_MwAewNb5ZEzAPMpKtz09JU` and `$G-5yKd4h7yKE2GGOXiRc1EvjjwEoXNeNZ8DpJPq6fQY` from room `!qjYaZmNMvDWQlPLQbI:matrix.org`.

#### What did you expect?

Not a UTD, as with Element X iOS for example.

#### What happened instead?

A UTD.

### Operating system

macOS

### Browser information

Firefox 121.0a1 (2023-11-05)

### URL for webapp

develop.element.io

### Application version

Version de Element : 61cfe567743f-react-9bb50119c752-js-311494bd44fd Crypto version: Rust SDK 0.6.0 (9c6b550), Vodozemac 0.5.0

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
We're not getting a lot of reports like this so I'm inclined to close it, at least for now.
