### ISSUE TITLE
EXi types "Left Double Quotation Mark" when "Quotation Mark" keyboard button is pressed

### ISSUE THREAD

**Issue by Twi1ightSparkle** [vector-im/element-x-ios#2060]
### Steps to reproduce

1. Where are you starting? What can you see? In the composer
2. What do you click? The " button on the default US English iOS keyboard
3. You now have a [`“` - Left Double Quotation Mark (U+201C)](https://unicodeplus.com/U+201C) instead of the expected [`"` - Quotation Mark (U+0022)](https://unicodeplus.com/U+0022)

Note, this does not happen on EX Android. And in other apps on my phone, pressing " on me keyboard produces the correct Quotation Mark

#### What did you expect?

"

#### What happened instead?

“

### Your phone model

iPhone 11 Pro Max

### Operating system version

16.7

### Application version

1.4.0 (77)

### Homeserver

n/a

### Will you send logs?

No

**Comment by pixlwave** [comment]
This behaviour is expected, iOS and macOS does it everywhere.

https://github.com/vector-im/element-x-ios/assets/6060466/0f2d1618-88d6-4a49-8612-e7145260d9f8

**Comment by pixlwave** [comment]
Note: If you don't want this behaviour, you can long-press on the quote button and choose the `"` alternate instead of `”`
