### ISSUE TITLE
Element doesn't allow me to sign out

### ISSUE THREAD

**Issue by poppyseedDev** [vector-im/element-x-ios#2153]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

#### What happened instead?
<img width="1091" alt="Screenshot 2023-11-22 at 17 42 34" src="https://github.com/vector-im/element-x-ios/assets/30662672/083668d9-06c9-4857-946a-4f3edd6d6aec">

### Will you send logs?

Yes

**Comment by poppyseedDev** [comment]
Sorry this issue should be labeled mac os app

**Comment by stefanceriu** [comment]
This doesn't look like Element **X** (the iOS app that happens to run on Apple Silicon) though 🤔

**Comment by pixlwave** [comment]
Yep closing this as that looks like Element Desktop. Please open your issue here @poppyseedDev:
https://github.com/vector-im/element-web
