### ISSUE TITLE
Can't enable key backup

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#2218]
### Steps to reproduce

1. Was on build 451 on macOS. Enabled key backup, and got as far as the prompt for a passphrase.
2. Realised i was on an old build, and upgraded to 457
3. Relaunched and tapped "confirm your recovery key"
<img width="628" alt="Screenshot 2023-12-08 at 19 05 40" src="https://github.com/vector-im/element-x-ios/assets/1294269/9ddb8d9e-73a2-4fac-a5b9-52107eebeec7">

4. Takes me to a "Turn on backup" button, which fails with "Error" when pressed.

#### What did you expect?

Ability to turn on backup

#### What happened instead?

ERROR

### Your phone model

macOS

### Operating system version

Ventura

### Application version

457

### Will you send logs?

Yes

**Comment by ara4n** [comment]
This looks to be because EX sees the recovery state as "unknown", despite rust sdk shifting it to "incomplete". In state "unknown", the "confirm recovery key" prompt is hidden in the SecureBackupScreen in settings, and so one can never enter the recovery key.

**Comment by stefanceriu** [comment]
Should be fixed by https://github.com/vector-im/element-x-ios/pull/2223
