### ISSUE TITLE
Message sending retry management

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#250]
Build mecanism for displaying and retrying messages that failed to send.

**Comment by ara4n** [comment]
n.b. that the retrying *has* to be queued in order (in the rust-sdk, presumably). given the send API doesn't let you define an ordering relative to other sends (https://github.com/matrix-org/matrix-spec/issues/1316), we have no choice but serialise each /send and wait for the previous one to complete with a 200 OK before sending the next one.

**Comment by pixlwave** [comment]
@ara4n Am I right in thinking its safe to queue send and retry per room as opposed to globally?

**Comment by VolkerJunginger** [comment]
Duplicate to https://github.com/vector-im/internal-planning/issues/312
