### ISSUE TITLE
Timeline scroll bugs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#270]
**Describe the bug**
Lots of timeline scroll positioning bugs:

**To Reproduce**

* open a room, get taken to a message in the past rather than the latest message.
* as messages get fwd/back-paginated in (and have their profiles resolved) the scroll offset jumps around
* send a message, see the timeline doesn’t scroll doen to show the recently 
* hit scroll to bottom; doesn't always jump to the bottom.

**Expected behavior**
No scroll jumps :)

Nightly, iOS 16.1, iPhone 12 pro max

**Comment by stefanceriu** [comment]
This should be fixed (or at least ameliorated) in https://github.com/vector-im/element-x-ios/issues/276 . Let's raise new tickets for things that still don't work properly.
