### ISSUE TITLE
Roomlist "All Chats" stays empty on private synapse server

### ISSUE THREAD

**Issue by paddsen** [vector-im/element-x-ios#294]
**Describe the bug**
The roomlist "All Chats" stays empty on private synapse server. It works well on matrix.org.
There is no issue in debug windows on Xcode nor  in logs on synapse, sygnal or sydent server instances.
Synapse is 1.70.1. ElementX is latest develop.
Settings on ElementX are working. Sign out is working.

**Expected behavior**
Roomlist should load as it does on Element-Ios 1.9.9.

**Screenshots**
<img width="436" alt="image" src="https://user-images.githubusercontent.com/16487932/200177278-221a91ae-11f9-4b39-ab2c-f1097ffe5396.png">

**Smartphone (please complete the following information):**
 - Device: iPhone 12 Pro Max as physical device or iPhone 14 Pro Max as Simulator
 - OS: iOS 16.1

**Comment by ara4n** [comment]
for ElementX to work you currently need to use it with a sliding sync proxy: https://github.com/matrix-org/sliding-sync
