### ISSUE TITLE
Fix timeline bubble corner radii

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#296]
In [290](https://github.com/vector-im/element-x-ios/pull/290) We have decided make the width of timeline bubbles dynamic, based on their content, but that breaks the corner radii treatment for grouped bubbles. We need to sync up with the design team and decide on what the correct fix is.

![Image](https://user-images.githubusercontent.com/637564/200243048-c6b20738-7c5f-4bd4-8e84-5c3f7d3492d5.png)

**Comment by ara4n** [comment]
(my hunch would be that convex corners should be round, and concave corners would be left alone. And the act of adding a reaction as per the example above would effectively split the sequence, causing 4 convex corners)

**Comment by jplatte** [comment]
FWIW, what Signal does:

![Screenshot_2022-11-07_101512](https://user-images.githubusercontent.com/951129/200272414-3b53ed4c-6f84-4880-804f-c1054dfcc6b6.png)

Difference in empty space between first/second and second/third is probably a bug 😄

**Comment by ara4n** [comment]
(i'm deliberately proposing something different to signal, fwiw)

**Comment by janogarcia** [comment]
@stefanceriu We'll explore this in more detail, as we're currently defining the cross-platform design language. For now, just apply the same radius for both corners.

So, for `New how office set up!` you'd apply same radius for both the top-left and bottom-left corners, as in the example for "Hard edge radius + Large inner radius":

<img width="1102" alt="Frame 158" src="https://user-images.githubusercontent.com/60790/201435247-3d6a0a11-f990-4860-b767-7565ccb7f8e4.png">

**Comment by stefanceriu** [comment]
Morning @janogarcia, thanks for looking at this. Is this what you had in mind:?

![Screenshot 2022-11-14 at 10 25 07](https://user-images.githubusercontent.com/637564/201611109-be5384ed-5502-4d70-8856-649dc44cdb9d.png)

**Comment by janogarcia** [comment]
@stefanceriu Thanks for the update. Yeah, let's use that treatment for now. 👍
