### ISSUE TITLE
If your access_token is invalid, the app doesn't notice.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#297]
I logged out one of my EX sessions, apparently. The app didn't notice, and instead displayed empty timelines.

If you get a 403, you should log the user out and destroy all their data - unless the error code includes `{ soft_logout: true }`, when you should reauthenticate the user instead. \(c.f. https://spec.matrix.org/unstable/client-server-api/#soft-logout\)

**Comment by stefanceriu** [comment]
Rust ticket - `FFI / Sliding sync / Client - Error handling` - https://github.com/matrix-org/matrix-rust-sdk/issues/1286

**Comment by stefanceriu** [comment]
> do we need to do anything on the app side

Yes, we need to listen to those errors coming from rust and act accordingly.
