### ISSUE TITLE
Setup Apple app site associations

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#301]
In order for deeplingking and credential suggestions to work properly we need to setup ElementX along the existing apple app site associations e.g. https://app.element.io/apple-app-site-association

We need this for normal ElementX, ElementX Nightly and ElementX PR

Same as here https://github.com/vector-im/element-ios/blob/develop/Riot/SupportingFiles/Riot.entitlements#L5 but let's filter out legacy (now unused) domains

**Comment by Velin92** [comment]
https://github.com/vector-im/element.io-website/issues/137 <- related issue on the element.io website git
