### ISSUE TITLE
Add a ProgressView to the syncing indicator.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#351]
The current implementation doesn't match the designs from Figma:
https://www.figma.com/file/G2ulpYxj8I0JzFyQznugwc/Element-X-BBQ-Alpha?node-id=119%3A14510&t=AygFYvedpsM3qMy1-4

**Comment by stefanceriu** [comment]
The "Syncing" indicator tends to get in the way of other components and doesn't look great either. We agreed to go back to the in-timeline spinner for now.
