### ISSUE TITLE
Left Panel room previews are often stale

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#392]
Running EIX on macOS \(as an iOS app on M1 macOS\), the room previews often show messages which are 3-4 events behind the actual most recent message in the room in question.

**Comment by ara4n** [comment]
for example, compare the room preview of EMS Internal with the history:

<img width="967" alt="Screenshot 2022-12-23 at 15 46 30" src="https://user-images.githubusercontent.com/1294269/209362618-a4d82fbe-9f22-4584-8713-7a32b715de77.png">

**Comment by stefanceriu** [comment]
This should now be fixed
