### ISSUE TITLE
Room list search is not accurate if rooms are not all loaded in the list

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#397]
The user will not need anymore to manually paginate all the rooms when [allRoomsView](https://github.com/vector-im/element-x-ios/blob/ab10278ff54de5fa9b3b9a582b78579b7451790f/ElementX/Sources/Services/Client/ClientProxy.swift#L108) will be enabled.
But we still need to manage the case where not all rooms have been loaded in background.

**Comment by stefanceriu** [comment]
This should now be fixed
