### ISSUE TITLE
Reuse strings from Element-Android

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#4]
We want to reuse them for several reasons:
- Android is better for supporting plurals
- Better parity between mobile apps
- Less work for translators

We want to rely entirely on them. This means the iOS developer will have to:
- add strings first on the Android project and PR them
- run a script to retrieve from the EA repo

This script could be run like xcodegen when you set up the project.

The final strategy is still to be defined. As part of this research project, we need to define what will be the best (or least bad) in term of devx.

Open questions:
 - [ ] Should those generated strings be in git? 
 - [ ] ...

**Comment by Johennes** [comment]
Not sure if helpful but in a previous project I've used https://github.com/icerockdev/moko-resources to load iOS & Android strings from a single source.
