### ISSUE TITLE
Manage homeservers with no Sliding Sync support

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#409]
EX only supports the SS API. It does not support the `/sync` v2 API that has been used for years.
Synapse does not offer it yet. The app needs to go through the SS proxy that will do all the necessary logic.

Two options:
- Short one: Ask the user to use a homeserver that supports SS
- Long one: Ask them to use somebody else SS proxy with a big warning that this will give the proxy an acces token

**Comment by kegsay** [comment]
> Long one: Ask them to use somebody else SS proxy with a big warning that this will give the proxy an acces token

Bear in mind that:
 - this is a huge security footgun, and it is unlikely that the average end user would understand the implications.
 - proxy servers are hard-coded to a single destination server else they become open proxies, so it's not like we can point people at the matrix.org SS proxy for their myowndomain.com HS.
