### ISSUE TITLE
Rooms stay unread after visiting them

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#414]
The unread state in the room list \(bolded last message and circle\) should be reset when coming to the room list.

**Comment by manuroe** [comment]
- [ ] We will need to create the rust API (should be not hard)
- [ ] Rust SDK does not provide updates when reading a room from another client updating the marker.

**Comment by pixlwave** [comment]
I'm going to mark this as complete. We send read markers on entering/exiting the room, and there's a Rust issue for the fully read markers not tracking your other clients.
