### ISSUE TITLE
Cannot swipe to leave the media fullscreen view

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#418]
Instead, we have to tap the `Back` button in the top navigation bar. This is kind of old school.

**Comment by pixlwave** [comment]
I looked into this with #447, however using `QLPreviewController` (which gives us a head-start with a *lot* of functionality for free) wrapped in an `NSViewControllerRepresentable` struct doesn't provide us with the "automatic" swipe gestures  that it provides within a UIKit hierarchy. I tested this with the controller wrapped in both `UINavigationController` (it updates the toolbars automatically in this one) and within `NavigationStack` and didn't get anything out of it.

The decision for now was to deprioritise the gestures so this issue should probably have the `TF` label removed?
