### ISSUE TITLE
Profiles load slowly in the timeline

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#425]
Senders display names and avatars are slow to appear the first time you open a room.
Curiously they resolve at the same time whereas we could expect display name to be instant.

**Comment by manuroe** [comment]
Rust should resolve them for the app.

**Comment by stefanceriu** [comment]
We have managed to get profile data working through the rust SDK [here](https://github.com/matrix-org/matrix-rust-sdk/pull/1336) but unfortunately it causes tokio panics 

```
thread 'tokio-runtime-worker' panicked at 'Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks.', /Users/stefanceriu/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.24.1/src/runtime/scheduler/multi_thread/mod.rs:65:25
2023-01-11T14:19:28.758063Z ERROR uniffi::ffi::rustcalls: Caught a panic calling rust code: "Cannot start a runtime from within a runtime. This happens because a function (like `block_on`) attempted to block the current thread while the thread is being used to drive asynchronous tasks."    
```

and the only way to fix seems to be adopting the new async unffi support which, as nice as it is, wouldn't be a good idea to drop into the app unless we have time to properly test it out

**Comment by stefanceriu** [comment]
This has now been addressed through https://github.com/vector-im/element-x-ios/pull/483
