### ISSUE TITLE
[Epic] Public TestFlight

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#428]
We want to publicly publish a beta version of ElementX-iOS on TestFlight. The feature scope is limited to what we have so far. We just want to optimise and polish existing things.

Notes:
If we bump only the build version, there is no TF review. The build is available ASAP

```[tasklist]
### Remaining tasks
- [ ] #537 
- [ ] #532 
- [ ] #448 
- [ ] #435 
- [ ] #398 
- [ ] #394 
- [ ] #528 
- [ ] #529 
- [ ] #530
- [x] Design signoff
- [x] QA signoff
- [x] Product signoff
- [x] Announcement for sharing the link
```

Not required for TF:
    - Block users
    - Report content
    - Provide a test account

**Comment by stefanceriu** [comment]
@VolkerJunginger Here's the Testflight ticket.

We will need to write up some announcements for both the public Element iOS room and TWIM.
We should also check

**Comment by VolkerJunginger** [comment]
https://docs.google.com/document/d/1vTCjw9iSjIBq8kDqUAi5A6KZSc7esVSyNxBzPa3I6D0/edit

**Comment by amshakal** [comment]
Everything looks good to me. Thank you!
