### ISSUE TITLE
DesignKit component

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#43]
The new Design Kit project should start in EIX as a swift package that EI could use.

**Todo**
- \[x\] Handle some rogue colours that have creeped into the EI theme.
- \[x\] Check in the package.resolved file in EI.
- \[x\] Try to generate `namesAndAvatars` array from the style dictionary.
- \[ \] <del>Consider whether or not fonts can be generated by the style dictionary.</del>
- [ ] Migrate DesignKit to use [vector-im/compound-design-tokens](https://github.com/vector-im/compound-design-tokens)

**Comment by pixlwave** [comment]
Closing this in favour of https://github.com/vector-im/internal-planning/issues/381
