### ISSUE TITLE
Design review for first public TestFlight

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#430]
As described in #428, we want to release an early version of the app as a public TestFlight. It would be great to have designer support to go and visit all the current EIX app for design issues.

If there are differences with figma, let us know.
If there are things to change, update figma, we will follow.

We may also want to revisit:
- the icon
- the splash screen
- may be the white & black design?

Valere had interesting feedbacks [here](https://matrix.to/#/!kCCQTCfnABLKGGvQjo:matrix.org/$BigzBOX213ieSnsaURWSQcBoQ4stUT-8nPRRA1VVFYk?via=matrix.org&via=element.io&via=one.ems.host) about the room list.

Amandine says:
- Unread rooms are shown with the room preview bolded, which means that it looks visually the same as the title of the room, which is very visually confusing in terms of information hierarchy. Perhaps just don't bold the preview, and rely on the white dot instead? "Bold = unread" was always a UX antipattern, given some users can't distinguish bold from normal weight fonts.
- Dynamic type seems a bit overenthusiastic. If the user dials DT down to minimum font size in the OS, then on an iPhone 14 Pro \(normal size, not Max\) then the room previews and titles get *really* small, relative to other apps like iMessage. Is there a way we can let the user tweak/override DT sizing from within the app?

**Comment by amshakal** [comment]
Hey Manu, I am unable to access the feedback Valere left. Any chance a screenshot (or text copy paste) of his feedback is possible?

**Comment by manuroe** [comment]
Argh sorry. Here is the screenshot:
<img width="537" alt="image" src="https://user-images.githubusercontent.com/8418515/213420743-421a8373-6b2c-4630-99e7-c7403f05a994.png">

The main point is that alignment changes when you scroll the room list is creating headaches.

**Comment by callumu** [comment]
Thanks for sharing. We're currently working on improving the Room list and all the concerns raised in the screenshot are being amended with the new design.
