### ISSUE TITLE
Make English the unique supported language

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#434]
as long as we do not have the proper translation framework \(#124\)

**Comment by pixlwave** [comment]
Fixing the Locale to English at the top of the SwiftUI view hierarchy works for our strings and allows us to keep German for UI tests. However there are plenty of system elements such as formatted dates, back buttons, file and edit menus that are getting their Locale from elsewhere. The amount of time needed to investigate these as a temporary fix won't be worth it so we've decided to leave everything as is.
