### ISSUE TITLE
Adjustable text size

### ISSUE THREAD

**Issue by QEDeD** [vector-im/element-x-ios#44]
**Is your feature request related to a problem? Please describe.**
As a user with reduced eyesight, I struggle with the size of the text and UI in general (of the old iOS app). 

**Describe the solution you'd like**
I want the app to support the iOS system-wide Text settings, in particular the Larger Text setting. The settings are described here: https://support.apple.com/guide/iphone/display-text-size-iph3e2e1fb0/ios

**Comment by pixlwave** [comment]
Hey @QEDeD thanks for creating the issue. We have very much been bearing dynamic text in mind from the very start of prototyping ElementX iOS and it will be something that we support. Here's a sneak peek:

![Simulator Screen Recording - iPhone 13 Pro - 2022-05-11 at 16 15 20](https://user-images.githubusercontent.com/6060466/167886074-d6f2dba8-7a61-4a2a-8bb8-f44a43d4b4c6.gif)

**Comment by QEDeD** [comment]
Looks great, thanks!

**Comment by stefanceriu** [comment]
I think we can close this for now. Please do raise bugs if this doesn't work properly in any part of the app. Thank you!
