### ISSUE TITLE
Improvements to FileCache logic.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#444]
Whenever we download media to show via AVPlayer/QuickLook the file is cached using naive guesses of the file extension. As we're writing `Data` to disk, the file doesn't have any useful type metadata, so if the file extension is wrong \(e.g. #443\) then playback/previewing will fail. We should either:
- Add more robust file type detection by reading the mimetype from the event, and then checking the data received.
- Pass this over to Rust itself and instead have it return us a valid URL to open the file from rather than data which we write to disk.

**Comment by stefanceriu** [comment]
Relates to https://github.com/vector-im/element-x-ios/issues/316
