### ISSUE TITLE
edited replies aren't shown as replies

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#451]
**To Reproduce**
 * reply to a msg
 * edit your reply (in EI at least)
 * observe the reply is not shown as a reply any more

**Comment by jplatte** [comment]
This is pretty likely a Rust SDK bug. Will look into it tomorrow.

**Comment by jplatte** [comment]
This should be fixed as of https://github.com/vector-im/element-x-ios/pull/861. cc @stefanceriu

**Comment by kittykat** [comment]
Can confirm that it's fixed in TF
