### ISSUE TITLE
allrooms view grows in a very strange manner

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#461]
I removed the 500 room cap on allrooms on my account, and looked to see how it grew the window \(by observing SS ranges\). It grew the view as follows:

```
(0, 20)
(0, 900)
(0, 2100)
(0, 1000)
(0, 2100)
(0, 3500)
(0, 3839)
```

Shouldn't be growing in first 20, and then blocks of 200 or so? Why did it go backwards? And why did it never cover the full range \(4053 rooms\)?

**Comment by stefanceriu** [comment]
This has been fixed
