### ISSUE TITLE
Incorrectly parsed linked in message body

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-x-ios#464]
**Describe the bug**

![IMG_0714](https://user-images.githubusercontent.com/769871/213113004-e381d881-1e58-4564-8652-44ccbb7a54d4.jpg)

On yesterday's latest test flight

**Comment by stefanceriu** [comment]
Caused by `NSRegularExpression`/`NSDataDetector` not knowing how to deal properly with unicode scalars. 

```
(lldb) po string
"Hello. 🙂 Not sure if you saw https://github.com/vector-im/element-web/issues/24229"

(lldb) po string.count
82

(lldb) po (string as NSString).length
83

(lldb) po range
▿ {0, 83}
  - location : 0
  - length : 83

(lldb) po MatrixEntityRegex.linkRegex.matches(in: string, options: [], range: range)
▿ 1 element
  - 0 : <NSLinkCheckingResult: 0x600003c27720>{30, 53}{https://github.com/vector-im/element-web/issues/24229}
  ```
  
  where I changed the range to be `NSRange(location: 0, length: (attributedString.string as NSString).length)` instead of `NSRange(location: 0, length: attributedString.string.count)`
