### ISSUE TITLE
Can't parse event body

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-x-ios#465]
**Describe the bug**

![IMG_0715](https://user-images.githubusercontent.com/769871/213113186-45a52eb3-8ea1-4fb7-bc2c-fd3cba20d1ff.PNG)

**To Reproduce**

Event content example

```
{
  "content": {
    "body": "Syncing artifacts...",
    "m.relates_to": {
      "event_id": "$fXFo-OCiaXCG1et_bWIwutdSCvQmG0NUIl1nlHO4HTw",
      "rel_type": "m.thread"
    },
    "msgtype": "m.notice"
  },
  "origin_server_ts": 1673946658122,
  "room_id": "!iMHopbhyKBpzonjTyZ:matrix.org",
  "sender": "@riotrobot:matrix.org",
  "type": "m.room.message",
  "unsigned": {
    "age": 1500798
  },
  "event_id": "$9D0bASvIFebIEtoIA91IompdgSrEyk_bd4YWlyCNplo",
  "user_id": "@riotrobot:matrix.org",
  "age": 1500546
}
```

**Comment by jplatte** [comment]
Interesting, so Ruma [enforces](https://github.com/ruma/ruma/blob/62ed200a56d00353eea128191311c4c8016def9f/crates/ruma-common/src/events/room/message/relation_serde.rs#L35-L38) reply fallbacks on threads, which don't seem to be required as per [spec](https://spec.matrix.org/v1.5/client-server-api/#threading). I'll fix it.

**Comment by jplatte** [comment]
It might be that my interpretation was wrong. There is this sentence:

> To work around this, events sent by clients which understand threads include rich reply metadata to attempt to form a reply chain representation of the conversation.

which says that reply fallbacks *are* mandatory. I brought it up [in #matrix-spec](https://matrix.to/#/!NasysSDfxKxZBzJJoE:matrix.org/$u987mZ4qSTDa3_pERBap2VQPWvJrVeyQm1wXZ7Uda_I?via=matrix.org&via=libera.chat&via=element.io).

**Comment by jplatte** [comment]
New Ruma PR, after the previous one was reverted: https://github.com/ruma/ruma/pull/1486
