### ISSUE TITLE
Room avatars disappear in room list

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-x-ios#466]
**Describe the bug**

Sometimes all avatars on the room list and the fallback (coloured avatar with a letter in it) appear instead

**To Reproduce**

I haven't been able to pin-point steps to reproduce, but it seems to happen when going back from the chat view to the room list, and there's a flash on the correct avatars, and then the room list transforms in its incorrect form.
This has also been seen when coming back to EX from a different application

**Comment by stefanceriu** [comment]
This should be fixed now, please reopen if you see it misbehaving again.
