### ISSUE TITLE
Loading in the app in low connectivity fails to show avatars

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-x-ios#467]
**Describe the bug**

Loading the app in low connectivity or offline fails to show the avatars in the room list. 
I was in the underground and when loading the app I can see all my rooms, but the avatars are not displayed correctly, which makes the app feel glitchy 

**To Reproduce**

Use Element X in the London Underground

**Expected behavior**

For avatars to be cached

**Comment by stefanceriu** [comment]
Same as the other one, should behave a lot better now. Please reopen if not.
