### ISSUE TITLE
Reaction not appearing

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-x-ios#469]
**Describe the bug**

Send a thumbs up reaction on EX. It does not appear. 
Look on Element Web and the reaction exists on the event

**To Reproduce**
1. Send a reaction to an event

**Expected behavior**

For the reaction to appear straight away

**Comment by stefanceriu** [comment]
This seems to work correctly on my side, is it still a problem?

**Comment by gsouquet** [comment]
just tested and it works like a charm now! thank you
