### ISSUE TITLE
Timeline ordering for locally echoed msgs is wrong

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#479]
**Describe the bug**
The order in the timeline of locally echoed msgs is not updated when remote echo happens, making them appear confusingly out of order if your client isn't synced.

**To Reproduce**

1. Send some messages before the app has synced.
2. Watch the app sync and load a bunch of old msgs
3. Observe that these msgs get appended after the ones you just sent, likely pushing them off the top of the screen

**Expected behavior**

Messages we haven't yet received a remote echo for should always be appended to the bottom of the timeline until we receive the remote echo, which will then let us position them correctly.

this on today's nightly

**Comment by jplatte** [comment]
This is a known issue in matrix-rust-sdk, I have a todo for it in https://github.com/matrix-org/matrix-rust-sdk/issues/1103:

> - Handle remote echoes correctly (always use server ordering for events)
