### ISSUE TITLE
Avatar fallback should trim "@" when using mxid

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-x-ios#488]
**Describe the bug**

The avatar fallbacks to the first letter of the user it's attached to, but if the display name of that user has not been set, it will fallback to its mxid \(e.g. @alice:matrix.org\). In that case the avatar fallback shows `@`, where it should trim the `@` and display `A`

**To Reproduce**

1. Go offline \(easier to repro\)
2. Go in and out of rooms

**Expected behavior**

Avatar should display `A` when displayed using the mxid `@alice:matrix.org`

**Comment by Velin92** [comment]
Should have been fixed in https://github.com/vector-im/element-x-ios/pull/483
