### ISSUE TITLE
Incorrect message ordering in a room

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-x-ios#490]
**Describe the bug**

The state event should be the last event displayed in the room

**Steps to repro**

- Change your display name from another device whilst having EX open
- Open the room where that state event exists
- they are incorrectly ordered

Worth noting that killing the app and restarting it solved the issue

![IMG\_48B1DE1D27DC-1](https://user-images.githubusercontent.com/769871/214533836-519a482a-8b3e-44d2-bbbc-a7bab376135b.jpeg)

**Comment by manuroe** [comment]
Dup of https://github.com/vector-im/element-x-ios/issues/640 that is going to be fixed for real
