### ISSUE TITLE
Use only bubbles in timeline

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#491]
Until we rework the plain timeline view, we should not use it.

- [ ] Make the timeline use bubbles only
- [ ] Hide the option in the settings screen

**Comment by ara4n** [comment]
i am worried that for the FOSDEM audience, people will expect to see the plain timeline view as an option, even if it's ugly and broken.

**Comment by manuroe** [comment]
Got it! Thanks.
