### ISSUE TITLE
Structured logging

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#504]
The[ SDK PR](https://github.com/matrix-org/matrix-rust-sdk/pull/1417) is ready and is waiting for feedback.

**Comment by stefanceriu** [comment]
We have decided to go a slightly different round and switch to doing our logging through the Rust side directly.
Rust ticket here https://github.com/matrix-org/matrix-rust-sdk/issues/1463

**Comment by kittykat** [comment]
@stefanceriu can we close this ticket as we will fix it in the SDK?

**Comment by stefanceriu** [comment]
Fixed by https://github.com/vector-im/element-x-ios/pull/831
