### ISSUE TITLE
Out of memory crashes

### ISSUE THREAD

**Issue by stefanceriu** [vector-im/element-x-ios#531]
We need to investigate where we're leaking memory and causing out of memory crashes

https://sentry.tools.element.io/organizations/element/issues/2574/?project=44&query=is%3Aunresolved+release.version%3A1.0.18&statsPeriod=14d

**Comment by stefanceriu** [comment]
All fingers point to Sled and we agreed to put a cache limit on it rust side.
Rust side ticket: https://github.com/matrix-org/matrix-rust-sdk/issues/1471

**Comment by manuroe** [comment]
We replaced sled by sqlite.
