### ISSUE TITLE
Sending the first message of the day causes duplicated date separators

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#540]
**To Reproduce**

1. Open a room where no events/messages/items are shown for the current day.
2. Send a message into this room.

**Expected behavior**
The message should be shown with today's date above it.

**Actual behavior**
The message is shown with the date above it twice, likely once for the local echo \(which has now been removed\) and then again for the remote echo.

**Version**
Nightly 1.0.19

**Comment by stefanceriu** [comment]
Known issue on the Rust side and tested for here https://github.com/matrix-org/matrix-rust-sdk/blob/main/crates/matrix-sdk/src/room/timeline/tests/echo.rs#L95

**Comment by stefanceriu** [comment]
This should be fixed now Rust side, we need to test in when releasing the next SDK version
