### ISSUE TITLE
Add support for grouping timeline items

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#543]
**Is your feature request related to a problem? Please describe.**
Timeline items are all shown individually, which can make it hard to read large rooms for all the membership and profile changes.

**Describe the solution you'd like**
We should add a `GroupedRoomTimelineItem` type which uses a `DisclosureGroup` to hide any items within it summarised as
> x room changes.

Grouping should happen for consecutive state items with a special case for including date separators if both items before and after it are also state items.

[Figma design](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=6%3A11040&t=1aAtc1NkBwOJ4KTq-4)

This change likely requires using an `enum` instead of `RoomTimelineItemProtocol` to allow for the item to remain `Hashable` with an array of sub-items.

**Comment by stefanceriu** [comment]
Fixed in #601
