### ISSUE TITLE
SS reqs can take much longer from the client's perspective than the server's perspective

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#545]
The clientside of https://github.com/matrix-org/sliding-sync/issues/25

At FOSDEM, 90ms requests were taking 500ms from the client's side \(900ms during the recorded talk :\( \).

We need to tcpdump to see where the time goes, and then enable keepalives or switch to HTTP/3 or something

**Comment by manuroe** [comment]
SS is fast now.
