### ISSUE TITLE
Exclude the .github directory from PR checks like changelog, etc

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-x-ios#560]
When a PR fixes an issue with automation or issue templates, there is no need for a changelog entry, UI changes or to build the app. The directory should probably be excluded from these checks. I believe this is already the case either in the legacy Android or iOS repo

**Comment by stefanceriu** [comment]
Agreed that this is not worth the configuration effort or maintainance.
We can simply ignore the results or not open a PR to begin with. Please just point us (the app team) at a branch and we can do the rest.
