### ISSUE TITLE
FOSDEM implementation inconsistencies

### ISSUE THREAD

**Issue by callumu** [vector-im/element-x-ios#565]
1. Background colour - for full screen pages the background colour should be the lightest colour \(Compound/Light/Background\) and the opposite in dark mode. For modals, the background colour should be the next lightest colour \(Compound/Light/System Light\) and the opposite in dark mode. Currently there are inconsistencies on the settings and room settings pages across both themes - I’ve updated our new file to match this so you can use it as the source of truth.  This background colour should be the same across all pages and modals of the app - is it possible to set this as a rule instead of individually adjusting them?

Settings: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-\(new\)?node-id=5%3A7387
 Room settings: https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-\(new\)?node-id=5%3A7388

Room list header - this should have the same opacity as the All Chats header if possible?

[Room settings page](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=5%3A7388\) - we are missing the Matrix ID and Topic from the implementation. I think Gil worked to add these, so I’m not sure why they’re not in there. Could you add them? There are also some changes needed for text weight and size of the ‘Topic’, ‘About’ and ‘Security’ headers. Again, the file is accurate and the source of truth for these.

**Comment by pixlwave** [comment]
1. Is closed by #573.
2. Separate issue #574.
3. Headers fixed, missing topic/alias are because we don't have the data from [Rust](https://github.com/matrix-org/matrix-rust-sdk/issues/1493).
