### ISSUE TITLE
Roadmap link in readme is broken

### ISSUE THREAD

**Issue by RayBB** [vector-im/element-x-ios#572]
### Steps to reproduce

See readmehere https://github.com/vector-im/element-x-ios/blob/7ab64d4cb4324c82ee93e6520cc8f112be22dc78/README.md?plain=1#L26

Links to this 404 page: https://github.com/orgs/vector-im/projects/43/views/23

#### What did you expect?
Link to actual roadmap

#### What happened instead?
404

### Will you send logs?

No

**Comment by stefanceriu** [comment]
Following an internal decision our roadmap is no longer public.
