### ISSUE TITLE
Support for Right to left like Arabic languages

### ISSUE THREAD

**Issue by toshanmugaraj** [vector-im/element-x-ios#59]
It would be nice to have support for RTL in element x.

**Comment by stefanceriu** [comment]
Thank you for raising a ticket for this. We're building most of the things with SwiftUI and that takes care of everything for us. We still need to work on our translations but here's a sneak peek:

![Screenshot 2022-06-30 at 12 34 46](https://user-images.githubusercontent.com/637564/176645675-ea5225c7-5070-47d2-8911-fb23da66248f.png)

**Comment by naim94a** [comment]
RTL text’s direction is LTR, in the below screenshot the question mark should be the leftmost character.

![Image](https://github.com/user-attachments/assets/12d56458-625a-4a09-aec2-b5878f14cccd)

iOS: 18.3.1
Element X iOS Version: “25.02.0 (145)”
