### ISSUE TITLE
When specifying a custom server, you cannot specify a URL in the box asking for a URL.

### ISSUE THREAD

**Issue by michaelkaye** [vector-im/element-x-ios#591]
### Steps to reproduce

Failure:

1. Click "onboarding_continue",
2. Click "login-change_server"
3. Click "change_server-server" and type "https://servername.lab.element.dev" (a valid URL for the C-S api of a server supporting sliding sync)
4. View the error that pops up.

(see https://app-automate.browserstack.com/builds/dcae7ff645884422490a3364caba2a41e49ad691/sessions/ec5788bc713cbfa8557d499462b3ff682da79c60?auth_token=5358d1fe6203c9ae3dc1ecb7577521c5b0854faaf4ef33c31bc3f8f0dee3af3a )

Success:
1. Click "onboarding_continue",
2. Click "login-change_server"
3. Click "change_server-server" and type "servername.lab.element.dev" (which is not a URL, but refers to the same server)
4. Configuration goes through.

https://app-automate.browserstack.com/builds/dcae7ff645884422490a3364caba2a41e49ad691/sessions/41a27c260d6917f1b0e12bda3a7c22abbd33f031?auth_token=653356e0473297d47bf32b3f0db4b372a17684ca95b397ec7f431f1636297753

### Outcome

I believe we should support urls and variations on them in this box, to better support user actions; matching the label. People are likely to type:
```
http://server.com
https://server.com
http://server.com/
https://server.com/
server.com
server.com:8443
https://server.com:8443/
```
etc etc..

and the app should handle and normalise them correctly.

Additionally, we should provide better debugging of the failure in the device logs to identify why a given server failed:
 - Is the URL inherently inaccessable, if so, be explicit in the logs which URL is being accessed when reporting a failure.
 - Is it a valid matrix server at all?
 - Does it additionally support the discovery and similar endpoints for sliding sync to be enabled?
 
 Currently the logs simply say:
 ```
 Feb 17 10:57:43 ElementX(Foundation)[28193] <Notice>: AuthenticationServiceProxy.configure():57 User entered a homeserver that isn't configured for sliding sync.
Feb 17 10:57:43 ElementX(Foundation)[28193] <Notice>: ServerSelectionCoordinator.useHomeserver():93 Invalid homeserver: https://slydingsinc.lab.element.dev
```

I'm assuming the failure is because it's trying to contact `https://https://slydingsinc.lab.element.dev/` or maybe do a DNS resolution or something.

### Will you send logs?

Yes

**Comment by pixlwave** [comment]
Adding some context on why this currently behaves this way. The Rust client builder has 2 options:
- A homeserver - The URL for a homeserver e.g. https://matrix.company.com
- A server name - The part of a Matrix ID that comes after the `:` e.g. company.com
A server name can't start with `http(s)://` and a homeserver must be a valid URL with a scheme.

When the URL is supplied to the SDK, it checks for a scheme and chooses which builder option to use:
https://github.com/matrix-org/matrix-rust-sdk/blob/b96532878b52744d995b041385f4265fbcf0032d/bindings/matrix-sdk-ffi/src/authentication_service.rs#L118-L122

> I'm assuming the failure is because it's trying to contact https://https://slydingsinc.lab.element.dev/ or maybe do a DNS resolution or something.

Now the bug: When building a client with a homeserver URL the SDK doesn't perform any .well-known lookup, it is simply built to use the URL specified and continues on its merry way. However this means the [check](https://github.com/matrix-org/matrix-rust-sdk/blob/b96532878b52744d995b041385f4265fbcf0032d/bindings/matrix-sdk-ffi/src/authentication_service.rs#L127-L128) I added recently to enforce the use of a server with sliding sync will fail unless EX was built with an override.

> Additionally, we should provide better debugging of the failure in the device logs to identify why a given server failed:

I think this is actually fine in all other cases e.g. entering `google.com` will tell the user (and log) that it isn't a valid server and entering `idontexist.com` will do the same saying a server couldn't be found.

I guess the right thing to do here would be to strip the scheme and try build without it, then if that fails, attempt again with the scheme.

**Comment by pixlwave** [comment]
@michaelkaye This is now fixed in the SDK but won't appear in the app until we make the next SDK release for Swift.
