### ISSUE TITLE
timeline gets stuck blank, then wedges, then unwedges when you send a message after ss expiration

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#615]
### Steps to reproduce

1. Use a big account (maybe? it's 100% repro for Matthew, but may not be related to large accounts)
2. View a given room
3. Bg the app and wait for SS to expire
4. Fg the app, observe the room goes blank and doesn't refresh its timeline
5. Switch to roomlist and back again, observe that the old content of the room from step 2 is shown.
6. Send a message in the room, observe that the room contents suddenly updates.

#### What did you expect?

Consistent room history

### Application version

10.21 (135) nightly

### Will you send logs?

Yes

**Comment by ara4n** [comment]
current working theory is that we're dropping the subscription for the room somehow and not reestablishing it.

this is 100% repro for me.

**Comment by stefanceriu** [comment]
Fixed in #618 and #628
