### ISSUE TITLE
Keyboard missing after viewing video in timeline

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#622]
* open keyboard in timeline
* click on video to view it
* hit back
* observe ugly broken timeline with no keyboard present

![image](https://user-images.githubusercontent.com/1294269/221045164-d7cd98aa-3a9e-4f19-9cfe-cdc350bd6efc.png)

this on 1.0.21 (137) nightly

**Comment by stefanceriu** [comment]
This one was fixed a long time ago when we switched the presentation mode for the QLPreviewController
