### ISSUE TITLE
Room changes expand / collapse padding issues

### ISSUE THREAD

**Issue by callumu** [vector-im/element-x-ios#631]
### Steps to reproduce

The padding between the room changes collapsed UI doesn't match the designs - it should be 24px between the room changes message and the nearest message bubbles.

The tappable area is also too small - can this be increased vertically and horizontally?

### Outcome

<img width="797" alt="Screenshot 2023-02-24 at 15 05 19" src="https://user-images.githubusercontent.com/110109933/221212204-568eb3b9-9468-4d90-8dd4-2cf5e1c58773.png">

### Will you send logs?

Yes

**Comment by ara4n** [comment]
are we sure about saying "N room changes" rather than summarising the changes? ("Matthew and 5 others joined") etc

**Comment by callumu** [comment]
We decided on this for now as it's the simplest solution, but we will work on improving this in the future to something clearer and less cryptic

**Comment by VolkerJunginger** [comment]
Future development starts here https://github.com/vector-im/internal-planning/issues/369

**Comment by stefanceriu** [comment]
Fixed in https://github.com/vector-im/element-x-ios/pull/646
