### ISSUE TITLE
All rooms list doesn’t seem to expand any more, meaning search the room list doesn’t work

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#636]
### Steps to reproduce

1. Search for a room which you haven’t seen in your roomlist yet this session
2. observe that the room doesn’t appear
3. scroll through the room list
5. try again; observe that it now appears

#### What did you expect?

room list filtering to work.

#### What happened instead?

missing entries

### Application version

1.0.23 (42)

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
I looked through the logs but everything seems correct: the all rooms ranges are growing as expected and the sliding sync position is correct. I can't reproduce the problem locally.

 The only thing I could think about is how the Rust side GrowingFullSync doesn't respect the maximum number of rooms and somethings asks for a larger range, which I fixed [here](https://github.com/matrix-org/matrix-rust-sdk/pull/1590). 
I don't think this will actually fix the problem but it definitely can't hurt.
