### ISSUE TITLE
Date separators get confused by UISIs

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#638]
### Steps to reproduce

1. Receive a UISI after a message at 2am
2. Note that the next message after the UISI comes with a date separator, despite being sent the same day.

![27D604F5-D500-48DF-B750-2941A5373A08](https://user-images.githubusercontent.com/1294269/221350982-cdc75f9c-8d61-45af-b9d6-8b73e49c4be3.png)

#### What did you expect?

date separators only occur on day boundaries

### Application version

1.0.23 (42)

### Will you send logs?

No

**Comment by kittykat** [comment]
@ara4n Have you seen this issue recently?

**Comment by ara4n** [comment]
nope, but that’s probably because i almost never get uisis on EX. i strongly suspect it’s still open as a bug unless it’s been explicitly fixed.

**Comment by stefanceriu** [comment]
Closing in favor of https://github.com/vector-im/element-x-ios/issues/1763 and https://github.com/vector-im/element-x-ios/issues/1839
