### ISSUE TITLE
History is going misordered or missing entirely

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#640]
### Steps to reproduce

1. saw some push go by via EI
2. went to read them in EIX
3. they were not there
4. sent a test msg to see if that would unstick something
5. it didn’t.

#### What did you expect?

never ever to drop msgs.

### Application version

1.0.23 (42)

### Will you send logs?

Yes

**Comment by ara4n** [comment]
Pretty sure this is due to a regression such that SS expiration no longer causing timelines to get invalidated. We need regression tests for this...

**Comment by ara4n** [comment]
actually, it may not be a regression: the app works fine if SS expires when the app is bg'd while viewing a timeline.  However, if it's bg'd while viewing the actual roomlist it looks like we don't expire the timelines of the rooms which experience a gap due to the SS expiration, maybe?

**Comment by ara4n** [comment]
if there isn't a `if (ss_expires) { reset all timelines }` somewhere, then that'll be this bug.

**Comment by stefanceriu** [comment]
I am able to reproduce session expirations using a local sliding sync proxy instance but both the room list and timelines update accordingly after that happens. Looking through the logs the only thing that jumped out was that we are seeing a quick succession of room subscribe + unsubscribe calls.

That's not something I can reproduce locally but I did find one problem with unsubscribes being called more than once which I fixed [here](https://github.com/vector-im/element-x-ios/pull/650/commits/4ae3b3b2dba033d560fe5321686635c96bd53f95) and then again [here](https://github.com/vector-im/element-x-ios/pull/656)

I'm not expecting this to fix the problem but it's worth a shot. Otherwise we should probably delay investigating this until we have structured logging

**Comment by pixlwave** [comment]
I think I’m seeing this on my side, or at least a variant of it:
- I background the app.
- A not insignificant amount of messages come into the room.
- Come back to it some time later.
- I come back to the room.

At this point I see:
a. The latest say 10 or messages.
b. Then whatever was already loaded in the timeline above them.
c. Then if I keep scrolling, I see the rest of the messages that I missed.
d. Then the timeline continues with the messages that come before b.

note: whilst writing this I realise my ss proxy is a version or 2 behind, I’ll update it and see if that changes anything.

**Comment by ara4n** [comment]
i just saw this with the same symptoms as @pixlwave - it's possible this has been out-of-order msgs all along

**Comment by stefanceriu** [comment]
Wrote Rust side integration tests [here](https://github.com/matrix-org/matrix-rust-sdk/tree/stefan/timeline-ordering-integration-test) but no matter what I tried I couldn't get it to completely break. What I did found is that sometimes, in between sliding sync requests, the message order is incorrect. They do get fixed as soon as the loop runs again. Not entirely sure where this leaves us but we should at least try to understand why it's inconsistent

**Comment by ara4n** [comment]
I just had a different variant of this in https://github.com/vector-im/element-x-ios-rageshakes/issues/223 - specifically, i opened the room, was reading the timeline, when suddenly the message i was reading from patrick suddenly vanished. i then had to scroll up a few pages and found it lost there. In other words, the timeline reordered from under me while it was loading. Dunno if this helps with the hunt at all...

**Comment by manuroe** [comment]
Should be fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/1709.
Let's reopen the issue after more tests on the coming TestFlight.

**Comment by manuroe** [comment]
There is a reproducible bug related to this described [here](https://github.com/matrix-org/matrix-rust-sdk/issues/1742)

**Comment by manuroe** [comment]
The last rageshake has steps to reproduce:

- load room
- stare at stale history for a bit (gah, no indication that it’s stale still)
- see the recent messages pop up in the right order (i think)
- go back to the room list
- go back into the room and see that only the first msg of the batch which was pending is now shown; the rest are buried precisely 20 messages earlier than they should be

**Comment by manuroe** [comment]
We can close it. The last problem we have related to this issue is described in #809 and just got fixed.

**Comment by ara4n** [comment]
i don't understand why this is closed; it's happening as much as it ever did - e.g. this from May 3rd:

![image](https://user-images.githubusercontent.com/1294269/236626012-6896afe4-3906-4eae-88c9-3c49f635c9f1.png)
