### ISSUE TITLE
MELS is too cryptic

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#642]
### Steps to reproduce

1. View a room with a lot of membership changes
2. Observe that they are collapsed to “1 change” if only one change happened in a given day amidst a series of changes:

![86E026FA-23A8-4930-B964-8210916CE527](https://user-images.githubusercontent.com/1294269/221355805-32685681-01e0-40c6-9f5b-d5845ba3c9f4.jpeg)

3. feel frustrated that the summaries don’t tell you more.

#### What did you expect?

Useful membership change sunmaries. If it’s a single event, it shouldn’t be collapsed at all. If it’s multiple events, it should be labelled something like “Matthew and 5 others joined; 3 left”

#### What happened instead?

“1 room changes”

### Application version

1.0.23 (42)

### Will you send logs?

No

**Comment by VolkerJunginger** [comment]
Thank for pointing that out. I created an epic for the team to discover and implement a more transparent solution https://github.com/vector-im/internal-planning/issues/369
