### ISSUE TITLE
On fresh launch, messages didn't load in a room until I sent a message.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#643]
### Steps to reproduce

1. Launched app
2. Opened a room from room list
3. Saw stale history
4. Assumed that it was #640 
5. Sent a message
6. Saw the missing history immediately appear (unlike #640, where the missing msgs were lost forever).

It looks like a variation failing to handle SS expiration correctly? or a variation on the subscription bug? (In which case, it feels like subscribing to rooms is way too racey and needs to be rethought...)

#### What did you expect?

App shows accurate history.

### Application version

1.0.23 (42)

### Will you send logs?

Yes

**Comment by ara4n** [comment]
just had this again

**Comment by manuroe** [comment]
It has been fixed
