### ISSUE TITLE
DMs don't show the avatar of the other member.

### ISSUE THREAD

**Issue by pixlwave** [vector-im/element-x-ios#657]
### Steps to reproduce

1. Start on the home screen.
2. Scroll down to a room that is a DM with someone else.

#### What did you expect?
That the room's icon, both on the home screen and the room screen's toolbar is the other user's avatar.

#### What happened instead?
The room's icon is the first letter of the room name.

This has been discussed before and ideal should be sent in the Sliding Sync response at the same point that it computes the room's name.

### Your phone model

iPhone 14

### Operating system version

iOS 16.3

### Application version

1.0.23 TF

### Will you send logs?

No

**Comment by VolkerJunginger** [comment]
Now a duplicate. I created user-stories for rooms & roomlist.
