### ISSUE TITLE
We no longer highlight the msg being replied to when you reply

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#666]
### Steps to reproduce

1. reply to a msg
2. note that the other bubbles are no longer greyed out while you are replying

i’m sure this used to work; it looks to be a regression

#### What did you expect?
 
to be able to see what i’m replying to

### Application version

public TF

### Will you send logs?

No

**Comment by stefanceriu** [comment]
This is not a bug, it was decided by the design team in https://github.com/vector-im/element-x-ios/issues/542#issuecomment-1437379073
