### ISSUE TITLE
Push notifications don't work

### ISSUE THREAD

**Issue by Zamrod** [vector-im/element-x-ios#674]
I'm not sure this issue is directly related to the iOS version.
I do not get push notifications on either my Android phone nor my iPad when new chat messages come in. I do get notifications on the Windows application though. The Windows application is where I first signed up for an account so I don't know if that's related.

When I run the notification tests on the Android it succeeds and I get a notification. However, any real message doesn't come through on either device.

**Comment by kittykat** [comment]
Hi, thank you for opening an issue. The push notifications are not implemented yet, you can track the high level stories [here](https://github.com/vector-im/element-meta/issues?q=is%3Aissue+is%3Aopen+label%3A%22App%3A+ElementX+iOS%22+label%3A%22A-Notifications%22).

We are in very early stages with Element X at this time and there are still many points to implement. You can have a look at some of the user stories [here](https://github.com/vector-im/element-meta/issues?q=is%3Aissue+is%3Aopen+label%3A%22App%3A+ElementX+iOS%22), and more are being added as we go along!

I'm going to close this issue for now as the work is already planned. It would be great if you can use the bug form for defects in the future
