### ISSUE TITLE
Messages sent while on bad connectivity can be entirely lost.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#675]
### Steps to reproduce

1. Sent a message whilst on bad connectivity.
2. Wait for encryption to do its thing
3. Lose connectivity entirely before the message has sent
4. See a (!) logo on the message
5. Go to the roomlist and back into the room
6. Watch as the message flickers and disappears forever.

#### What did you expect?

Even if we don't queue msgs to be sent yet, i'd expect unsent messages never to be lost.

#### What happened instead?

My messages got lost.

### Application version

1.0.23 (42)

### Will you send logs?

No

**Comment by pixlwave** [comment]
Duplicate of #517.
