### ISSUE TITLE
App browsing whilst offline

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-x-ios#676]
**Is your feature request related to a problem? Please describe.**

I want to be able to cold start ElementX when i'm on airplane mode

**Describe the solution you'd like**

To be able to browse the current known rooms and view known history in those rooms 

**Describe alternatives you've considered**

N/A

**Additional context**

Nothing is currently shown, only the room list loading placeholder

**Comment by VolkerJunginger** [comment]
Thanks for the report. We will cover this with https://github.com/vector-im/element-meta/issues/1101
