### ISSUE TITLE
Odd chevron animation when entering a room

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-x-ios#678]
### Steps to reproduce

1. Enter a room

#### What did you expect?

No motion for the chevron on the room header

#### What happened instead?

https://user-images.githubusercontent.com/769871/223188945-eda036d8-394e-41b4-93e2-285d09419731.mov

### Your phone model

iPhone 13

### Operating system version

iOS 16.4

### Application version

1.0.24 (145)

### Will you send logs?

Yes

**Comment by VolkerJunginger** [comment]
As iOS16.4 is not official yet I would close this issue for now.
