### ISSUE TITLE
Don't block initial sync on to-device messages.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#681]
### Steps to reproduce

https://github.com/matrix-org/matrix-rust-sdk/pull/1616 forces to-device messages on constantly.

As a result, if you don't use the app for a few hours (e.g. overnight), then on a busy account hundreds of to-device messages could easily stack up as new megolm sessions get shared with you; new olm sessions get set up; etc.

Previously, we would download these in a second /sync req [edit: apparently this was never actually implemented?], ensuring the first one returns as rapidly as possible (meaning the user isn't stuck looking at a spinner; instead we show them which rooms are active, including previews for unencrypted rooms, and then encrypted content would get resolved shortly afterwards once the second /sync returned).  However, in practice, the implementation of this proved fiddly, with the to-device extension getting stuck off, breaking e2ee until the next launch, hence implementing a workaround.

This bug exists to remind us to remove the workaround and fix it properly, so that launch continues to be instant, no matter how long the app has been offline - rather than staring at a spinner waiting for a to-device backlog before the roomlist is usable.  The proposed fix is to split consuming to-device msgs into a separate /sync loop (which then means that e2ee state can all be managed one place without getting entangled or blocking the SS loop used for scrolling around the app and receiving room msgs).

#### What did you expect?

Instant launch, no matter how long it's been since you last launched the app.

#### What happened instead?

The longer you've been offline, the longer you'll be shown stale content on launch.

**Comment by manuroe** [comment]
Should be fixed now.
