### ISSUE TITLE
URLs with `#` in them get altered when clicked

### ISSUE THREAD

**Issue by cor** [vector-im/element-x-ios#687]
### Steps to reproduce

1. Where are you starting? What can you see?

Someone sent me a link with a `#` in it, for example: `https://example.com/#/`

2. What do you click?

I clicked `https://example.com/#/`

#### What did you expect?

`https://example.com/#/` to open in my browser, Chrome.

#### What happened instead?

`https://example.com/%23/` got opened in my browser instead.

### Your phone model

MacBook Pro 14" M1

### Operating system version

macOS 13.2.1

### Application version

ElementX Version 1.0.23 (42)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by habi** [comment]
I also see this with Element-X 1.0.23 (42) on iOS 16.3.

Most recently in the link posted at https://matrix.to/#/!CCRKncVOQamqtSzFBm%3Amatrix.org/%24167842337884849uwgfk%3Amatrix.org

**Comment by ara4n** [comment]
(This is still there in build 181 and biting badly)
