### ISSUE TITLE
Scroll to bottom button not shown after expanding state event group

### ISSUE THREAD

**Issue by germain-gg** [vector-im/element-x-ios#694]
### Steps to reproduce

1. Go to a room where the last event is a group of state events (profile picture and display name updates)
2. Click on it to expand

#### What did you expect?

I would expect the "scroll to bottom" button to be displayed as we are not scrolled to the bottom of the timeline anymore

#### What happened instead?

The button is not displayed. Although, as soon as I scroll the timeline by 1 pixel, the button gets displayed

### Will you send logs?

No

**Comment by kittykat** [comment]
I feel like the timeline should possibly scroll up so you stay at the most recent message… tagging design

**Comment by amshakal** [comment]
I mean we wanted to scroll to the bottom of the state events when expanded but sadly thats not technically possible. So yes, showing that 'scroll to the bottom' button should show up instantly.

**Comment by stefanceriu** [comment]
This stopped being a problem after we flipped the timeline scroll view
