### ISSUE TITLE
If you send a msg while room history is loading, it doesn’t echo

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#698]
### Steps to reproduce

1. View a room
2. While the timeline is loading, send a msg (slow the network if needed)
3. Note the echo for the msg doesn’t appear

#### What did you expect?

reliable echo.

### Application version

1.0.25 (153)

### Will you send logs?

No

**Comment by kittykat** [comment]
@ara4n Can you still reproduce this issue?

**Comment by ara4n** [comment]
nope.
