### ISSUE TITLE
Room list content when search selected

### ISSUE THREAD

**Issue by callumu** [vector-im/element-x-ios#715]
### Steps to reproduce

Selecting the search bar

![ima_c2f2ced](https://user-images.githubusercontent.com/110109933/226669661-62942736-5b59-4077-9574-80dc212efef3.png)

### Outcome

The content jerks up the page and sits below the search bar.

A better interaction would be for all the content below the search bar on the room list to be hidden when the search bar is selected

### Will you send logs?

No

**Comment by manuroe** [comment]
It is now implemented in 1.1.8 and before.
