### ISSUE TITLE
Unexpected behaviour when moving from the timeline to the room list

### ISSUE THREAD

**Issue by callumu** [vector-im/element-x-ios#722]
### Steps to reproduce

https://user-images.githubusercontent.com/110109933/226952448-44f9be82-6759-47b9-aae5-091f3920de8f.mp4

### Outcome

When moving from the timeline to the room list, I would expect the header (including the room avatar and name), to move to the right alongside the rest of the timeline content.

This is associated with issue #574

### Will you send logs?

Yes

**Comment by manuroe** [comment]
Tested on 1.1.8. The room header move with the room timeline.
