### ISSUE TITLE
room previews don’t tell you who sent a message

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#731]
### Steps to reproduce

1. look at the room list
2. admire the room previews
3. feel frustrated that you don’t have a way of knowing who sent which msg, short of tapping into the room

#### What did you expect?

room previews should show you who spoke in a room

#### What happened instead?

they have no sender

### Application version

latest tf

### Will you send logs?

No

**Comment by manuroe** [comment]
Dup of https://github.com/vector-im/element-x-ios/issues/1204 which sees a little improvement.
