### ISSUE TITLE
timeline doesn’t relayout after the keyboard shrinks after selecting an emoji

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#735]
### Steps to reproduce

1. view a room
2. select an emoji in the keyboard and send it as a message
3. see keyboard shrinks back to normal size
4. …but the timeline doesn’t adjust, so you end up with a big hole at the bottom if the timeline

#### What did you expect?

bottom of the timeline tracks the top of the keyboard

#### What happened instead?

big ugly gap

### Your phone model

iphone 12 pro max

### Operating system version

16.3.1

### Application version

latest tf

### Homeserver

m.org

### Will you send logs?

No

**Comment by manuroe** [comment]
Cannot reproduce it on 1.1.8.
