### ISSUE TITLE
Room list sometimes does not load

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#743]
After starting the app (after a nightly update for example), only first rooms in the room list are displayed (We have a report with no room loaded at all). Only black cells are displayed for the rest of list.

See screenshots in the rageshakes.

Bug seen in 1.0.25 builds 160, 165, 166.

build 160 correspond to bindings [1.0.48-alpha](https://github.com/matrix-org/matrix-rust-components-swift/releases/tag/v1.0.48-alpha) and SDK [commit](https://github.com/matrix-org/matrix-rust-sdk/tree/f70b6f5ecf3439dd522548ef30edf167ed330163).

Note https://github.com/matrix-org/matrix-rust-sdk/pull/1699 may already address part of it.

**Comment by Hywan** [comment]
Is it solved?

**Comment by stefanceriu** [comment]
Seems so, yes, but today is pretty quiet so let's give it some time before we close the issue

**Comment by manuroe** [comment]
We have a less frequent problem now (#796) but this bug is gone.
