### ISSUE TITLE
Sync sometimes got stuck

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#757]
This bug seems to appear in EIX 1.1.0 (168).

When debackgrounding the app, the room list and the timeline do not refresh. Restarting seems to fix the problem.

**Comment by manuroe** [comment]
The 2 rageshakes have a common warning:
```
WARN matrix_sdk_ffi::client: Ignoring sync error: Http(Api(Deserialization(Json(Error("identifier contains invalid characters", line: 1, column: 14417)))))
```

**Comment by stefanceriu** [comment]
Duplicates #761
