### ISSUE TITLE
Move search users into a dedicated service

### ISSUE THREAD

**Issue by flescio** [vector-im/element-x-ios#767]
- [x] Move the search from the current StartChat ViewModel into a separate Service that will expose the search 
- [x] Unit Test the service
- [x] adding the search also in the invite screen
- [x] put suggestions under feature flag in invite view model

**Comment by Johennes** [comment]
@flescio this needs to either be tracked somewhere under the [epic](https://github.com/vector-im/element-meta/issues/988) or have it's epic field set correctly in the right panel. Otherwise, it's not going to be counted towards our [CFD](https://github.com/orgs/vector-im/projects/73/insights/7).
