### ISSUE TITLE
React on message with emojis

### ISSUE THREAD

**Issue by flescio** [vector-im/element-x-ios#782]
### Your use case

- [x] - Change the contextual menu into a bottom sheet menu
- [x] - Adding a row at the top of the bottom sheet menu for emoji reactions
- [x] - A default set of reactions is presented, at the end of the list there is a "show more emoji" button
- [x] - If the "add more emoji" button is pressed the user can pick out of a standard set of emoji

### Default set
`["👍", "👎", "😄", "🎉", "😕", "❤️", "🚀", "👀"]`

### Design
- [Figma](https://www.figma.com/file/0MMNu7cTOzLOlWb7ctTkv3/Element-X-(new)?node-id=2053-103726&t=VXjtbRUhiNZlaxsI-4)

**Comment by langleyd** [comment]
https://github.com/vector-im/element-x-ios/pull/1046
