### ISSUE TITLE
STATE_ERROR_VALIDATION_ERROR for ID

### ISSUE THREAD

**Issue by ridcridc1** [vector-im/element-x-ios#80]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ridcridc1** [comment]
STATE_ERROR_VALIDATION_ERROR for ID when upload archive to apple store with xcode

**Comment by ridcridc1** [comment]
any help please

**Comment by manuroe** [comment]
We cannot help with no more description.
