### ISSUE TITLE
Nightly builds on Xcode cloud

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#81]
We want to automate the release of develop builds so that we can have feedbacks sooner a la develop.element.io.
- [ ] Requires #131

**Comment by ismailgulek** [comment]
Creating the first workflow fails with a generic error message. After some investigation i've found this in the Xcode cloud docs:

`
When you first configure your project or workspace to use Xcode Cloud, you need to allow Xcode Cloud to access your Git repository. It uses this access to automatically build and test your code when you make changes to the codebase.
If you host your code as part of a GitHub organization, the person who first configures a project to use Xcode Cloud must be an organization owner.
`

Full docs: https://developer.apple.com/documentation/xcode/connecting-xcode-cloud-to-github-enterprise

@ara4n can we have your support on ^? All you need to do is creating the first workflow for us with default actions (as in https://developer.apple.com/documentation/xcode/configuring-your-first-xcode-cloud-workflow) and then we'll be able to alter it hopefully.
