### ISSUE TITLE
[Question] Is dendrite already supported? Login error

### ISSUE THREAD

**Issue by traktuner** [vector-im/element-x-ios#845]
### Steps to reproduce

Hello,
I wanted to ask if dendrite is already supported with Element X?

### Outcome

When I want to connect to my synapse homeserver, I get an expected error because sliding-sync is not enabled.
When pointing to my dendrite homeserver, I just get "Cannot reach homeserver at this URL, please check it"
(It is working with the current version of Element for iOS)

Error in nginx:
x.x.x.x - - [29/Apr/2023:10:32:47 +0200] "GET /.well-known/matrix/client HTTP/1.1" 200 133 "-" "matrix-rust-sdk" "x.x.x.x, x.x.x.x"

Element X logs can not be sent since the "shake" gesture does not work.

### Your phone model

iPhone 14 Pro Max

### Operating system version

iOS 16.4.1

### Application version

Element X 1.0.24

### Homeserver

Dendrite 0.12.0

### Will you send logs?

No

**Comment by pixlwave** [comment]
It sounds like you don't have a client well-known file defined for your dendrite server. This is currently a requirement for Element X to be able to discover information about sliding sync availability (and in the future authentication too).

As to your question, Dendrite doesn't have sliding sync built in either. To use Element X whilst sliding sync is in developement you will need to [configure](https://github.com/matrix-org/sliding-sync/blob/main/docs/Landing.md) a sliding sync proxy.
