### ISSUE TITLE
Membership list shows parted users

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#867]
### Steps to reproduce

1. Go to a room with parted users
2. View the member list
3. Observe weird blank entries for users who have parted the room.

![IMG_0038](https://user-images.githubusercontent.com/1294269/236916832-e3653306-f706-4ef7-8592-53bf48c2dd44.png)

#### What did you expect?

parted users should not be shown in the memberlist; only invited and joined users

### Application version

nightly 200

### Will you send logs?

No

**Comment by kittykat** [comment]
@ara4n Are you still seeing this issue? (Note that membership list doesn't work in large rooms right now)

**Comment by kittykat** [comment]
I'm going to close this issue for now as we can't reproduce it and haven't seen it in a while, please reopen if you're still seeing it.
