### ISSUE TITLE
Ability to send or receive msgs in encrypted rooms is getting completely stuck - either globally or per room.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#875]
### Steps to reproduce

On nightly build 206 (and 202) you can end up unable to decrypt new messages, receive new messages, or send new messages (which either hang in local echo, or crash out with a ⚠).

In one instance, this affected all rooms, including across restarts, until something unblocked (perhaps the SS session expired?)

#### What did you expect?

Ability to send/receive msgs.

### Application version

nightly 206

### Will you send logs?

Yes

**Comment by ara4n** [comment]
Stefan says:

> not sure what's happening here on rageshake 311, it's doing a ton of crypto stuff and eventually getting a bunch of

`2023-05-10T08:48:04.904448Z  WARN root: matrix_sdk_crypto::identities::manager: crates/matrix-sdk-crypto/src/identities/manager.rs:308: Device keys failed to deserialize user_id="@affbw2qgwkwbg5ov7wyiov4ilfxsva7vcqzjcuewyy2m74anoo7ai===:chat.teamspeak.com" device_id="BQKBFMRGPE" error=Error("required colon is missing", line: 1, column: 472)`

otherwise apparently

```
2023-05-10T08:48:46.462246Z  INFO root: elementx: RoomTimelineController.swift:139: Send message in !kCCQTCfnABLKGGvQjo:matrix.org
2023-05-10T08:48:46.488151Z  INFO root: elementx: RoomTimelineController.swift:146: Finished sending message
```

...except it doesn't send.

> this whole business of it unwedging after a while feels to me like an "initial sync" for the crypto side. In rageshake 315 console.1.log it's still was doing a ton of root:latest_event:retry_event_decryption and then in console.log it calmed down.

rageshake 315 is the unwedge from 311

**Comment by manuroe** [comment]
Did not reoccured. The code has changed a lot underneath
