### ISSUE TITLE
"Clear cache" is super slow and leaves app with very broken timeline ordering

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#884]
### Steps to reproduce

1. hit the clear cache button
2. stare at the splash screen for 30s
3. observe that the roomlist shows you cached data from the last time you viewed the roomlist
4. view a room, and see completely broken ordering of messages.

#### What did you expect?

I'd expect clear cache to be instant, as it's throwing away all your local data, and then restarting SS which should surely be super fast.  It shouldn't have any other data to act on, so why would it spend 30s doing anything?

Restarting the app fixed the ordering issue.

#### What happened instead?

It feels like it didn't actually clear the cache, or perhaps left one hanging around in RAM.

### Application version

nightly 206

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
@Hywan By popular demand we introduced a clear cache button on the nightly builds. This goes and deletes the `matrix-sdk-state` folder from within your session's folder and then soft restarts the app, recreating your session, the client, sliding sync etc.

Any chance there's some sort of static cache somewhere that doesn't get cleaned up when this happens?
