### ISSUE TITLE
Opening videos doesn’t deduplicate taps

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#901]
### Steps to reproduce

1. View a video in an e2ee room by tapping its thumbnail
2. Nothing happens; you wonder if the tap worked
3. you tap a few more times
4. suddenly you get 4 copies of the video open up in the view stack

#### What did you expect?

duplicate taps should be deduplicated.

#### What happened instead?

videopalooza

### Application version

nightly 213

### Will you send logs?

No

**Comment by manuroe** [comment]
Cannot reproduce it. We have a spinner now.
