### ISSUE TITLE
Need a way to create a user account from the welcome screen

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#904]
After the welcome screen the user is presented with the sign-in screen. There should be a way for them to create a user account from this screen but there isn't currently.

Version tested: Element X iOS 1.1.0 (214) via Testflight
Device tested: iPhone 12 Mini with iOS 16.3.1

**Comment by manuroe** [comment]
It is expected. Account creation will come with the OIDC support.

https://github.com/vector-im/element-x-ios/issues/1225 has a list of what is currently supported in EIX.
