### ISSUE TITLE
Welcome screen and analytics opt-in presented on subsequent logins

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#906]
### Steps to reproduce

1. Start the Element X app and tap _Continue_ on the welcome screen.
2. Sign in and either accept or decline the analytics opt in.
3. Sign out and tap _Continue_ on the welcome screen again.
4. Sign in again and either accept or decline the analytics opt in again.
5. Repeat...

#### What did you expect?
A user should only be presented with the welcome screen once and returned to the login screen on sign out. They should also only be presented with the analytics opt-in screen once as they can change the setting through the user settings screen.

#### What happened instead?
The welcome screen and analytics opt-in are shown every time a user logs in.

### Your phone model

iPhone 12 mini

### Operating system version

iOS 16.3.1

### Application version

Element 1.1.0 (214)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by pixlwave** [comment]
This is working as designed.
- The welcome screen will eventually have 2 buttons, one for login and another for register.
- When implementing analytics, the [decision](https://github.com/vector-im/element-x-ios/pull/816) was made that this should be per session and not per device, which means that consent it reset on each sign out.
