### ISSUE TITLE
Unblocking a user doesn't restore messages until app reset

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#911]
### Steps to reproduce

1. Block a user
2. Go back to the room and see that their content is removed from view
3. Unblock the user
4. Go back to the room and see if their content has been restored

#### What did you expect?
The user's content should be restored when unblocked.

#### What happened instead?
The user's previous content is not restored, however any new content they add shows up. I have to quit the app (swipe up) and open the app again for the previous messages to be restored.

**Note:** The content area is just blank, these are not UTDs.

### Your phone model

iPhone 12 mini

### Operating system version

iOS 16.3.1

### Application version

Element 1.1.0 (214)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ashughes1** [comment]
I retested this on Element X iOS 1.1.8 (271) and it is still reproducing.

**Comment by Velin92** [comment]
Seems that the SDK is not refreshing the timeline anymore after the update, opening an issue on it.
https://github.com/matrix-org/matrix-rust-sdk/issues/2284
