### ISSUE TITLE
Tap your own solitary emoji reaction to remove it

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#912]
When you tap on an existing emoji reaction, the app registers the same reaction for you and increases the count by 1. Tapping it again unregisters your reaction and decreases the count by 1. If yours is the only reaction tapping on it should remove the reaction, as it does in the Element (legacy) app, but currently this does nothing (the reaction remains and the count sits at 1).

**Comment by manuroe** [comment]
Reaction removal has been added recently.
I am closing the issue. Reopen it you still meet this bug.

**Comment by ashughes1** [comment]
Confirmed working. Thanks.
