### ISSUE TITLE
Avatar for a DM use the default instead of the avatar of that user

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#917]
### Steps to reproduce

1. Start a DM with another user, note the room avatar
2. Tap on the room title to open the room details screen, note the avatar
3. Go back to the room timeline, note the avatar

#### What did you expect?
When in a DM the avatar should be that of the other user.

#### What happened instead?
The avatar is the default, in this case an "A" on a green background.

#### Screenshot of room avatar in the room timeline view
![Screenshot from 2023-05-17 08-31-23](https://github.com/vector-im/element-x-ios/assets/766595/78d28141-dca0-47de-aede-72bf99b86d76)

#### Screenshot of room avatar in the room details view
![IMG_3822](https://github.com/vector-im/element-x-ios/assets/766595/3c2d46e2-e560-4ec3-9379-e90143770b7a)

### Your phone model

iPhone 12 mini

### Operating system version

iOS 16.3.1

### Application version

Element 1.1.0 (214)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by manuroe** [comment]
SS proxy issue: https://github.com/matrix-org/sliding-sync/issues/166

**Comment by manuroe** [comment]
Fixed at least from nightly #311.
