### ISSUE TITLE
[ui bug] Transparent avatars show an awkward circle

### ISSUE THREAD

**Issue by ShadowJonathan** [vector-im/element-x-ios#923]
![image](https://github.com/vector-im/element-x-ios/assets/22740616/622210c3-94f6-40af-978d-c1f720b9f503)

Encountered this in the last TestFlight (1.1.0 47), in the bubbles layout.

The user in question is https://matrix.to/#/@ruma_mod:flipdot.org

**Comment by habi** [comment]
Maybe a tad related to https://github.com/vector-im/element-ios/issues/5595
