### ISSUE TITLE
Have more messages in cache 

### ISSUE THREAD

**Issue by manuroe** [vector-im/element-x-ios#93]
The room screen is empty when you open it and it stays empty for a long time.

We need to increase the `limit` value of the `/sync` request to have more messages in cache to improve the UX.

Element-iOS has an algo to determine this value according to the screen size. The idea is to have a full page of messages when you open a room. It is roughly 10 for iPhoneSE, 30 for iPads and 20 in between.
It depends a lot on the text density, which is quite light on ElementX right now.

As a quick start, we can use 20 so that we will be able to compare EX and EIX performance on a same amount of data

**Comment by stefanceriu** [comment]
This will need to be exposed through the SyncSettings here https://github.com/gnunicorn/matrix-rust-sdk/blob/main/crates/matrix-sdk/src/config/sync.rs#L23
