### ISSUE TITLE
Room Details view for Matrix.org HQ room thinks I'm the only user in the room

### ISSUE THREAD

**Issue by ashughes1** [vector-im/element-x-ios#933]
### Steps to reproduce

1. Log in to Element X iOS
2. Join the Matrix HQ room
3. Tap the room title to open the Room Details view
4. Note the number of users on the People button
5. Tap the People button and view the People list

#### What did you expect?
The user count on the People button should match the number of users in the room.
The People list view should show all of the users in the room.

#### What happened instead?
The user count is 1 and I am the only user listed in the People list.

### Your phone model

iPhone 12 mini

### Operating system version

iOS 16.3.1

### Application version

Element 1.1.0 (218)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by kittykat** [comment]
I can't reproduce this issue, @ashughes1 can you please verify with the latest version?

**Comment by ashughes1** [comment]
This is working as expected now with Element X 1.1.6 (257) on iPhone 12 mini.
