### ISSUE TITLE
Room previews load very slowly, if at all, as you scroll the room list

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#934]
### Steps to reproduce

1. scroll a few pages down the room list
2. observe that the room previews don’t load
3. wait for tens of seconds
4. observe some (but not all) load
5. scroll up a bit; see most of the room previews above have loaded

#### What did you expect?

visiblerooms should instantly load the previews as you scroll (with 1 msg of history), and precache 20 msg of history when scroll settles.

(This was working correctly around FOSDEM, so is a regression)

#### What happened instead?

It doesn’t look like the visiblerooms list is updating at all - looks like allrooms is being slowly expanded with previews or something?

### Application version

218

### Will you send logs?

Yes

**Comment by manuroe** [comment]
Should be fixed now.
