### ISSUE TITLE
We've lost offline support, and no longer cache the roomlist, so roomlist search doesn't work until AllRooms has reloaded.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#937]
### Steps to reproduce

1. Launch the app on bad/missing connectivity
2. Observe that the you see the shimmering empty roomlist rather than a usable room list.
3. Once the roomlist loads, observe that roomlist search doesn't work (until AllRooms has eventually paginated in all your rooms again, which could take tens of seconds on a large account - which is a problem, given immediately searching the room list on launching the app is a very common use case).
   * (a separate problem is that the roomlist search gives you no UI feedback to warn you it's incomplete while allrooms is populating)

This is because we backed out the cold cache in https://github.com/vector-im/element-x-ios/commit/abc86b7368aab69f65b0cee6d8399c443df8db9a given its performance with sqlite was particularly bad (as per https://github.com/vector-im/element-x-ios/issues/876).

However, we do need a cold cache of some kind so that offline support works, and so app launch isn't bottlenecked on talking to the server, which *should* be much slower than simply loading some data from local disk.  A better cold cache would presumably:

 * Be paginated, so access is O(1) with number of rooms, so the roomlist UI code will pull only the required page of rooms from cache needed to display the current visible rooms
 * Cache data precomputed for display in the roomlist (e.g. the current room preview, rather than figuring it out from scratch)
 * Only precache room history for these rooms on demand.

If it was me doing it, I'd be tempted to use the same API for SS as for the cache rather than having two different pagination/precaching mechanisms flying around - given the problem of "how do you efficiently load data O(1) from the server" is almost identical to the problem of "how do you efficiently load data O(1) from a local cache".

#### What did you expect?

Offline support and reliable roomlist search.

#### What happened instead?

No offline support, and roomlist search isn't reliable until allrooms has loaded.

### Application version

nightly 221

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by ara4n** [comment]
see also https://github.com/vector-im/element-x-ios/issues/1203

**Comment by stefanceriu** [comment]
Will be part of the next SDK release as per https://github.com/matrix-org/matrix-rust-sdk/pull/2386
