### ISSUE TITLE
Sometimes local echos appear duplicated alongside remote echos

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#939]
### Steps to reproduce

About 1 in 100 messages ends up with two echos - an unsent local one, and a remote one:

![IMG_0035](https://github.com/vector-im/element-x-ios/assets/1294269/5c8878a6-52a3-41ca-bf6b-e619ba45a3a5)

This looks to be a manifestation of https://github.com/matrix-org/sliding-sync/issues/3

#### What did you expect?

No duplicate echos

#### What happened instead?

Duplicate echos

### Application version

nightly 221

### Will you send logs?

No

**Comment by ara4n** [comment]
(it's unclear if this is a permanent duplication, or a temporary flicker - but eitherway, it sucks. it sounds like a related issue is that rust-sdk assumes that /send will always return before /sync returns, meaning you can deduplicate based on event ID, and don't need to do so based on txn IDs. This is obviously going to be prone to races where /send is delayed however, which might be what's happening here?

**Comment by jplatte** [comment]
Nonono, we absolutely do deduplicate based on txn ID, it's just that with Sliding Sync, it seems like there's never *any* txn IDs. Deduplicating based on event ID is just a fallback.

**Comment by ara4n** [comment]
right, this just happened to me again, and it is indeed permenant (until the timeline next gets refreshed at least). rageshaked.

**Comment by kegsay** [comment]
It should never be a permanent thing if the client is tracking events in that room. Transaction IDs should be included with events in the proxy if they are present upstream as per https://github.com/matrix-org/sliding-sync/blob/main/tests-integration/timeline_test.go#L579 - it would be worth having a sanity check e2e test though to be sure.

**Comment by kegsay** [comment]
<img width="856" alt="Screenshot 2023-05-25 at 11 41 54" src="https://github.com/vector-im/element-x-ios/assets/7190048/e6fd5157-4f83-4f10-8eac-bed85578c6e6">

Tests pass and I see this in the wild. That being said, it's often not there in large rooms with many shared users, which is what https://github.com/matrix-org/sliding-sync/issues/3 describes.
