### ISSUE TITLE
Timestamps in bubbles use unnecessary vertical screen realestste

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#95]
**Describe the bug**
Looking at the current demo screenshot of bubbles, we are wasting about 30% of the available vertical screen realestate on timestamps. Timestamps should only have their own line if there is not room to put them at the right hand side of the bubble - see Telegram for a great example of doing this.

**To Reproduce**

Observe that most of these  timestamps are needlessly on a new line when they could be put on the rhs of the last line of content in their respective bubbles:

![image](https://user-images.githubusercontent.com/1294269/175776801-f33bbb5f-133b-4100-8c18-43100b562c1f.jpeg)

**Expected behavior**

Moar vertical screen estate = being able to read moar msgs

**Comment by pixlwave** [comment]
My perspective on this would be to favour an option to hide the timestamps all together. For the personal messenger use-case, I'm rarely interested in the exact time a message came in. It would still need an interaction to reveal the timestamp for a specific message for those few times someone wanted to see it, but it would result in a less cluttered layout IMO.

**Comment by stefanceriu** [comment]
No longer relevant as per latest designs
