### ISSUE TITLE
scroll position should be always locked when scrolled up in a room

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#955]
### Steps to reproduce

1. go to a busy room
2. scroll up to read scrollback
3. some of the time, the scroll position jumps around as new msgs are appended to the timeline - sometimes it jumps to the bottom; sometimes it jumps down by a bubble’s height.

#### What did you expect?

scroll position should never jump around when scrolled up

### Application version

223

### Will you send logs?

No

**Comment by kittykat** [comment]
@ara4n Are you still seeing the issue? If you are, can you please attach a screen recording and a rageshake

**Comment by pixlwave** [comment]
Unable to reproduce on `develop`. A lot has changed in the timeline recently, so closing this issue as stale.
