### ISSUE TITLE
Emoji reactions to older messages in timeline show neither local or remote echo vanish 

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#964]
### Steps to reproduce

1. open a room
2. scroll back a few pages
3. double tap on a msg to react
4. observe no reaction shown at all
5. reopen room
6. now observe reaction

#### What did you expect?

reliable reactions

### Application version

223

### Will you send logs?

Yes

**Comment by ara4n** [comment]
@langleyd presumably this is fixed?

**Comment by pixlwave** [comment]
Testing just now and it works as expected.
