### ISSUE TITLE
Room cannot be joined through room link

### ISSUE THREAD

**Issue by habi** [vector-im/element-x-ios#966]
### Steps to reproduce

A room link was posted in a channel.
Clicking on it in Element X does nothing, clicking on it in Element opens the room and asks the user to join.

#### What did you expect?

Room is previewed and possibility to join is given.

#### What happened instead?

Nothing

### Your phone model

iPhone 12 mini

### Operating system version

16.5

### Application version

1.1.1 (48)

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by habi** [comment]
![IMG_3721](https://github.com/vector-im/element-x-ios/assets/1651235/ad23349a-cadd-4277-8e75-b9d489c57f7c)
redacted Element screenshot

**Comment by grahamperrin** [comment]
I guess, _spaces_ fall under the same umbrella.

**Comment by VolkerJunginger** [comment]
Feature not build yet.
