### ISSUE TITLE
App now takes ~10s to incr sync

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#970]
### Steps to reproduce

1. Use the app
2. Background it, either in a timeline or a roomlist
3. Do something else for 10-60m
4. Foreground it
5. Stare at a “Loading…” spinner for at least 10s (i had one which i gave up waiting for).

This happens on good connectivity.

#### What did you expect?

Less than 100ms to incr sync; this is the whole point of SS and EX.

#### What happened instead?

Feels as slow as Element iOS

Build 223 was fine; build 226 not so much.

There’s a chance that the perf has always been this bad, but it was impossible to see given the Loading… status was unreliable?

### Application version

226

### Will you send logs?

Yes

**Comment by ara4n** [comment]
looks like this was an initial sync (as you'd expect after 30m of bg) - which synced 4.6MB of data.

This is roughly 10x too much: before we land delta tokens, i'd expect my initial sync to be ~400KB of account data (mainly DM maps) and ~100KB of per-room data in total for the ~20 rooms at the top of the visible rooms list.

So, possible guesses:
 * allrooms has snuck into the initial SS req (whereas it should be set up in the bg)
 * we're paginating too much timeline when setting up visible rooms (limit should be 0, and then, in bg: 1 and then 20, to prevent precisely this sort of thing)
 * ...?

I haven't waded through the logs to check.

**Comment by ara4n** [comment]
looks like it's:

> allrooms has snuck into the initial SS req (whereas it should be set up in the bg)

once a session expires, we should set up allrooms in the bg, rather than throwing it straight back into the mix and blocking on it.

**Comment by ara4n** [comment]
It's worth highlighting that there may be two separate bugs here:
 * one where Loading hangs around for ~10s
 * one where Loading hangs around forever (which both I and @clokep have also seen - rageshake linked above).

**Comment by ara4n** [comment]
have split the stuck forever one into https://github.com/vector-im/element-x-ios/issues/999

**Comment by ara4n** [comment]
I looked at the logs. there are various different reasons causing 10s of delays.

The original [one](https://github.com/vector-im/element-x-ios-rageshakes/issues/390) was due to SS incorrectly using an expanded allrooms view after SS expired.  I believe @Hywan fixed this.

Then there's [one](https://github.com/vector-im/element-x-ios-rageshakes/issues/391) where the SS req itself took 11s to return (but the window sizes were sensible). I think this might have been the SS proxy was overloaded a few weeks ago, which K fixed.

Then, there's a separate failure mode [here](https://github.com/vector-im/element-x-ios-rageshakes/issues/451) and [here](https://github.com/vector-im/element-x-ios-rageshakes/issues/456) where it turns out that rust-sdk will block on pending /key/query reqs before processing the initial SS response.  So if those key queries hit a server which is down, it'll block for 10s until the federation key req times out, blocking startup.  This happens at https://github.com/matrix-org/matrix-rust-sdk/blob/6fc90609b6af4bfda62cb3c91655874806a6b775/crates/matrix-sdk/src/sliding_sync/mod.rs#L458-L460.

So hopefully the only actual issue here remaining is to stop rust-sdk's SS processing getting unnecessarily blocked behind other slow reqs.

**Comment by Hywan** [comment]
We have 2 solutions for this:

1. Run a different sync-loop dedicated only to E2EE, which is what https://github.com/matrix-org/matrix-rust-sdk/issues/1928 is supposed to fix, with an implementation by @bnjbvr at https://github.com/matrix-org/matrix-rust-sdk/pull/2110 (under review)
2. Spawn a new task in `sliding_sync/mod.rs` (your link above) to handle E2EE.

I think we should explore both. (1) is more important for us at Element, but (2) might be important for other users.

**Comment by manuroe** [comment]
> Then, there's a separate failure mode https://github.com/vector-im/element-x-ios-rageshakes/issues/451 and https://github.com/vector-im/element-x-ios-rageshakes/issues/456 where it turns out that rust-sdk will block on pending /key/query reqs before processing the initial SS response. So if those key queries hit a server which is down, it'll block for 10s until the federation key req times out, blocking startup. This happens at https://github.com/matrix-org/matrix-rust-sdk/blob/6fc90609b6af4bfda62cb3c91655874806a6b775/crates/matrix-sdk/src/sliding_sync/mod.rs#L458-L460.

This will happen with https://github.com/matrix-org/matrix-rust-sdk/issues/1928. This specific case is actually already managed and tested.

Removing the blocker tag for now as it is an edge cage.

**Comment by ara4n** [comment]
> The original https://github.com/vector-im/element-x-ios-rageshakes/issues/390 was due to SS incorrectly using an expanded allrooms view after SS expired. I believe @Hywan fixed this.

I just saw this again on build 269; have rageshaked.

**Comment by Hywan** [comment]
Yup, I said in https://github.com/vector-im/element-x-ios-rageshakes/issues/540, you've a special build (269) that removes the “refresh all_rooms” mechanism, and that's why you've those bugs.

**Comment by ara4n** [comment]
other than the risk of blocking on /keys/query solved by https://github.com/matrix-org/matrix-rust-sdk/issues/1928, this is fixed.
