### ISSUE TITLE
Warn during initial SS sync while the proxy is warming up

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#983]
The fact that the very first SS sync still takes multiple seconds/minutes is a horrible black eye for EX... unless we explicitly warn the user what's going on and explain that it's literally a once off for their account.

This bit investors badly last week when I finally got EIX TF to them.

**Comment by manuroe** [comment]
@kegsay is there a way to know the proxy is running the very first SS sync?

**Comment by ara4n** [comment]
no, there isn't currently. we could definite a special account data event or something which gets returned as a dummy initial SS response if the proxy is having to do a migration?

**Comment by ara4n** [comment]
Actually, can we do this by having the client query its /devices after /login to see if there is a SS proxy listed in /devices, and if there isn't, show a "warning, first login takes a while" prompt?

**Comment by manuroe** [comment]
Will happen with in this [user story ](https://github.com/vector-im/element-meta/issues/1805).

**Comment by pixlwave** [comment]
Making in a note in the issue: For now we're going to implement this by adding the user's ID to a dictionary in UserDefaults once they have successfully completed a sync and only show the screen if their user ID isn't included. Its not ideal but given time constraints and lack of information from the server, its the most direct route to achieve what we're looking for.

**Comment by ara4n** [comment]
hang on - are you sure? we only need to show this for the first ever login to the SS proxy; tracking stuff in UserDefaults will be irrelevant?

Is there a reason why "call /login, call /devices; if you see "Element X" listed in the devices, then you know the user is already using Element X, and you don't display the 'migrating to Sliding Sync' screen" doesn't work?

**Comment by manuroe** [comment]
We want a dumb implementation for that. We do not expect to support multi-device users.  
Checking `/devices` means we will display this screen every time a user logs out and logs in on their single device. Plus, it is another HTTP call.

**Comment by pixlwave** [comment]
Closed by https://github.com/vector-im/element-x-ios/pull/1224
