### ISSUE TITLE
Nag the user if they disable push.

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#992]
Most messaging apps (e.g. WhatsApp, Threema) yell loudly at you if you disable their push notifs, given the app is basically useless without notifs.  We should detect this and loudly warn the user to reenable them if this happens.

(Hopefully this would also catch https://github.com/vector-im/element-x-ios/issues/991 - caused by the devicetoken for the app no longer being successfully registered with apple)

**Comment by pixlwave** [comment]
@giomfo I'm sure I've seen this covered by an existing issue/user story already, but failing to find it. Am I right or just imagining it?

**Comment by giomfo** [comment]
@pixlwave yes this has been covered by this PR: https://github.com/vector-im/element-x-ios/pull/1273

**Comment by pixlwave** [comment]
Thanks, closing this issue then 👍
