### ISSUE TITLE
App can get stuck Loading… forever

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-x-ios#999]
### Steps to reproduce

1. foreground the app on bad data
2. stare at the loading overlay for 20s or so
3. switch to good data
4. the loading overlay never goes away

i think this is different but related to https://github.com/vector-im/element-x-ios/issues/970

#### What did you expect?

instant loading, and quick recovery if you switch from bad to good data

#### What happened instead?

app gets stuck loading.

### Application version

228

### Will you send logs?

Yes

**Comment by stefanceriu** [comment]
Most likely fixed by https://github.com/matrix-org/matrix-rust-sdk/pull/1992 and https://github.com/vector-im/element-x-ios/pull/998

**Comment by ara4n** [comment]
just had it again - again, while shifting between network during launching

**Comment by stefanceriu** [comment]
I had a look through all the logs here but I can't find a place in which sliding sync is failing, the room list mode isn't set to showing rooms or the list itself stays empty. I have no idea what's happening but it's probably best we investigate further once the new room list api gets adopted

**Comment by ara4n** [comment]
i haven't seen this since the roomlist api landed
